#pragma once
/*
# ======================================================================================== #
# > ArcticCombat SDK
# > Generated By HJSdkGen v1.06b
# ---------------------------------------------------------------------------------------- #
# > Package : WWeapons
# >    File : WWeapons\WWeapons.h
# ======================================================================================== #
*/


/*
# ======================================================================================== #
# > Forward Declarations
# ======================================================================================== #
*/

class AwAirStrikeProj;
class AwWeapon_Turret_FNM240;
class AwRocketLauncher;
class UwTurret_FNM240_Fire;
class AwGunAttachment;
class AwTurretAttachmet;
class UwRocketFire;
class AwAirStrikeBomb;
class AwThrowingWeapon;
class UwThrowingFire;
class AwGrenade;

/*
# ======================================================================================== #
# > Includes
# ======================================================================================== #
*/

#include "Structs.h"
#include "ParamStructs.h"
#include "Classes.h"
