class wWeaponRes_M14 extends wWeaponRes_Base;

defaultproperties
{
    szClass_Shell="Xeffects.ShellSpewer_762"
    szClass_Shell_3rd="Xeffects.ShellSpewer_762_3rd"
    fTracerPop=1.0000000
    szClass_Muzz_1st="Xeffects.SR_MuzFlash_04_1RD"
    szClass_Muzz_3rd="Xeffects.SR_MuzFlash_04_3RD"
    szClass_Smoke_1st="XEffects.AssaultMuzzleSmoke"
    szClass_Smoke_3rd="Xeffects.SR_MuzFlash_smoke_3rd"
    effect_Melee_Attack1=Class'XEffects.HitEffect_Stock_Meleeattack'
    effect_Melee_Attack2=Class'XEffects.HitEffect_Stock_Meleeattack'
    szIcon_HUD="Warfare_UI_Item.HUDIcon.Item_HUD_WP_AR_M14"
    szIcon_Kill="Warfare_UI_Item.Item_killIcon"
    ibIcon_Kill=(X=384,Y=138,W=128,H=32)
    szType_DisplayAmmo="ammo50"
    fsound_Fire="Warfare_Sound_Weapon/AR/M14/fire"
    fsound_Fire_Stereo="Warfare_Sound_Weapon/AR/M14/fire_s"
    fSound_Fire_Silencer="Warfare_Sound_Weapon/AR/M14/fire_silencer"
    fsound_Fire_Silencer_Stereo="Warfare_Sound_Weapon/AR/M14/fire_silencer_s"
    fsound_Fire_Shell="Warfare_Sound_Weapon/ETC/shell/shell_762mm"
    fsound_Fire_Empty="Warfare_Sound_Weapon/ETC/dryfire/weapon_ar_fire_nobullet"
    fsound_Melee_Ok="Warfare_Sound_Weapon/ETC/buttplate/weapon_melee_buttplate_attack"
    fsound_Melee_Miss="Warfare_Sound_Weapon/ETC/buttplate/weapon_melee_buttplate_miss"
    fsound_Reload="Warfare_Sound_Weapon/AR/M14/reload"
    fsound_ReloadEmpty="Warfare_Sound_Weapon/AR/M14/reload_empty"
    fsound_Select="Warfare_Sound_Weapon/AR/M14/select"
    fsound_Pickup="Warfare_Sound_Char/GetItem/char_getitem_weapon"
    fsound_Select_New="Warfare_Sound_Weapon/AR/M14/select_n"
}