#pragma once
/*
# ======================================================================================== #
# > ArcticCombat SDK
# > Generated By HJSdkGen v1.06b
# ---------------------------------------------------------------------------------------- #
# > Package : D3D9Drv
# >    File : Classes.h
# ======================================================================================== #
*/

#ifdef _MSC_VER
#pragma pack ( push, 4 )
#endif


/*
# ======================================================================================== #
# > Classes
# ======================================================================================== #
*/

// Class D3D9Drv.D3D9RenderDevice
class DLL_IMPORT UD3D9RenderDevice : public URenderDevice
{
public:
	unsigned char                                      _0x00C4[ 0x403C ];                                		// 0x00C4 ( 0x403C )
	unsigned long                                      UseVSync:1;                                       		// 0x4100 ( 0x0004 )  [0x00000001][ CPF_Edit ]
	unsigned char                                      _0x4104[ 0x80 ];                                  		// 0x4104 ( 0x0080 )
	int                                                LevelOfAnisotropy;                                		// 0x4184 ( 0x0004 ) [ CPF_Edit ]
	unsigned char                                      _0x4188[ 0x37770 ];                               		// 0x4188 ( 0x37770 )

	// Public Imports
	UD3D9RenderDevice(class UD3D9RenderDevice const &);
	UD3D9RenderDevice(void);
	class UD3D9RenderDevice &  operator=(class UD3D9RenderDevice const &);
	class FD3D9Resource *  GetCachedResource(unsigned __int64);
	class FD3D9PixelShader *  GetPixelShader(enum EPixelShader);
	class FD3D9VertexShader *  GetVertexShader(enum EVertexShader,struct FShaderDeclaration &);
	static void  InternalConstructor(void *);
	static class UClass *  StaticClass(void);
	void  StaticConstructor(void);
	int  UnSetRes(unsigned short const *,long,int);

	// Private Imports
private:
	static class UClass PrivateStaticClass;
}; // Size: 0x3B834

// Class D3D9Drv.D3D9BtrTexture
class DLL_IMPORT UD3D9BtrTexture : public UBtrTexture
{
public:
	unsigned char                                      _0x002C[ 0x10 ];                                  		// 0x002C ( 0x0010 )

	// Public Imports
	UD3D9BtrTexture(class UD3D9BtrTexture const &);
	UD3D9BtrTexture(void);
	class UD3D9BtrTexture &  operator=(class UD3D9BtrTexture const &);
	static void  InternalConstructor(void *);
	static class UClass *  StaticClass(void);

	// Private Imports
private:
	static class UClass PrivateStaticClass;
}; // Size: 0x0010

#ifdef _MSC_VER
#pragma pack ( pop )
#endif

