#pragma once
/*
# ======================================================================================== #
# > ArcticCombat SDK
# > Generated By HJSdkGen v1.06b
# ---------------------------------------------------------------------------------------- #
# > Package : GUIWarfare
# >    File : GUIWarfare\GUIWarfare.h
# ======================================================================================== #
*/


/*
# ======================================================================================== #
# > Forward Declarations
# ======================================================================================== #
*/

class UBTConsole;
class UBTNetGUIPage;
class UBTNetMainMenu;
class UBTNetGUIPageHK;
class UBTNetQuestInfoPageHK;
class UBTPageRoomLobby;
class UBTTcpHandler;
class UBTPageLogo;
class UBTPageLogin;
class UBTPageCharacterCreation;
class UBTPageLobby;
class UBTPageServerSelection;
class UBTPageMatchResult;
class UBTPageAuction;
class UBTPageHelp;
class UBTPageMail;
class UBTPageStore;
class UBTPageInventory;
class UBTPageMyInfo;
class UBTPageClan;
class UBTPageCredit;
class UBTPageClanWar;
class UBTTcpLoginHandler;
class UBTWindowItemExpiredHK;
class UBTTcpHandlerMed;
class UBTLabelNoticeHK;
class UBTTPAASHK;
class UBTPageRoomLobby_TcpLogin;
class UBTPageRoomLobby_TCP;
class UBTRefreshTime;
class UBTWindowItemDurabilityWarningHK;
class UBTPageServerSelection_TcpLogin;
class UBTPageServerSelection_TCP;
class UBTPageLobby_TcpLogin;
class UBTPageLobby_TCP;
class UBTNuclearButtonHK;
class UBTPageInventory_TCP;
class UBTPageClanWar_TCP;
class UBTPageClan_TCP;
class UBTPageAuction_TCP;
class UBTPageMail_TCP;
class UBTPageLogo_TcpLogin;
class UBTPageLogin_TcpLogin;
class UBTPageStore_TCP;
class UBTPageMyInfo_TCP;
class UBTPageCharacterCreation_TcpLogin;
class UBTPageMatchResult_TCP;
class UBTPageHelp_TCP;
class UBTPageServerSelectionCN;
class UBTPageLobbyCN;

/*
# ======================================================================================== #
# > Includes
# ======================================================================================== #
*/

#include "Structs.h"
#include "ParamStructs.h"
#include "Classes.h"
