#pragma once
/*
# ======================================================================================== #
# > ArcticCombat SDK
# > Generated By HJSdkGen v1.06b
# ---------------------------------------------------------------------------------------- #
# > Package : GUIWarfare
# >    File : Structs.h
# ======================================================================================== #
*/

#ifdef _MSC_VER
#pragma pack ( push, 4 )
#endif


/*
# ======================================================================================== #
# > Structs
# ======================================================================================== #
*/

// Struct GUIWarfare.BTNetGUIPage.ChatInfo
struct DLL_IMPORT FChatInfo
{
	int                                                ChatType;                                         		// 0x0000 ( 0x0004
	struct FString                                     ChatTo;                                           		// 0x0004 ( 0x000C[ CPF_NeedCtorLink ]
	struct FString                                     chatText;                                         		// 0x0010 ( 0x000C[ CPF_NeedCtorLink ]
}; // Size: 0x001C

// Struct GUIWarfare.BTNetMainMenu.ServerConnectionInfo
struct DLL_IMPORT FServerConnectionInfo
{
	int                                                ServerID;                                         		// 0x0000 ( 0x0004
	int                                                ChannelID;                                        		// 0x0004 ( 0x0004
	struct FString                                     ServerIP;                                         		// 0x0008 ( 0x000C[ CPF_NeedCtorLink ]
	int                                                serverPort;                                       		// 0x0014 ( 0x0004
	int                                                ServerDataPort;                                   		// 0x0018 ( 0x0004
	struct FString                                     ServerName;                                       		// 0x001C ( 0x000C[ CPF_NeedCtorLink ]
	struct FString                                     ServerShortName;                                  		// 0x0028 ( 0x000C[ CPF_NeedCtorLink ]
	struct FString                                     ChannelName;                                      		// 0x0034 ( 0x000C[ CPF_NeedCtorLink ]
	int                                                ServerGroupID;                                    		// 0x0040 ( 0x0004
	struct FString                                     ServerGroupName;                                  		// 0x0044 ( 0x000C[ CPF_NeedCtorLink ]
	int                                                IsClanChannel;                                    		// 0x0050 ( 0x0004
	struct FString                                     ChannelNickName;                                  		// 0x0054 ( 0x000C[ CPF_NeedCtorLink ]
	int                                                ChannelTypeValue;                                 		// 0x0060 ( 0x0004
	unsigned long                                      IsDedicatedServer:1;                              		// 0x0064 ( 0x0004 [0x00000001]
	int                                                nCurUser;                                         		// 0x0068 ( 0x0004
	int                                                nMaxUser;                                         		// 0x006C ( 0x0004
}; // Size: 0x0070

// Struct GUIWarfare.BTNetMainMenu.AAS_Struct
struct DLL_IMPORT FAAS_Struct
{
	unsigned char                                      Level;                                            		// 0x0000 ( 0x0001
	unsigned long                                      Activated:1;                                      		// 0x0004 ( 0x0004 [0x00000001]
	struct FString                                     Text;                                             		// 0x0008 ( 0x000C[ CPF_NeedCtorLink ]
	float                                              Time;                                             		// 0x0014 ( 0x0004
	int                                                iRepeatTime;                                      		// 0x0018 ( 0x0004
	int                                                iCount;                                           		// 0x001C ( 0x0004
	float                                              fBeginTime;                                       		// 0x0020 ( 0x0004
}; // Size: 0x0024

// Struct GUIWarfare.BTNetMainMenu.ChatHistory
struct DLL_IMPORT FChatHistory
{
	int                                                ChatType;                                         		// 0x0000 ( 0x0004
	struct FString                                     chatText;                                         		// 0x0004 ( 0x000C[ CPF_NeedCtorLink ]
}; // Size: 0x0010

// Struct GUIWarfare.BTNetMainMenu.EachDurabilityWarningItem
struct DLL_IMPORT FEachDurabilityWarningItem
{
	struct FBtrDouble                                  UniqueID;                                         		// 0x0000 ( 0x0008
	int                                                ItemID;                                           		// 0x0008 ( 0x0004
	int                                                SlotPos;                                          		// 0x000C ( 0x0004
	int                                                PartID;                                           		// 0x0010 ( 0x0004
	int                                                Durability;                                       		// 0x0014 ( 0x0004
	int                                                RepairCost;                                       		// 0x0018 ( 0x0004
}; // Size: 0x001C

// Struct GUIWarfare.BTNetMainMenu.DurabilityWarningItemsStruct
struct DLL_IMPORT FDurabilityWarningItemsStruct
{
	unsigned long                                      bDurWarningItem:1;                                		// 0x0000 ( 0x0004 [0x00000001]
	unsigned long                                      bReqRepairCost:1;                                 		// 0x0000 ( 0x0004 [0x00000002]
	class TArray< struct FEachDurabilityWarningItem >  items;                                            		// 0x0004 ( 0x000C[ CPF_NeedCtorLink ]
}; // Size: 0x0010

// Struct GUIWarfare.BTNetMainMenu.EachExpiredItem
struct DLL_IMPORT FEachExpiredItem
{
	int                                                ItemID;                                           		// 0x0000 ( 0x0004
	int                                                SlotPos;                                          		// 0x0004 ( 0x0004
	int                                                PartID;                                           		// 0x0008 ( 0x0004
	struct FBtrDouble                                  UniqueItemID;                                     		// 0x000C ( 0x0008
	int                                                UniqueSkillID;                                    		// 0x0014 ( 0x0004
}; // Size: 0x0018

// Struct GUIWarfare.BTNetMainMenu.ExpiredItemsStruct
struct DLL_IMPORT FExpiredItemsStruct
{
	unsigned long                                      bExpiredItem:1;                                   		// 0x0000 ( 0x0004 [0x00000001]
	class TArray< struct FEachExpiredItem >            items;                                            		// 0x0004 ( 0x000C[ CPF_NeedCtorLink ]
}; // Size: 0x0010

// Struct GUIWarfare.BTNetMainMenu.WZInvenListProcess
struct DLL_IMPORT FWZInvenListProcess
{
	unsigned long                                      bLock:1;                                          		// 0x0000 ( 0x0004 [0x00000001]
	int                                                MaxPage;                                          		// 0x0004 ( 0x0004
	int                                                CurPage;                                          		// 0x0008 ( 0x0004
	int                                                CountPerPage;                                     		// 0x000C ( 0x0004
	struct FString                                     StorageType;                                      		// 0x0010 ( 0x000C[ CPF_NeedCtorLink ]
}; // Size: 0x001C

// Struct GUIWarfare.BTNetMainMenu.LevelUpInfoStruct
struct DLL_IMPORT FLevelUpInfoStruct
{
	unsigned long                                      bLevelUp:1;                                       		// 0x0000 ( 0x0004 [0x00000001]
	unsigned long                                      bCompleteLevelUp:1;                               		// 0x0000 ( 0x0004 [0x00000002]
	int                                                Level;                                            		// 0x0004 ( 0x0004
	int                                                Exp;                                              		// 0x0008 ( 0x0004
	class TArray< int >                                ItemID;                                           		// 0x000C ( 0x000C[ CPF_NeedCtorLink ]
	class TArray< int >                                PartID;                                           		// 0x0018 ( 0x000C[ CPF_NeedCtorLink ]
}; // Size: 0x0024

// Struct GUIWarfare.BTNetMainMenu.MapNameInfo
struct DLL_IMPORT FMapNameInfo
{
	struct FString                                     FriendlyName;                                     		// 0x0000 ( 0x000C[ CPF_NeedCtorLink ]
	struct FString                                     fileName;                                         		// 0x000C ( 0x000C[ CPF_NeedCtorLink ]
}; // Size: 0x0018

// Struct GUIWarfare.BTPageServerSelection.ConnectingInfo
struct DLL_IMPORT FConnectingInfo
{
	int                                                ServerID;                                         		// 0x0000 ( 0x0004
	int                                                ChannelID;                                        		// 0x0004 ( 0x0004
	struct FString                                     IP;                                               		// 0x0008 ( 0x000C[ CPF_NeedCtorLink ]
	int                                                Port;                                             		// 0x0014 ( 0x0004
	int                                                DataPort;                                         		// 0x0018 ( 0x0004
}; // Size: 0x001C

// Struct GUIWarfare.BTPageServerSelection.CheckToReceivedPacket
struct DLL_IMPORT FCheckToReceivedPacket
{
	unsigned long                                      bItemListEnd:1;                                   		// 0x0000 ( 0x0004 [0x00000001]
	unsigned long                                      bSkillListEnd:1;                                  		// 0x0000 ( 0x0004 [0x00000002]
	unsigned long                                      bQSListEnd:1;                                     		// 0x0000 ( 0x0004 [0x00000004]
	unsigned long                                      bServerTimeEnd:1;                                 		// 0x0000 ( 0x0004 [0x00000008]
	unsigned long                                      bGetMyMailBoxState:1;                             		// 0x0000 ( 0x0004 [0x00000010]
	unsigned long                                      bGetServerTimeEnd:1;                              		// 0x0000 ( 0x0004 [0x00000020]
	unsigned long                                      bHashEnd:1;                                       		// 0x0000 ( 0x0004 [0x00000040]
}; // Size: 0x0004

// Struct GUIWarfare.BTWindowItemExpiredHK.BuyExpriedCashInfo
struct DLL_IMPORT FBuyExpriedCashInfo
{
	class TArray< int >                                CashElements;                                     		// 0x0000 ( 0x000C[ CPF_NeedCtorLink ]
}; // Size: 0x000C

// Struct GUIWarfare.BTPageAuction.SearchAuctionItem
struct DLL_IMPORT FSearchAuctionItem
{
	unsigned long                                      bLock:1;                                          		// 0x0000 ( 0x0004 [0x00000001]
	int                                                Section;                                          		// 0x0004 ( 0x0004
	struct FString                                     Keyword;                                          		// 0x0008 ( 0x000C[ CPF_NeedCtorLink ]
	int                                                ItemRank;                                         		// 0x0014 ( 0x0004
	unsigned char                                      ItemClassify;                                     		// 0x0018 ( 0x0001
	unsigned char                                      IsAvailable;                                      		// 0x0019 ( 0x0001
	int                                                CurrentPageNum;                                   		// 0x001C ( 0x0004
	int                                                PagePerCount;                                     		// 0x0020 ( 0x0004
	int                                                SortType;                                         		// 0x0024 ( 0x0004
}; // Size: 0x0028

// Struct GUIWarfare.BTPageMail.ReceiveMode
struct DLL_IMPORT FReceiveMode
{
	unsigned long                                      bLock:1;                                          		// 0x0000 ( 0x0004 [0x00000001]
	int                                                RequestMailType;                                  		// 0x0004 ( 0x0004
	int                                                RequestItemType;                                  		// 0x0008 ( 0x0004
	int                                                TotalCount;                                       		// 0x000C ( 0x0004
}; // Size: 0x0010

#ifdef _MSC_VER
#pragma pack ( pop )
#endif

