#include "stdafx.h"
/*
# ======================================================================================== #
# > ArcticCombat SDK
# > Generated By HJSdkGen v1.06b
# ---------------------------------------------------------------------------------------- #
# > Package : BTData
# >    File : Code.cpp
# ======================================================================================== #
*/

/*struct FName UBTNetPlayerData::getNameData ( struct FString category, struct FString key, int iIndex )
{
	static UFunction* pgetNameData = 0;
	UBTNetPlayerData_execgetNameData_Parms parms;

	if ( !pgetNameData )
		pgetNameData = ( UFunction* )UFunction::StaticFindObject ( UFunction::StaticClass(), NULL, L"BTData.BTNetPlayerData.getNameData" );

	parms.category = category;
	parms.key = key;
	parms.iIndex = iIndex;
	this->ProcessEvent ( pgetNameData, &parms, NULL );

	return parms.ReturnValue;
}*/

/*struct FString UBTNetPlayerData::getData ( struct FString category, struct FString key, int iIndex )
{
	static UFunction* pgetData = 0;
	UBTNetPlayerData_execgetData_Parms parms;

	if ( !pgetData )
		pgetData = ( UFunction* )UFunction::StaticFindObject ( UFunction::StaticClass(), NULL, L"BTData.BTNetPlayerData.getData" );

	parms.category = category;
	parms.key = key;
	parms.iIndex = iIndex;
	this->ProcessEvent ( pgetData, &parms, NULL );

	return parms.ReturnValue;
}*/

/*bool UBTNetPlayerData::LoadPlayerMoveParams (  )
{
	static UFunction* pLoadPlayerMoveParams = 0;
	UBTNetPlayerData_execLoadPlayerMoveParams_Parms parms;

	if ( !pLoadPlayerMoveParams )
		pLoadPlayerMoveParams = ( UFunction* )UFunction::StaticFindObject ( UFunction::StaticClass(), NULL, L"BTData.BTNetPlayerData.LoadPlayerMoveParams" );

	this->ProcessEvent ( pLoadPlayerMoveParams, &parms, NULL );

	return parms.ReturnValue;
}*/

/*bool UBTNetPlayerData::LoadPlayerAnimationData (  )
{
	static UFunction* pLoadPlayerAnimationData = 0;
	UBTNetPlayerData_execLoadPlayerAnimationData_Parms parms;

	if ( !pLoadPlayerAnimationData )
		pLoadPlayerAnimationData = ( UFunction* )UFunction::StaticFindObject ( UFunction::StaticClass(), NULL, L"BTData.BTNetPlayerData.LoadPlayerAnimationData" );

	this->ProcessEvent ( pLoadPlayerAnimationData, &parms, NULL );

	return parms.ReturnValue;
}*/

/*bool UBTNetPlayerData::LoadPlayerPartsData (  )
{
	static UFunction* pLoadPlayerPartsData = 0;
	UBTNetPlayerData_execLoadPlayerPartsData_Parms parms;

	if ( !pLoadPlayerPartsData )
		pLoadPlayerPartsData = ( UFunction* )UFunction::StaticFindObject ( UFunction::StaticClass(), NULL, L"BTData.BTNetPlayerData.LoadPlayerPartsData" );

	this->ProcessEvent ( pLoadPlayerPartsData, &parms, NULL );

	return parms.ReturnValue;
}*/

/*struct FString UBTNetMapData::getData ( struct FString category, struct FString key, int iIndex )
{
	static UFunction* pgetData = 0;
	UBTNetMapData_execgetData_Parms parms;

	if ( !pgetData )
		pgetData = ( UFunction* )UFunction::StaticFindObject ( UFunction::StaticClass(), NULL, L"BTData.BTNetMapData.getData" );

	parms.category = category;
	parms.key = key;
	parms.iIndex = iIndex;
	this->ProcessEvent ( pgetData, &parms, NULL );

	return parms.ReturnValue;
}*/

/*bool UBTNetMapData::LoadMapData (  )
{
	static UFunction* pLoadMapData = 0;
	UBTNetMapData_execLoadMapData_Parms parms;

	if ( !pLoadMapData )
		pLoadMapData = ( UFunction* )UFunction::StaticFindObject ( UFunction::StaticClass(), NULL, L"BTData.BTNetMapData.LoadMapData" );

	this->ProcessEvent ( pLoadMapData, &parms, NULL );

	return parms.ReturnValue;
}*/

/*void UBTNetGameData::ClearNetData (  )
{
	static UFunction* pClearNetData = 0;
	UBTNetGameData_execClearNetData_Parms parms;

	if ( !pClearNetData )
		pClearNetData = ( UFunction* )UFunction::StaticFindObject ( UFunction::StaticClass(), NULL, L"BTData.BTNetGameData.ClearNetData" );

	this->ProcessEvent ( pClearNetData, &parms, NULL );

}*/

/*bool UBTNetGameData::LoadModeDOAParams (  )
{
	static UFunction* pLoadModeDOAParams = 0;
	UBTNetGameData_execLoadModeDOAParams_Parms parms;

	if ( !pLoadModeDOAParams )
		pLoadModeDOAParams = ( UFunction* )UFunction::StaticFindObject ( UFunction::StaticClass(), NULL, L"BTData.BTNetGameData.LoadModeDOAParams" );

	this->ProcessEvent ( pLoadModeDOAParams, &parms, NULL );

	return parms.ReturnValue;
}*/

/*bool UBTNetGameData::LoadSupplyRandomTable (  )
{
	static UFunction* pLoadSupplyRandomTable = 0;
	UBTNetGameData_execLoadSupplyRandomTable_Parms parms;

	if ( !pLoadSupplyRandomTable )
		pLoadSupplyRandomTable = ( UFunction* )UFunction::StaticFindObject ( UFunction::StaticClass(), NULL, L"BTData.BTNetGameData.LoadSupplyRandomTable" );

	this->ProcessEvent ( pLoadSupplyRandomTable, &parms, NULL );

	return parms.ReturnValue;
}*/

/*bool UBTNetGameData::LoadClanLevelInfoParams (  )
{
	static UFunction* pLoadClanLevelInfoParams = 0;
	UBTNetGameData_execLoadClanLevelInfoParams_Parms parms;

	if ( !pLoadClanLevelInfoParams )
		pLoadClanLevelInfoParams = ( UFunction* )UFunction::StaticFindObject ( UFunction::StaticClass(), NULL, L"BTData.BTNetGameData.LoadClanLevelInfoParams" );

	this->ProcessEvent ( pLoadClanLevelInfoParams, &parms, NULL );

	return parms.ReturnValue;
}*/

/*bool UBTNetGameData::LoadLevelInfoParams (  )
{
	static UFunction* pLoadLevelInfoParams = 0;
	UBTNetGameData_execLoadLevelInfoParams_Parms parms;

	if ( !pLoadLevelInfoParams )
		pLoadLevelInfoParams = ( UFunction* )UFunction::StaticFindObject ( UFunction::StaticClass(), NULL, L"BTData.BTNetGameData.LoadLevelInfoParams" );

	this->ProcessEvent ( pLoadLevelInfoParams, &parms, NULL );

	return parms.ReturnValue;
}*/

/*bool UBTNetGameData::LoadItemBoxParams (  )
{
	static UFunction* pLoadItemBoxParams = 0;
	UBTNetGameData_execLoadItemBoxParams_Parms parms;

	if ( !pLoadItemBoxParams )
		pLoadItemBoxParams = ( UFunction* )UFunction::StaticFindObject ( UFunction::StaticClass(), NULL, L"BTData.BTNetGameData.LoadItemBoxParams" );

	this->ProcessEvent ( pLoadItemBoxParams, &parms, NULL );

	return parms.ReturnValue;
}*/

/*bool UBTNetGameData::LoadClanMarkParams (  )
{
	static UFunction* pLoadClanMarkParams = 0;
	UBTNetGameData_execLoadClanMarkParams_Parms parms;

	if ( !pLoadClanMarkParams )
		pLoadClanMarkParams = ( UFunction* )UFunction::StaticFindObject ( UFunction::StaticClass(), NULL, L"BTData.BTNetGameData.LoadClanMarkParams" );

	this->ProcessEvent ( pLoadClanMarkParams, &parms, NULL );

	return parms.ReturnValue;
}*/

/*bool UBTNetGameData::LoadDailyQuestParams (  )
{
	static UFunction* pLoadDailyQuestParams = 0;
	UBTNetGameData_execLoadDailyQuestParams_Parms parms;

	if ( !pLoadDailyQuestParams )
		pLoadDailyQuestParams = ( UFunction* )UFunction::StaticFindObject ( UFunction::StaticClass(), NULL, L"BTData.BTNetGameData.LoadDailyQuestParams" );

	this->ProcessEvent ( pLoadDailyQuestParams, &parms, NULL );

	return parms.ReturnValue;
}*/

/*bool UBTNetGameData::LoadRandBoxParams (  )
{
	static UFunction* pLoadRandBoxParams = 0;
	UBTNetGameData_execLoadRandBoxParams_Parms parms;

	if ( !pLoadRandBoxParams )
		pLoadRandBoxParams = ( UFunction* )UFunction::StaticFindObject ( UFunction::StaticClass(), NULL, L"BTData.BTNetGameData.LoadRandBoxParams" );

	this->ProcessEvent ( pLoadRandBoxParams, &parms, NULL );

	return parms.ReturnValue;
}*/

/*bool UBTNetGameData::LoadQuestParams (  )
{
	static UFunction* pLoadQuestParams = 0;
	UBTNetGameData_execLoadQuestParams_Parms parms;

	if ( !pLoadQuestParams )
		pLoadQuestParams = ( UFunction* )UFunction::StaticFindObject ( UFunction::StaticClass(), NULL, L"BTData.BTNetGameData.LoadQuestParams" );

	this->ProcessEvent ( pLoadQuestParams, &parms, NULL );

	return parms.ReturnValue;
}*/

/*bool UBTNetGameData::LoadPaintGroupParams (  )
{
	static UFunction* pLoadPaintGroupParams = 0;
	UBTNetGameData_execLoadPaintGroupParams_Parms parms;

	if ( !pLoadPaintGroupParams )
		pLoadPaintGroupParams = ( UFunction* )UFunction::StaticFindObject ( UFunction::StaticClass(), NULL, L"BTData.BTNetGameData.LoadPaintGroupParams" );

	this->ProcessEvent ( pLoadPaintGroupParams, &parms, NULL );

	return parms.ReturnValue;
}*/

/*bool UBTNetGameData::LoadPromotionParams (  )
{
	static UFunction* pLoadPromotionParams = 0;
	UBTNetGameData_execLoadPromotionParams_Parms parms;

	if ( !pLoadPromotionParams )
		pLoadPromotionParams = ( UFunction* )UFunction::StaticFindObject ( UFunction::StaticClass(), NULL, L"BTData.BTNetGameData.LoadPromotionParams" );

	this->ProcessEvent ( pLoadPromotionParams, &parms, NULL );

	return parms.ReturnValue;
}*/

/*bool UBTNetGameData::LoadAddPartsGroupParams (  )
{
	static UFunction* pLoadAddPartsGroupParams = 0;
	UBTNetGameData_execLoadAddPartsGroupParams_Parms parms;

	if ( !pLoadAddPartsGroupParams )
		pLoadAddPartsGroupParams = ( UFunction* )UFunction::StaticFindObject ( UFunction::StaticClass(), NULL, L"BTData.BTNetGameData.LoadAddPartsGroupParams" );

	this->ProcessEvent ( pLoadAddPartsGroupParams, &parms, NULL );

	return parms.ReturnValue;
}*/

/*bool UBTNetGameData::LoadSkillParams (  )
{
	static UFunction* pLoadSkillParams = 0;
	UBTNetGameData_execLoadSkillParams_Parms parms;

	if ( !pLoadSkillParams )
		pLoadSkillParams = ( UFunction* )UFunction::StaticFindObject ( UFunction::StaticClass(), NULL, L"BTData.BTNetGameData.LoadSkillParams" );

	this->ProcessEvent ( pLoadSkillParams, &parms, NULL );

	return parms.ReturnValue;
}*/

/*bool UBTNetGameData::LoadItemResourceParams (  )
{
	static UFunction* pLoadItemResourceParams = 0;
	UBTNetGameData_execLoadItemResourceParams_Parms parms;

	if ( !pLoadItemResourceParams )
		pLoadItemResourceParams = ( UFunction* )UFunction::StaticFindObject ( UFunction::StaticClass(), NULL, L"BTData.BTNetGameData.LoadItemResourceParams" );

	this->ProcessEvent ( pLoadItemResourceParams, &parms, NULL );

	return parms.ReturnValue;
}*/

/*bool UBTNetGameData::LoadItemParams (  )
{
	static UFunction* pLoadItemParams = 0;
	UBTNetGameData_execLoadItemParams_Parms parms;

	if ( !pLoadItemParams )
		pLoadItemParams = ( UFunction* )UFunction::StaticFindObject ( UFunction::StaticClass(), NULL, L"BTData.BTNetGameData.LoadItemParams" );

	this->ProcessEvent ( pLoadItemParams, &parms, NULL );

	return parms.ReturnValue;
}*/

/*bool UBTNetGameData::LoadWeaponRecoilParams (  )
{
	static UFunction* pLoadWeaponRecoilParams = 0;
	UBTNetGameData_execLoadWeaponRecoilParams_Parms parms;

	if ( !pLoadWeaponRecoilParams )
		pLoadWeaponRecoilParams = ( UFunction* )UFunction::StaticFindObject ( UFunction::StaticClass(), NULL, L"BTData.BTNetGameData.LoadWeaponRecoilParams" );

	this->ProcessEvent ( pLoadWeaponRecoilParams, &parms, NULL );

	return parms.ReturnValue;
}*/

/*bool UBTNetGameData::LoadWeaponParams (  )
{
	static UFunction* pLoadWeaponParams = 0;
	UBTNetGameData_execLoadWeaponParams_Parms parms;

	if ( !pLoadWeaponParams )
		pLoadWeaponParams = ( UFunction* )UFunction::StaticFindObject ( UFunction::StaticClass(), NULL, L"BTData.BTNetGameData.LoadWeaponParams" );

	this->ProcessEvent ( pLoadWeaponParams, &parms, NULL );

	return parms.ReturnValue;
}*/

/*bool UBTNetGameData::LoadWeaponRes (  )
{
	static UFunction* pLoadWeaponRes = 0;
	UBTNetGameData_execLoadWeaponRes_Parms parms;

	if ( !pLoadWeaponRes )
		pLoadWeaponRes = ( UFunction* )UFunction::StaticFindObject ( UFunction::StaticClass(), NULL, L"BTData.BTNetGameData.LoadWeaponRes" );

	this->ProcessEvent ( pLoadWeaponRes, &parms, NULL );

	return parms.ReturnValue;
}*/

/*struct FString UBTNetGameData::getData ( struct FString category, struct FString key, int iIndex )
{
	static UFunction* pgetData = 0;
	UBTNetGameData_execgetData_Parms parms;

	if ( !pgetData )
		pgetData = ( UFunction* )UFunction::StaticFindObject ( UFunction::StaticClass(), NULL, L"BTData.BTNetGameData.getData" );

	parms.category = category;
	parms.key = key;
	parms.iIndex = iIndex;
	this->ProcessEvent ( pgetData, &parms, NULL );

	return parms.ReturnValue;
}*/

/*bool UBTNetGameData::LoadAllData (  )
{
	static UFunction* pLoadAllData = 0;
	UBTNetGameData_execLoadAllData_Parms parms;

	if ( !pLoadAllData )
		pLoadAllData = ( UFunction* )UFunction::StaticFindObject ( UFunction::StaticClass(), NULL, L"BTData.BTNetGameData.LoadAllData" );

	this->ProcessEvent ( pLoadAllData, &parms, NULL );

	return parms.ReturnValue;
}*/

/*bool UBTNetGameData::LoadAddPaintGroupParams (  )
{
	static UFunction* pLoadAddPaintGroupParams = 0;
	UBTNetGameData_execLoadAddPaintGroupParams_Parms parms;

	if ( !pLoadAddPaintGroupParams )
		pLoadAddPaintGroupParams = ( UFunction* )UFunction::StaticFindObject ( UFunction::StaticClass(), NULL, L"BTData.BTNetGameData.LoadAddPaintGroupParams" );

	this->ProcessEvent ( pLoadAddPaintGroupParams, &parms, NULL );

	return parms.ReturnValue;
}*/

/*struct FString UBTNetExcelData::getData ( struct FString category, struct FString key, int iIndex )
{
	static UFunction* pgetData = 0;
	UBTNetExcelData_execgetData_Parms parms;

	if ( !pgetData )
		pgetData = ( UFunction* )UFunction::StaticFindObject ( UFunction::StaticClass(), NULL, L"BTData.BTNetExcelData.getData" );

	parms.category = category;
	parms.key = key;
	parms.iIndex = iIndex;
	this->ProcessEvent ( pgetData, &parms, NULL );

	return parms.ReturnValue;
}*/

/*bool UBTNetExcelData::LoadExcelData ( struct FString fileName, struct FString sheetName, int numHeadRows, int numHeadColumns, int nKeyColumnOrRow, int arrangeType )
{
	static UFunction* pLoadExcelData = 0;
	UBTNetExcelData_execLoadExcelData_Parms parms;

	if ( !pLoadExcelData )
		pLoadExcelData = ( UFunction* )UFunction::StaticFindObject ( UFunction::StaticClass(), NULL, L"BTData.BTNetExcelData.LoadExcelData" );

	parms.fileName = fileName;
	parms.sheetName = sheetName;
	parms.numHeadRows = numHeadRows;
	parms.numHeadColumns = numHeadColumns;
	parms.nKeyColumnOrRow = nKeyColumnOrRow;
	parms.arrangeType = arrangeType;
	this->ProcessEvent ( pLoadExcelData, &parms, NULL );

	return parms.ReturnValue;
}*/

