#pragma once
/*
# ======================================================================================== #
# > ArcticCombat SDK
# > Generated By HJSdkGen v1.06b
# ---------------------------------------------------------------------------------------- #
# > Package : BTData
# >    File : ParamStructs.h
# ======================================================================================== #
*/

#ifdef _MSC_VER
#pragma pack ( push, 4 )
#endif

// Function BTData.BTNetPlayerData.getNameData
// Flags: [ FUNC_Native ]
struct UBTNetPlayerData_execgetNameData_Parms
{
	struct FString                                     category;                                         		// 0x0000 ( 0x000C[ CPF_Parm | CPF_NeedCtorLink ]
	struct FString                                     key;                                              		// 0x000C ( 0x000C[ CPF_Parm | CPF_NeedCtorLink ]
	int                                                iIndex;                                           		// 0x0018 ( 0x0004[ CPF_Parm ]
	struct FName                                       ReturnValue;                                      		// 0x001C ( 0x0004[ CPF_Parm | CPF_OutParm | CPF_ReturnParm ]
};

// Function BTData.BTNetPlayerData.getData
// Flags: [ FUNC_Native ]
struct UBTNetPlayerData_execgetData_Parms
{
	struct FString                                     category;                                         		// 0x0000 ( 0x000C[ CPF_Parm | CPF_NeedCtorLink ]
	struct FString                                     key;                                              		// 0x000C ( 0x000C[ CPF_Parm | CPF_NeedCtorLink ]
	int                                                iIndex;                                           		// 0x0018 ( 0x0004[ CPF_Parm ]
	struct FString                                     ReturnValue;                                      		// 0x001C ( 0x000C[ CPF_Parm | CPF_OutParm | CPF_ReturnParm | CPF_NeedCtorLink ]
};

// Function BTData.BTNetPlayerData.LoadPlayerMoveParams
// Flags: [ FUNC_Native ]
struct UBTNetPlayerData_execLoadPlayerMoveParams_Parms
{
	unsigned long                                      ReturnValue:1;                                    		// 0x0000 ( 0x0004 [0x00000001][ CPF_Parm | CPF_OutParm | CPF_ReturnParm ]
};

// Function BTData.BTNetPlayerData.LoadPlayerAnimationData
// Flags: [ FUNC_Native ]
struct UBTNetPlayerData_execLoadPlayerAnimationData_Parms
{
	unsigned long                                      ReturnValue:1;                                    		// 0x0000 ( 0x0004 [0x00000001][ CPF_Parm | CPF_OutParm | CPF_ReturnParm ]
};

// Function BTData.BTNetPlayerData.LoadPlayerPartsData
// Flags: [ FUNC_Native ]
struct UBTNetPlayerData_execLoadPlayerPartsData_Parms
{
	unsigned long                                      ReturnValue:1;                                    		// 0x0000 ( 0x0004 [0x00000001][ CPF_Parm | CPF_OutParm | CPF_ReturnParm ]
};

// Function BTData.BTNetMapData.getData
// Flags: [ FUNC_Native ]
struct UBTNetMapData_execgetData_Parms
{
	struct FString                                     category;                                         		// 0x0000 ( 0x000C[ CPF_Parm | CPF_NeedCtorLink ]
	struct FString                                     key;                                              		// 0x000C ( 0x000C[ CPF_Parm | CPF_NeedCtorLink ]
	int                                                iIndex;                                           		// 0x0018 ( 0x0004[ CPF_Parm ]
	struct FString                                     ReturnValue;                                      		// 0x001C ( 0x000C[ CPF_Parm | CPF_OutParm | CPF_ReturnParm | CPF_NeedCtorLink ]
};

// Function BTData.BTNetMapData.LoadMapData
// Flags: [ FUNC_Native ]
struct UBTNetMapData_execLoadMapData_Parms
{
	unsigned long                                      ReturnValue:1;                                    		// 0x0000 ( 0x0004 [0x00000001][ CPF_Parm | CPF_OutParm | CPF_ReturnParm ]
};

// Function BTData.BTNetGameData.ClearNetData
// Flags: 
struct UBTNetGameData_execClearNetData_Parms
{
};

// Function BTData.BTNetGameData.LoadModeDOAParams
// Flags: [ FUNC_Native ]
struct UBTNetGameData_execLoadModeDOAParams_Parms
{
	unsigned long                                      ReturnValue:1;                                    		// 0x0000 ( 0x0004 [0x00000001][ CPF_Parm | CPF_OutParm | CPF_ReturnParm ]
};

// Function BTData.BTNetGameData.LoadSupplyRandomTable
// Flags: [ FUNC_Native ]
struct UBTNetGameData_execLoadSupplyRandomTable_Parms
{
	unsigned long                                      ReturnValue:1;                                    		// 0x0000 ( 0x0004 [0x00000001][ CPF_Parm | CPF_OutParm | CPF_ReturnParm ]
};

// Function BTData.BTNetGameData.LoadClanLevelInfoParams
// Flags: [ FUNC_Native ]
struct UBTNetGameData_execLoadClanLevelInfoParams_Parms
{
	unsigned long                                      ReturnValue:1;                                    		// 0x0000 ( 0x0004 [0x00000001][ CPF_Parm | CPF_OutParm | CPF_ReturnParm ]
};

// Function BTData.BTNetGameData.LoadLevelInfoParams
// Flags: [ FUNC_Native ]
struct UBTNetGameData_execLoadLevelInfoParams_Parms
{
	unsigned long                                      ReturnValue:1;                                    		// 0x0000 ( 0x0004 [0x00000001][ CPF_Parm | CPF_OutParm | CPF_ReturnParm ]
};

// Function BTData.BTNetGameData.LoadItemBoxParams
// Flags: [ FUNC_Native ]
struct UBTNetGameData_execLoadItemBoxParams_Parms
{
	unsigned long                                      ReturnValue:1;                                    		// 0x0000 ( 0x0004 [0x00000001][ CPF_Parm | CPF_OutParm | CPF_ReturnParm ]
};

// Function BTData.BTNetGameData.LoadClanMarkParams
// Flags: [ FUNC_Native ]
struct UBTNetGameData_execLoadClanMarkParams_Parms
{
	unsigned long                                      ReturnValue:1;                                    		// 0x0000 ( 0x0004 [0x00000001][ CPF_Parm | CPF_OutParm | CPF_ReturnParm ]
};

// Function BTData.BTNetGameData.LoadDailyQuestParams
// Flags: [ FUNC_Native ]
struct UBTNetGameData_execLoadDailyQuestParams_Parms
{
	unsigned long                                      ReturnValue:1;                                    		// 0x0000 ( 0x0004 [0x00000001][ CPF_Parm | CPF_OutParm | CPF_ReturnParm ]
};

// Function BTData.BTNetGameData.LoadRandBoxParams
// Flags: [ FUNC_Native ]
struct UBTNetGameData_execLoadRandBoxParams_Parms
{
	unsigned long                                      ReturnValue:1;                                    		// 0x0000 ( 0x0004 [0x00000001][ CPF_Parm | CPF_OutParm | CPF_ReturnParm ]
};

// Function BTData.BTNetGameData.LoadQuestParams
// Flags: [ FUNC_Native ]
struct UBTNetGameData_execLoadQuestParams_Parms
{
	unsigned long                                      ReturnValue:1;                                    		// 0x0000 ( 0x0004 [0x00000001][ CPF_Parm | CPF_OutParm | CPF_ReturnParm ]
};

// Function BTData.BTNetGameData.LoadPaintGroupParams
// Flags: [ FUNC_Native ]
struct UBTNetGameData_execLoadPaintGroupParams_Parms
{
	unsigned long                                      ReturnValue:1;                                    		// 0x0000 ( 0x0004 [0x00000001][ CPF_Parm | CPF_OutParm | CPF_ReturnParm ]
};

// Function BTData.BTNetGameData.LoadPromotionParams
// Flags: [ FUNC_Native ]
struct UBTNetGameData_execLoadPromotionParams_Parms
{
	unsigned long                                      ReturnValue:1;                                    		// 0x0000 ( 0x0004 [0x00000001][ CPF_Parm | CPF_OutParm | CPF_ReturnParm ]
};

// Function BTData.BTNetGameData.LoadAddPartsGroupParams
// Flags: [ FUNC_Native ]
struct UBTNetGameData_execLoadAddPartsGroupParams_Parms
{
	unsigned long                                      ReturnValue:1;                                    		// 0x0000 ( 0x0004 [0x00000001][ CPF_Parm | CPF_OutParm | CPF_ReturnParm ]
};

// Function BTData.BTNetGameData.LoadSkillParams
// Flags: [ FUNC_Native ]
struct UBTNetGameData_execLoadSkillParams_Parms
{
	unsigned long                                      ReturnValue:1;                                    		// 0x0000 ( 0x0004 [0x00000001][ CPF_Parm | CPF_OutParm | CPF_ReturnParm ]
};

// Function BTData.BTNetGameData.LoadItemResourceParams
// Flags: [ FUNC_Native ]
struct UBTNetGameData_execLoadItemResourceParams_Parms
{
	unsigned long                                      ReturnValue:1;                                    		// 0x0000 ( 0x0004 [0x00000001][ CPF_Parm | CPF_OutParm | CPF_ReturnParm ]
};

// Function BTData.BTNetGameData.LoadItemParams
// Flags: [ FUNC_Native ]
struct UBTNetGameData_execLoadItemParams_Parms
{
	unsigned long                                      ReturnValue:1;                                    		// 0x0000 ( 0x0004 [0x00000001][ CPF_Parm | CPF_OutParm | CPF_ReturnParm ]
};

// Function BTData.BTNetGameData.LoadWeaponRecoilParams
// Flags: [ FUNC_Native ]
struct UBTNetGameData_execLoadWeaponRecoilParams_Parms
{
	unsigned long                                      ReturnValue:1;                                    		// 0x0000 ( 0x0004 [0x00000001][ CPF_Parm | CPF_OutParm | CPF_ReturnParm ]
};

// Function BTData.BTNetGameData.LoadWeaponParams
// Flags: [ FUNC_Native ]
struct UBTNetGameData_execLoadWeaponParams_Parms
{
	unsigned long                                      ReturnValue:1;                                    		// 0x0000 ( 0x0004 [0x00000001][ CPF_Parm | CPF_OutParm | CPF_ReturnParm ]
};

// Function BTData.BTNetGameData.LoadWeaponRes
// Flags: [ FUNC_Native ]
struct UBTNetGameData_execLoadWeaponRes_Parms
{
	unsigned long                                      ReturnValue:1;                                    		// 0x0000 ( 0x0004 [0x00000001][ CPF_Parm | CPF_OutParm | CPF_ReturnParm ]
};

// Function BTData.BTNetGameData.getData
// Flags: [ FUNC_Native ]
struct UBTNetGameData_execgetData_Parms
{
	struct FString                                     category;                                         		// 0x0000 ( 0x000C[ CPF_Parm | CPF_NeedCtorLink ]
	struct FString                                     key;                                              		// 0x000C ( 0x000C[ CPF_Parm | CPF_NeedCtorLink ]
	int                                                iIndex;                                           		// 0x0018 ( 0x0004[ CPF_Parm ]
	struct FString                                     ReturnValue;                                      		// 0x001C ( 0x000C[ CPF_Parm | CPF_OutParm | CPF_ReturnParm | CPF_NeedCtorLink ]
};

// Function BTData.BTNetGameData.LoadAllData
// Flags: [ FUNC_Native ]
struct UBTNetGameData_execLoadAllData_Parms
{
	unsigned long                                      ReturnValue:1;                                    		// 0x0000 ( 0x0004 [0x00000001][ CPF_Parm | CPF_OutParm | CPF_ReturnParm ]
};

// Function BTData.BTNetGameData.LoadAddPaintGroupParams
// Flags: [ FUNC_Native ]
struct UBTNetGameData_execLoadAddPaintGroupParams_Parms
{
	unsigned long                                      ReturnValue:1;                                    		// 0x0000 ( 0x0004 [0x00000001][ CPF_Parm | CPF_OutParm | CPF_ReturnParm ]
};

// Function BTData.BTNetExcelData.getData
// Flags: [ FUNC_Native ]
struct UBTNetExcelData_execgetData_Parms
{
	struct FString                                     category;                                         		// 0x0000 ( 0x000C[ CPF_Parm | CPF_NeedCtorLink ]
	struct FString                                     key;                                              		// 0x000C ( 0x000C[ CPF_Parm | CPF_NeedCtorLink ]
	int                                                iIndex;                                           		// 0x0018 ( 0x0004[ CPF_Parm ]
	struct FString                                     ReturnValue;                                      		// 0x001C ( 0x000C[ CPF_Parm | CPF_OutParm | CPF_ReturnParm | CPF_NeedCtorLink ]
};

// Function BTData.BTNetExcelData.LoadExcelData
// Flags: [ FUNC_Native ]
struct UBTNetExcelData_execLoadExcelData_Parms
{
	struct FString                                     fileName;                                         		// 0x0000 ( 0x000C[ CPF_Parm | CPF_NeedCtorLink ]
	struct FString                                     sheetName;                                        		// 0x000C ( 0x000C[ CPF_Parm | CPF_NeedCtorLink ]
	int                                                numHeadRows;                                      		// 0x0018 ( 0x0004[ CPF_Parm ]
	int                                                numHeadColumns;                                   		// 0x001C ( 0x0004[ CPF_Parm ]
	int                                                nKeyColumnOrRow;                                  		// 0x0020 ( 0x0004[ CPF_Parm ]
	int                                                arrangeType;                                      		// 0x0024 ( 0x0004[ CPF_OptionalParm | CPF_Parm ]
	unsigned long                                      ReturnValue:1;                                    		// 0x0028 ( 0x0004 [0x00000001][ CPF_Parm | CPF_OutParm | CPF_ReturnParm ]
};

#ifdef _MSC_VER
#pragma pack ( pop )
#endif

