#pragma once
/*
# ======================================================================================== #
# > ArcticCombat SDK
# > Generated By HJSdkGen v1.06b
# ---------------------------------------------------------------------------------------- #
# > Package : ALAudio
# >    File : Classes.h
# ======================================================================================== #
*/

#ifdef _MSC_VER
#pragma pack ( push, 4 )
#endif


/*
# ======================================================================================== #
# > Classes
# ======================================================================================== #
*/

// Class ALAudio.FModAudioSubsystem
class DLL_IMPORT UFModAudioSubsystem : public UAudioSubsystem
{
public:
	unsigned char                                      _0x00A0[ 0x5C ];                                  		// 0x00A0 ( 0x005C )
	unsigned long                                      UseEAX:1;                                         		// 0x00FC ( 0x0004 )  [0x00000001][ CPF_Edit ]

	// Public Imports
	UFModAudioSubsystem(class UFModAudioSubsystem const &);
	UFModAudioSubsystem(void);
	class UFModAudioSubsystem &  operator=(class UFModAudioSubsystem const &);
	void  InitBaseInfo(void);
	static void  InternalConstructor(void *);
	void  SetReverbEffect(void);
	void  Shutdown(void);
	static class UClass *  StaticClass(void);
	void  StaticConstructor(void);
	class FModSound *  loadEventData(class FSoundSource *);
	class FModSound *  loadSoundData(class USound *);

	// Private Imports
private:
	static class UClass PrivateStaticClass;
}; // Size: 0x0060

// Class ALAudio.ALAudioSubsystem
class DLL_IMPORT UALAudioSubsystem : public UAudioSubsystem
{
public:
	unsigned char                                      _0x00A0[ 0x6C ];                                  		// 0x00A0 ( 0x006C )
	unsigned long                                      UseEAX:1;                                         		// 0x010C ( 0x0004 )  [0x00000001][ CPF_Edit ]
	unsigned char                                      _0x0110[ 0x24 ];                                  		// 0x0110 ( 0x0024 )

	// Public Imports
	UALAudioSubsystem(class UALAudioSubsystem const &);
	UALAudioSubsystem(void);
	class UALAudioSubsystem &  operator=(class UALAudioSubsystem const &);
	int  FindExt(unsigned short const *,int);
	void  FindProc(void * &,char *,char *,int &,int,int);
	void  FindProcs(int);
	void  InitBaseInfo(void);
	static void  InternalConstructor(void *);
	int  IsSupportsEFX(void);
	static int SUPPORTS_AL;
	static int SUPPORTS_ALC;
	static int SUPPORTS_ALC_EXT_capture;
	int  SetEFXEffect(void);
	void  Shutdown(void);
	static class UClass *  StaticClass(void);
	void  StaticConstructor(void);
	static void (__cdecl* alAuxiliaryEffectSlotf)(unsigned int,int,float);
	static void (__cdecl* alAuxiliaryEffectSlotfv)(unsigned int,int,float *);
	static void (__cdecl* alAuxiliaryEffectSloti)(unsigned int,int,int);
	static void (__cdecl* alAuxiliaryEffectSlotiv)(unsigned int,int,int *);
	static void (__cdecl* alBuffer3f)(unsigned int,int,float,float,float);
	static void (__cdecl* alBuffer3i)(unsigned int,int,int,int,int);
	static void (__cdecl* alBufferData)(unsigned int,int,void *,int,int);
	static void (__cdecl* alBufferf)(unsigned int,int,float);
	static void (__cdecl* alBufferfv)(unsigned int,int,float const *);
	static void (__cdecl* alBufferi)(unsigned int,int,int);
	static void (__cdecl* alBufferiv)(unsigned int,int,int const *);
	static void (__cdecl* alDeleteAuxiliaryEffectSlots)(int,unsigned int *);
	static void (__cdecl* alDeleteBuffers)(int,unsigned int *);
	static void (__cdecl* alDeleteEffects)(int,unsigned int *);
	static void (__cdecl* alDeleteFilters)(int,unsigned int *);
	static void (__cdecl* alDeleteSources)(int,unsigned int *);
	static void (__cdecl* alDisable)(int);
	static void (__cdecl* alDistanceModel)(int);
	static void (__cdecl* alDopplerFactor)(float);
	static void (__cdecl* alDopplerVelocity)(float);
	static int (__cdecl* alEAXGet)(struct _GUID const *,unsigned int,unsigned int,void *,unsigned int);
	static int (__cdecl* alEAXSet)(struct _GUID const *,unsigned int,unsigned int,void *,unsigned int);
	static void (__cdecl* alEffectf)(unsigned int,int,float);
	static void (__cdecl* alEffectfv)(unsigned int,int,float *);
	static void (__cdecl* alEffecti)(unsigned int,int,int);
	static void (__cdecl* alEffectiv)(unsigned int,int,int *);
	static void (__cdecl* alEnable)(int);
	static int  alError(unsigned short *,int);
	static void (__cdecl* alFilterf)(unsigned int,int,float);
	static void (__cdecl* alFilterfv)(unsigned int,int,float *);
	static void (__cdecl* alFilteri)(unsigned int,int,int);
	static void (__cdecl* alFilteriv)(unsigned int,int,int *);
	static void (__cdecl* alGenAuxiliaryEffectSlots)(int,unsigned int *);
	static void (__cdecl* alGenBuffers)(int,unsigned int *);
	static void (__cdecl* alGenEffects)(int,unsigned int *);
	static void (__cdecl* alGenFilters)(int,unsigned int *);
	static void (__cdecl* alGenSources)(int,unsigned int *);
	static void (__cdecl* alGetAuxiliaryEffectSlotf)(unsigned int,int,float *);
	static void (__cdecl* alGetAuxiliaryEffectSlotfv)(unsigned int,int,float *);
	static void (__cdecl* alGetAuxiliaryEffectSloti)(unsigned int,int,int *);
	static void (__cdecl* alGetAuxiliaryEffectSlotiv)(unsigned int,int,int *);
	static char (__cdecl* alGetBoolean)(int);
	static void (__cdecl* alGetBooleanv)(int,char *);
	static void (__cdecl* alGetBuffer3f)(unsigned int,int,float *,float *,float *);
	static void (__cdecl* alGetBuffer3i)(unsigned int,int,int *,int *,int *);
	static void (__cdecl* alGetBufferf)(unsigned int,int,float *);
	static void (__cdecl* alGetBufferfv)(unsigned int,int,float *);
	static void (__cdecl* alGetBufferi)(unsigned int,int,int *);
	static void (__cdecl* alGetBufferiv)(unsigned int,int,int *);
	static double (__cdecl* alGetDouble)(int);
	static void (__cdecl* alGetDoublev)(int,double *);
	static void (__cdecl* alGetEffectf)(unsigned int,int,float *);
	static void (__cdecl* alGetEffectfv)(unsigned int,int,float *);
	static void (__cdecl* alGetEffecti)(unsigned int,int,int *);
	static void (__cdecl* alGetEffectiv)(unsigned int,int,int *);
	static int (__cdecl* alGetEnumValue)(char const *);
	static int (__cdecl* alGetError)(void);
	static void (__cdecl* alGetFilterf)(unsigned int,int,float *);
	static void (__cdecl* alGetFilterfv)(unsigned int,int,float *);
	static void (__cdecl* alGetFilteri)(unsigned int,int,int *);
	static void (__cdecl* alGetFilteriv)(unsigned int,int,int *);
	static float (__cdecl* alGetFloat)(int);
	static void (__cdecl* alGetFloatv)(int,float *);
	static int (__cdecl* alGetInteger)(int);
	static void (__cdecl* alGetIntegerv)(int,int *);
	static void (__cdecl* alGetListener3f)(int,float *,float *,float *);
	static void (__cdecl* alGetListenerf)(int,float *);
	static void (__cdecl* alGetListenerfv)(int,float *);
	static void (__cdecl* alGetListeneri)(int,int *);
	static void * (__cdecl* alGetProcAddress)(char const *);
	static void (__cdecl* alGetSource3f)(unsigned int,int,float *,float *,float *);
	static void (__cdecl* alGetSource3i)(unsigned int,int,int *,int *,int *);
	static void (__cdecl* alGetSourcef)(unsigned int,int,float *);
	static void (__cdecl* alGetSourcefv)(unsigned int,int,float *);
	static void (__cdecl* alGetSourcei)(unsigned int,int,int *);
	static void (__cdecl* alGetSourceiv)(unsigned int,int,int *);
	static unsigned char * (__cdecl* alGetString)(int);
	static char (__cdecl* alIsAuxiliaryEffectSlot)(unsigned int);
	static char (__cdecl* alIsBuffer)(unsigned int);
	static char (__cdecl* alIsEffect)(unsigned int);
	static char (__cdecl* alIsEnabled)(int);
	static char (__cdecl* alIsExtensionPresent)(char const *);
	static char (__cdecl* alIsFilter)(unsigned int);
	static char (__cdecl* alIsSource)(unsigned int);
	static void (__cdecl* alListener3f)(int,float,float,float);
	static void (__cdecl* alListenerf)(int,float);
	static void (__cdecl* alListenerfv)(int,float *);
	static void (__cdecl* alListeneri)(int,int);
	static void (__cdecl* alSource3f)(unsigned int,int,float,float,float);
	static void (__cdecl* alSource3i)(unsigned int,int,int,int,int);
	static void (__cdecl* alSourcePause)(unsigned int);
	static void (__cdecl* alSourcePausev)(int,unsigned int *);
	static void (__cdecl* alSourcePlay)(unsigned int);
	static void (__cdecl* alSourcePlayv)(int,unsigned int *);
	static void (__cdecl* alSourceQueueBuffers)(unsigned int,int,unsigned int *);
	static void (__cdecl* alSourceRewind)(unsigned int);
	static void (__cdecl* alSourceRewindv)(int,unsigned int *);
	static void (__cdecl* alSourceStop)(unsigned int);
	static void (__cdecl* alSourceStopv)(int,unsigned int *);
	static void (__cdecl* alSourceUnqueueBuffers)(unsigned int,int,unsigned int *);
	static void (__cdecl* alSourcef)(unsigned int,int,float);
	static void (__cdecl* alSourcefv)(unsigned int,int,float *);
	static void (__cdecl* alSourcei)(unsigned int,int,int);
	static void (__cdecl* alSourceiv)(unsigned int,int,int const *);
	static void (__cdecl* alSpeedOfSound)(float);
	static void (__cdecl* alcCaptureCloseDevice)(struct ALCdevice_struct *);
	static struct ALCdevice_struct * (__cdecl* alcCaptureOpenDevice)(unsigned char const *,unsigned int,int,int);
	static void (__cdecl* alcCaptureSamples)(struct ALCdevice_struct *,void *,int);
	static void (__cdecl* alcCaptureStart)(struct ALCdevice_struct *);
	static void (__cdecl* alcCaptureStop)(struct ALCdevice_struct *);
	static void (__cdecl* alcCloseDevice)(struct ALCdevice_struct *);
	static struct ALCcontext_struct * (__cdecl* alcCreateContext)(struct ALCdevice_struct *,int *);
	static void (__cdecl* alcDestroyContext)(struct ALCcontext_struct *);
	static struct ALCdevice_struct * (__cdecl* alcGetContextsDevice)(struct ALCcontext_struct *);
	static struct ALCcontext_struct * (__cdecl* alcGetCurrentContext)(void);
	static int (__cdecl* alcGetEnumValue)(struct ALCdevice_struct *,char const *);
	static int (__cdecl* alcGetError)(struct ALCdevice_struct *);
	static void (__cdecl* alcGetIntegerv)(struct ALCdevice_struct *,int,int,int *);
	static void * (__cdecl* alcGetProcAddress)(struct ALCdevice_struct *,char const *);
	static unsigned char * (__cdecl* alcGetString)(struct ALCdevice_struct *,int);
	static char (__cdecl* alcIsExtensionPresent)(struct ALCdevice_struct *,char const *);
	static char (__cdecl* alcMakeContextCurrent)(struct ALCcontext_struct *);
	static struct ALCdevice_struct * (__cdecl* alcOpenDevice)(unsigned char *);
	static void (__cdecl* alcProcessContext)(struct ALCcontext_struct *);
	static void (__cdecl* alcSuspendContext)(struct ALCcontext_struct *);

	// Private Imports
private:
	static class UClass PrivateStaticClass;
}; // Size: 0x0094

#ifdef _MSC_VER
#pragma pack ( pop )
#endif

