#pragma once
/*
# ======================================================================================== #
# > ArcticCombat SDK
# > Generated By HJSdkGen v1.06b
# ---------------------------------------------------------------------------------------- #
# > Package : GUIWarfareStyles
# >    File : Classes.h
# ======================================================================================== #
*/

#ifdef _MSC_VER
#pragma pack ( push, 4 )
#endif


/*
# ======================================================================================== #
# > Classes
# ======================================================================================== #
*/

// Class GUIWarfareStyles.STY2WarfareListBox
class DLL_IMPORT USTY2WarfareListBox : public UGUI2Styles
{
public:
}; // Size: 0x0000

// Class GUIWarfareStyles.STY2WarfareEmpty
class DLL_IMPORT USTY2WarfareEmpty : public UGUI2Styles
{
public:
}; // Size: 0x0000

// Class GUIWarfareStyles.STY2Warfare_ComboButton
class DLL_IMPORT USTY2Warfare_ComboButton : public UGUI2Styles
{
public:
}; // Size: 0x0000

// Class GUIWarfareStyles.STY2Warfare_ComboListBox
class DLL_IMPORT USTY2Warfare_ComboListBox : public UGUI2Styles
{
public:
}; // Size: 0x0000

// Class GUIWarfareStyles.STY2Warfare_ListSection
class DLL_IMPORT USTY2Warfare_ListSection : public UGUI2Styles
{
public:
}; // Size: 0x0000

// Class GUIWarfareStyles.STY2WarfareHK_ServerSelection_ChannelButton
class DLL_IMPORT USTY2WarfareHK_ServerSelection_ChannelButton : public UGUI2Styles
{
public:
}; // Size: 0x0000

// Class GUIWarfareStyles.STY2WarfareHK_Empty
class DLL_IMPORT USTY2WarfareHK_Empty : public UGUI2Styles
{
public:
}; // Size: 0x0000

#ifdef _MSC_VER
#pragma pack ( pop )
#endif

