#pragma once
/*
# ======================================================================================== #
# > ArcticCombat SDK
# > Generated By HJSdkGen v1.06b
# ---------------------------------------------------------------------------------------- #
# > Package : GUI2K4
# >    File : GUI2K4\GUI2K4.h
# ======================================================================================== #
*/


/*
# ======================================================================================== #
# > Forward Declarations
# ======================================================================================== #
*/

class UUT2K4GUIController;
class UPopupPageBase;
class UFloatingWindow;
class UfntUT2k4Menu;
class UfntUT2k4Default;
class UfntUT2k4Large;
class UfntUT2k4Header;
class UfntUT2k4Small;
class UfntUT2k4MidGame;
class UfntUT2k4SmallHeader;
class UfntUT2k4ServerList;
class UfntUT2k4IRC;
class UfntUT2k4MainMenu;
class UfntUT2K4Medium;
class UGUI2Styles;
class USTY2RoundButton;
class USTY2RoundScaledButton;
class USTY2SquareButton;
class USTY2ListBox;
class USTY2ScrollZone;
class USTY2TextButton;
class USTY2Page;
class USTY2Footer;
class USTY2Header;
class USTY2TabButton;
class USTY2CharButton;
class USTY2ArrowLeft;
class USTY2ArrowRight;
class USTY2ServerBrowserGrid;
class USTY2NoBackground;
class USTY2ServerBrowserGridHeader;
class USTY2SliderCaption;
class USTY2LadderButton;
class USTY2LadderButtonHi;
class USTY2LadderButtonActive;
class USTY2BindBox;
class USTY2SquareBar;
class USTY2SquareMenuButton;
class USTY2MidGameButton;
class USTY2TextLabel;
class USTY2ComboListBox;
class USTY2IRCText;
class USTY2IRCEntry;
class USTY2BrowserButton;
class USTY2ContextMenu;
class USTY2ServerListContextMenu;
class USTY2ListSelection;
class USTY2TabBackground;
class USTY2BrowserListSel;
class USTY2EditBox;
class USTY2CheckBox;
class USTY2CheckBoxCheck;
class USTY2SliderKnob;
class USTY2BottomTabButton;
class USTY2ListSectionHeader;
class USTY2ItemOutline;
class USTY2ListHighlight;
class USTY2MouseOverLabel;
class USTY2SliderBar;
class USTY2DarkTextLabel;
class USTY2TextButtonEffect;
class USTY2ArrowRightDbl;
class USTY2ArrowLeftDbl;
class USTY2FooterButton;
class USTY2SectionHeaderText;
class USTY2ComboButton;
class USTY2VertUpButton;
class USTY2VertDownButton;
class USTY2VertGrip;
class USTY2Spinner;
class USTY2SectionHeaderTop;
class USTY2SectionHeaderBar;
class USTY2CloseButton;
class USTY2CoolScroll;
class USTY2AltComboButton;
class UUT2K4InGameChat;
class UAltSectionBackground;

/*
# ======================================================================================== #
# > Includes
# ======================================================================================== #
*/

#include "Structs.h"
#include "ParamStructs.h"
#include "Classes.h"
