#pragma once
/*
# ======================================================================================== #
# > ArcticCombat SDK
# > Generated By HJSdkGen v1.06b
# ---------------------------------------------------------------------------------------- #
# > Package : GUI2K4
# >    File : ParamStructs.h
# ======================================================================================== #
*/

#ifdef _MSC_VER
#pragma pack ( push, 4 )
#endif

// Function GUI2K4.UT2K4GUIController.PurgeComponentClasses
// Flags: 
struct UUT2K4GUIController_execPurgeComponentClasses_Parms
{
};

// Function GUI2K4.UT2K4GUIController.AddComponentClass
// Flags: 
struct UUT2K4GUIController_execAddComponentClass_Parms
{
	struct FString                                     ClassName;                                        		// 0x0000 ( 0x000C[ CPF_Parm | CPF_NeedCtorLink ]
	class UClass*                                      ReturnValue;                                      		// 0x000C ( 0x0004[ CPF_Parm | CPF_OutParm | CPF_ReturnParm ]
//	int                                                i;                                                		// 0x0010 ( 0x0004
//	class UClass*                                      cls;                                              		// 0x0014 ( 0x0004
};

// Function GUI2K4.UT2K4GUIController.GetQuitPage
// Flags: [ FUNC_Simulated ]
struct UUT2K4GUIController_execGetQuitPage_Parms
{
	struct FString                                     ReturnValue;                                      		// 0x0000 ( 0x000C[ CPF_Parm | CPF_OutParm | CPF_ReturnParm | CPF_NeedCtorLink ]
};

// Function GUI2K4.UT2K4GUIController.GetSettingsPage
// Flags: [ FUNC_Simulated ]
struct UUT2K4GUIController_execGetSettingsPage_Parms
{
	struct FString                                     ReturnValue;                                      		// 0x0000 ( 0x000C[ CPF_Parm | CPF_OutParm | CPF_ReturnParm | CPF_NeedCtorLink ]
};

// Function GUI2K4.UT2K4GUIController.GetModPage
// Flags: [ FUNC_Simulated ]
struct UUT2K4GUIController_execGetModPage_Parms
{
	struct FString                                     ReturnValue;                                      		// 0x0000 ( 0x000C[ CPF_Parm | CPF_OutParm | CPF_ReturnParm | CPF_NeedCtorLink ]
};

// Function GUI2K4.UT2K4GUIController.GetInstantActionPage
// Flags: [ FUNC_Simulated ]
struct UUT2K4GUIController_execGetInstantActionPage_Parms
{
	struct FString                                     ReturnValue;                                      		// 0x0000 ( 0x000C[ CPF_Parm | CPF_OutParm | CPF_ReturnParm | CPF_NeedCtorLink ]
};

// Function GUI2K4.UT2K4GUIController.GetMultiplayerPage
// Flags: [ FUNC_Simulated ]
struct UUT2K4GUIController_execGetMultiplayerPage_Parms
{
	struct FString                                     ReturnValue;                                      		// 0x0000 ( 0x000C[ CPF_Parm | CPF_OutParm | CPF_ReturnParm | CPF_NeedCtorLink ]
};

// Function GUI2K4.UT2K4GUIController.GetServerBrowserPage
// Flags: [ FUNC_Simulated ]
struct UUT2K4GUIController_execGetServerBrowserPage_Parms
{
	struct FString                                     ReturnValue;                                      		// 0x0000 ( 0x000C[ CPF_Parm | CPF_OutParm | CPF_ReturnParm | CPF_NeedCtorLink ]
};

// Function GUI2K4.UT2K4GUIController.GetSinglePlayerPage
// Flags: [ FUNC_Simulated ]
struct UUT2K4GUIController_execGetSinglePlayerPage_Parms
{
	struct FString                                     ReturnValue;                                      		// 0x0000 ( 0x000C[ CPF_Parm | CPF_OutParm | CPF_ReturnParm | CPF_NeedCtorLink ]
};

// Function GUI2K4.UT2K4GUIController.Validate
// Flags: [ FUNC_Simulated | FUNC_Event ]
struct UUT2K4GUIController_eventValidate_Parms
{
};

// Function GUI2K4.UT2K4GUIController.OpenMenu
// Flags: [ FUNC_Event ]
struct UUT2K4GUIController_eventOpenMenu_Parms
{
	struct FString                                     NewMenuName;                                      		// 0x0000 ( 0x000C[ CPF_Parm | CPF_NeedCtorLink ]
	struct FString                                     Param1;                                           		// 0x000C ( 0x000C[ CPF_OptionalParm | CPF_Parm | CPF_NeedCtorLink ]
	struct FString                                     Param2;                                           		// 0x0018 ( 0x000C[ CPF_OptionalParm | CPF_Parm | CPF_NeedCtorLink ]
	unsigned long                                      ReturnValue:1;                                    		// 0x0024 ( 0x0004 [0x00000001][ CPF_Parm | CPF_OutParm | CPF_ReturnParm ]
};

// Function GUI2K4.UT2K4GUIController.SetFocusTo
// Flags: 
struct UUT2K4GUIController_execSetFocusTo_Parms
{
	class UFloatingWindow*                             Menu;                                             		// 0x0000 ( 0x0004[ CPF_ExportObject | CPF_Parm | CPF_NeedCtorLink | CPF_EditInline ]
	unsigned long                                      ReturnValue:1;                                    		// 0x0004 ( 0x0004 [0x00000001][ CPF_Parm | CPF_OutParm | CPF_ReturnParm ]
//	int                                                i;                                                		// 0x0008 ( 0x0004
};

// Function GUI2K4.UT2K4GUIController.ReturnToMainMenu
// Flags: 
struct UUT2K4GUIController_execReturnToMainMenu_Parms
{
};

// Function GUI2K4.FloatingWindow.SetMouseCursorIndex
// Flags: 
struct UFloatingWindow_execSetMouseCursorIndex_Parms
{
	int                                                NewIndex;                                         		// 0x0000 ( 0x0004[ CPF_Parm ]
};

// Function GUI2K4.FloatingWindow.XButtonClicked
// Flags: 
struct UFloatingWindow_execXButtonClicked_Parms
{
	class UGUIComponent*                               Sender;                                           		// 0x0000 ( 0x0004[ CPF_ExportObject | CPF_Parm | CPF_NeedCtorLink | CPF_EditInline ]
	unsigned long                                      ReturnValue:1;                                    		// 0x0004 ( 0x0004 [0x00000001][ CPF_Parm | CPF_OutParm | CPF_ReturnParm ]
};

// Function GUI2K4.FloatingWindow.HoveringBottomLeft
// Flags: 
struct UFloatingWindow_execHoveringBottomLeft_Parms
{
	unsigned long                                      ReturnValue:1;                                    		// 0x0000 ( 0x0004 [0x00000001][ CPF_Parm | CPF_OutParm | CPF_ReturnParm ]
};

// Function GUI2K4.FloatingWindow.HoveringTopLeft
// Flags: 
struct UFloatingWindow_execHoveringTopLeft_Parms
{
	unsigned long                                      ReturnValue:1;                                    		// 0x0000 ( 0x0004 [0x00000001][ CPF_Parm | CPF_OutParm | CPF_ReturnParm ]
};

// Function GUI2K4.FloatingWindow.HoveringBottomBorder
// Flags: 
struct UFloatingWindow_execHoveringBottomBorder_Parms
{
	unsigned long                                      ReturnValue:1;                                    		// 0x0000 ( 0x0004 [0x00000001][ CPF_Parm | CPF_OutParm | CPF_ReturnParm ]
};

// Function GUI2K4.FloatingWindow.HoveringTopBorder
// Flags: 
struct UFloatingWindow_execHoveringTopBorder_Parms
{
	unsigned long                                      ReturnValue:1;                                    		// 0x0000 ( 0x0004 [0x00000001][ CPF_Parm | CPF_OutParm | CPF_ReturnParm ]
};

// Function GUI2K4.FloatingWindow.HoveringRightBorder
// Flags: 
struct UFloatingWindow_execHoveringRightBorder_Parms
{
	unsigned long                                      ReturnValue:1;                                    		// 0x0000 ( 0x0004 [0x00000001][ CPF_Parm | CPF_OutParm | CPF_ReturnParm ]
};

// Function GUI2K4.FloatingWindow.HoveringLeftBorder
// Flags: 
struct UFloatingWindow_execHoveringLeftBorder_Parms
{
	unsigned long                                      ReturnValue:1;                                    		// 0x0000 ( 0x0004 [0x00000001][ CPF_Parm | CPF_OutParm | CPF_ReturnParm ]
};

// Function GUI2K4.FloatingWindow.ResizeAllowed
// Flags: 
struct UFloatingWindow_execResizeAllowed_Parms
{
	unsigned long                                      ReturnValue:1;                                    		// 0x0000 ( 0x0004 [0x00000001][ CPF_Parm | CPF_OutParm | CPF_ReturnParm ]
};

// Function GUI2K4.FloatingWindow.ResizedHeight
// Flags: 
struct UFloatingWindow_execResizedHeight_Parms
{
};

// Function GUI2K4.FloatingWindow.ResizedWidth
// Flags: 
struct UFloatingWindow_execResizedWidth_Parms
{
};

// Function GUI2K4.FloatingWindow.ResizedBoth
// Flags: 
struct UFloatingWindow_execResizedBoth_Parms
{
};

// Function GUI2K4.FloatingWindow.ResolutionChanged
// Flags: [ FUNC_Event ]
struct UFloatingWindow_eventResolutionChanged_Parms
{
	int                                                ResX;                                             		// 0x0000 ( 0x0004[ CPF_Parm ]
	int                                                ResY;                                             		// 0x0004 ( 0x0004[ CPF_Parm ]
};

// Function GUI2K4.FloatingWindow.FloatingRendered
// Flags: 
struct UFloatingWindow_execFloatingRendered_Parms
{
	class UCanvas*                                     C;                                                		// 0x0000 ( 0x0004[ CPF_Parm ]
};

// Function GUI2K4.FloatingWindow.FloatingPreDraw
// Flags: 
struct UFloatingWindow_execFloatingPreDraw_Parms
{
	class UCanvas*                                     C;                                                		// 0x0000 ( 0x0004[ CPF_Parm ]
	unsigned long                                      ReturnValue:1;                                    		// 0x0004 ( 0x0004 [0x00000001][ CPF_Parm | CPF_OutParm | CPF_ReturnParm ]
//	float                                              OldW;                                             		// 0x0008 ( 0x0004
//	float                                              OldH;                                             		// 0x000C ( 0x0004
//	float                                              DiffX;                                            		// 0x0010 ( 0x0004
//	float                                              DiffY;                                            		// 0x0014 ( 0x0004
//	float                                              AW;                                               		// 0x0018 ( 0x0004
//	float                                              AT;                                               		// 0x001C ( 0x0004
//	float                                              AH;                                               		// 0x0020 ( 0x0004
//	float                                              AL;                                               		// 0x0024 ( 0x0004
};

// Function GUI2K4.FloatingWindow.SetPanelPosition
// Flags: 
struct UFloatingWindow_execSetPanelPosition_Parms
{
	class UCanvas*                                     C;                                                		// 0x0000 ( 0x0004[ CPF_Parm ]
};

// Function GUI2K4.FloatingWindow.FloatingHover
// Flags: 
struct UFloatingWindow_execFloatingHover_Parms
{
	class UGUIComponent*                               Sender;                                           		// 0x0000 ( 0x0004[ CPF_ExportObject | CPF_Parm | CPF_NeedCtorLink | CPF_EditInline ]
	unsigned long                                      ReturnValue:1;                                    		// 0x0004 ( 0x0004 [0x00000001][ CPF_Parm | CPF_OutParm | CPF_ReturnParm ]
};

// Function GUI2K4.FloatingWindow.SaveCurrentPosition
// Flags: 
struct UFloatingWindow_execSaveCurrentPosition_Parms
{
};

// Function GUI2K4.FloatingWindow.FloatingMouseRelease
// Flags: 
struct UFloatingWindow_execFloatingMouseRelease_Parms
{
	class UGUIComponent*                               Sender;                                           		// 0x0000 ( 0x0004[ CPF_ExportObject | CPF_Parm | CPF_NeedCtorLink | CPF_EditInline ]
	unsigned long                                      bSave:1;                                          		// 0x0004 ( 0x0004 [0x00000001]
};

// Function GUI2K4.FloatingWindow.FloatingMousePressed
// Flags: 
struct UFloatingWindow_execFloatingMousePressed_Parms
{
	class UGUIComponent*                               Sender;                                           		// 0x0000 ( 0x0004[ CPF_ExportObject | CPF_Parm | CPF_NeedCtorLink | CPF_EditInline ]
	unsigned long                                      bRepeat:1;                                        		// 0x0004 ( 0x0004 [0x00000001][ CPF_Parm ]
};

// Function GUI2K4.FloatingWindow.SetFocus
// Flags: [ FUNC_Event ]
struct UFloatingWindow_eventSetFocus_Parms
{
	class UGUIComponent*                               Who;                                              		// 0x0000 ( 0x0004[ CPF_ExportObject | CPF_Parm | CPF_NeedCtorLink | CPF_EditInline ]
};

// Function GUI2K4.FloatingWindow.InternalOnCreateComponent
// Flags: 
struct UFloatingWindow_execInternalOnCreateComponent_Parms
{
	class UGUIComponent*                               NewComp;                                          		// 0x0000 ( 0x0004[ CPF_ExportObject | CPF_Parm | CPF_NeedCtorLink | CPF_EditInline ]
	class UGUIComponent*                               Sender;                                           		// 0x0004 ( 0x0004[ CPF_ExportObject | CPF_Parm | CPF_NeedCtorLink | CPF_EditInline ]
};

// Function GUI2K4.FloatingWindow.SetDefaultPosition
// Flags: 
struct UFloatingWindow_execSetDefaultPosition_Parms
{
	float                                              rH;                                               		// 0x0000 ( 0x0004
	float                                              rW;                                               		// 0x0004 ( 0x0004
};

// Function GUI2K4.FloatingWindow.CheckBounds
// Flags: 
struct UFloatingWindow_execCheckBounds_Parms
{
	float                                              AH;                                               		// 0x0000 ( 0x0004
	float                                              AW;                                               		// 0x0004 ( 0x0004
	float                                              AL;                                               		// 0x0008 ( 0x0004
	float                                              AT;                                               		// 0x000C ( 0x0004
};

// Function GUI2K4.FloatingWindow.SystemMenuPreDraw
// Flags: 
struct UFloatingWindow_execSystemMenuPreDraw_Parms
{
	class UCanvas*                                     Canvas;                                           		// 0x0000 ( 0x0004[ CPF_Parm ]
	unsigned long                                      ReturnValue:1;                                    		// 0x0004 ( 0x0004 [0x00000001][ CPF_Parm | CPF_OutParm | CPF_ReturnParm ]
};

// Function GUI2K4.FloatingWindow.AddSystemMenu
// Flags: 
struct UFloatingWindow_execAddSystemMenu_Parms
{
	unsigned char                                      tFontScale;                                       		// 0x0000 ( 0x0001
};

// Function GUI2K4.FloatingWindow.AlignFrame
// Flags: 
struct UFloatingWindow_execAlignFrame_Parms
{
	class UCanvas*                                     C;                                                		// 0x0000 ( 0x0004[ CPF_Parm ]
	unsigned long                                      ReturnValue:1;                                    		// 0x0004 ( 0x0004 [0x00000001][ CPF_Parm | CPF_OutParm | CPF_ReturnParm ]
//	float                                              temp;                                             		// 0x0008 ( 0x0004
};

// Function GUI2K4.FloatingWindow.InitComponent
// Flags: 
struct UFloatingWindow_execInitComponent_Parms
{
	class UGUIController*                              MyController;                                     		// 0x0000 ( 0x0004[ CPF_Parm ]
	class UGUIComponent*                               myOwner;                                          		// 0x0004 ( 0x0004[ CPF_ExportObject | CPF_Parm | CPF_NeedCtorLink | CPF_EditInline ]
};

// Function GUI2K4.PopupPageBase.Default_FadedOut
// Flags: 
struct UPopupPageBase_execDefault_FadedOut_Parms
{
};

// Function GUI2K4.PopupPageBase.FadeOut
// Flags: 
struct UPopupPageBase_execFadeOut_Parms
{
	unsigned long                                      bTranslate:1;                                     		// 0x0000 ( 0x0004 [0x00000001][ CPF_OptionalParm | CPF_Parm ]
	unsigned long                                      bChangeAlpha:1;                                   		// 0x0004 ( 0x0004 [0x00000001][ CPF_OptionalParm | CPF_Parm ]
};

// Function GUI2K4.PopupPageBase.FadeIn
// Flags: 
struct UPopupPageBase_execFadeIn_Parms
{
	unsigned long                                      bTranslate:1;                                     		// 0x0000 ( 0x0004 [0x00000001][ CPF_OptionalParm | CPF_Parm ]
	unsigned long                                      bChangeAlpha:1;                                   		// 0x0004 ( 0x0004 [0x00000001][ CPF_OptionalParm | CPF_Parm ]
};

// Function GUI2K4.PopupPageBase.InternalOnPreDraw
// Flags: 
struct UPopupPageBase_execInternalOnPreDraw_Parms
{
	class UCanvas*                                     C;                                                		// 0x0000 ( 0x0004[ CPF_Parm ]
	unsigned long                                      ReturnValue:1;                                    		// 0x0004 ( 0x0004 [0x00000001][ CPF_Parm | CPF_OutParm | CPF_ReturnParm ]
//	float                                              fadeDirection;                                    		// 0x0008 ( 0x0004
//	unsigned char                                      fadeByte;                                         		// 0x000C ( 0x0001
//	unsigned long                                      bFadedState:1;                                    		// 0x0010 ( 0x0004 [0x00000001]
};

// Function GUI2K4.PopupPageBase.OnFadeEnd
// Flags: 
struct UPopupPageBase_execOnFadeEnd_Parms
{
};

// Function GUI2K4.PopupPageBase.FindPoupPageBaseInMenuStack
// Flags: 
struct UPopupPageBase_execFindPoupPageBaseInMenuStack_Parms
{
	class UGUIPage*                                    CurrentPage;                                      		// 0x0000 ( 0x0004[ CPF_ExportObject | CPF_Parm | CPF_NeedCtorLink | CPF_EditInline ]
	unsigned long                                      ReturnValue:1;                                    		// 0x0004 ( 0x0004 [0x00000001][ CPF_Parm | CPF_OutParm | CPF_ReturnParm ]
//	int                                                i;                                                		// 0x0008 ( 0x0004
};

// Function GUI2K4.PopupPageBase.Opened
// Flags: [ FUNC_Event ]
struct UPopupPageBase_eventOpened_Parms
{
	class UGUIComponent*                               Sender;                                           		// 0x0000 ( 0x0004[ CPF_ExportObject | CPF_Parm | CPF_NeedCtorLink | CPF_EditInline ]
};

// Function GUI2K4.fntUT2k4MidGame.GetFont
// Flags: [ FUNC_Event ]
struct UfntUT2k4MidGame_eventGetFont_Parms
{
	int                                                XRes;                                             		// 0x0000 ( 0x0004[ CPF_Parm ]
	class UFont*                                       ReturnValue;                                      		// 0x0004 ( 0x0004[ CPF_Parm | CPF_OutParm | CPF_ReturnParm ]
};

// Function GUI2K4.fntUT2k4MidGame.GetMidGameFont
// Flags: 
struct UfntUT2k4MidGame_execGetMidGameFont_Parms
{
	int                                                XRes;                                             		// 0x0000 ( 0x0004[ CPF_Parm ]
	class UFont*                                       ReturnValue;                                      		// 0x0004 ( 0x0004[ CPF_Parm | CPF_OutParm | CPF_ReturnParm ]
//	int                                                i;                                                		// 0x0008 ( 0x0004
};

// Function GUI2K4.UT2K4InGameChat.InternalOnCreateComponent
// Flags: 
struct UUT2K4InGameChat_execInternalOnCreateComponent_Parms
{
	class UGUIComponent*                               NewComp;                                          		// 0x0000 ( 0x0004[ CPF_ExportObject | CPF_Parm | CPF_NeedCtorLink | CPF_EditInline ]
	class UGUIComponent*                               Sender;                                           		// 0x0004 ( 0x0004[ CPF_ExportObject | CPF_Parm | CPF_NeedCtorLink | CPF_EditInline ]
};

// Function GUI2K4.UT2K4InGameChat.InternalOnKeyEvent
// Flags: 
struct UUT2K4InGameChat_execInternalOnKeyEvent_Parms
{
	unsigned char                                      key;                                              		// 0x0000 ( 0x0001[ CPF_Parm | CPF_OutParm ]
	unsigned char                                      State;                                            		// 0x0001 ( 0x0001[ CPF_Parm | CPF_OutParm ]
	float                                              Delta;                                            		// 0x0004 ( 0x0004[ CPF_Parm ]
	unsigned long                                      ReturnValue:1;                                    		// 0x0008 ( 0x0004 [0x00000001][ CPF_Parm | CPF_OutParm | CPF_ReturnParm ]
//	struct FString                                     Cmd;                                              		// 0x000C ( 0x000C[ CPF_NeedCtorLink ]
//	int                                                i;                                                		// 0x0018 ( 0x0004
};

// Function GUI2K4.UT2K4InGameChat.HandleChat
// Flags: 
struct UUT2K4InGameChat_execHandleChat_Parms
{
	struct FString                                     Msg;                                              		// 0x0000 ( 0x000C[ CPF_Parm | CPF_NeedCtorLink ]
	int                                                TeamIndex;                                        		// 0x000C ( 0x0004[ CPF_Parm ]
	int                                                i;                                                		// 0x0010 ( 0x0004
	struct FString                                     str;                                              		// 0x0014 ( 0x000C[ CPF_NeedCtorLink ]
};

// Function GUI2K4.UT2K4InGameChat.Closed
// Flags: 
struct UUT2K4InGameChat_execClosed_Parms
{
	class UGUIComponent*                               Sender;                                           		// 0x0000 ( 0x0004[ CPF_ExportObject | CPF_Parm | CPF_NeedCtorLink | CPF_EditInline ]
	unsigned long                                      bCancelled:1;                                     		// 0x0004 ( 0x0004 [0x00000001][ CPF_Parm ]
};

// Function GUI2K4.UT2K4InGameChat.Opened
// Flags: [ FUNC_Event ]
struct UUT2K4InGameChat_eventOpened_Parms
{
	class UGUIComponent*                               Sender;                                           		// 0x0000 ( 0x0004[ CPF_ExportObject | CPF_Parm | CPF_NeedCtorLink | CPF_EditInline ]
	int                                                i;                                                		// 0x0004 ( 0x0004
	struct FString                                     KeyName;                                          		// 0x0008 ( 0x000C[ CPF_NeedCtorLink ]
	class TArray< struct FString >                     KeyNames;                                         		// 0x0014 ( 0x000C[ CPF_NeedCtorLink ]
	class APlayerController*                           PC;                                               		// 0x0020 ( 0x0004
};

// Function GUI2K4.UT2K4InGameChat.InitComponent
// Flags: 
struct UUT2K4InGameChat_execInitComponent_Parms
{
	class UGUIController*                              MyController;                                     		// 0x0000 ( 0x0004[ CPF_Parm ]
	class UGUIComponent*                               myOwner;                                          		// 0x0004 ( 0x0004[ CPF_ExportObject | CPF_Parm | CPF_NeedCtorLink | CPF_EditInline ]
	int                                                i;                                                		// 0x0008 ( 0x0004
	class APlayerController*                           PC;                                               		// 0x000C ( 0x0004
	class UExtendedConsole*                            MyConsole;                                        		// 0x0010 ( 0x0004
};

#ifdef _MSC_VER
#pragma pack ( pop )
#endif

