#pragma once
/*
# ======================================================================================== #
# > ArcticCombat SDK
# > Generated By HJSdkGen v1.06b
# ---------------------------------------------------------------------------------------- #
# > Package : XWeapons
# >    File : Classes.h
# ======================================================================================== #
*/

#ifdef _MSC_VER
#pragma pack ( push, 4 )
#endif


/*
# ======================================================================================== #
# > Classes
# ======================================================================================== #
*/

// Class XWeapons.HitEffect
class DLL_IMPORT AHitEffect : public AEffects
{
public:
	class UClass*                                      HitEffectDefault;                                 		// 0x03C8 ( 0x0004 ) [ CPF_Edit ]
	class UClass*                                      HitEffectETC;                                     		// 0x03CC ( 0x0004 ) [ CPF_Edit ]
	class UClass*                                      HitEffectrock;                                    		// 0x03D0 ( 0x0004 ) [ CPF_Edit ]
	class UClass*                                      HitEffectbrick;                                   		// 0x03D4 ( 0x0004 ) [ CPF_Edit ]
	class UClass*                                      HitEffectConcrete;                                		// 0x03D8 ( 0x0004 ) [ CPF_Edit ]
	class UClass*                                      HitEffectDirt;                                    		// 0x03DC ( 0x0004 ) [ CPF_Edit ]
	class UClass*                                      HitEffectMetal;                                   		// 0x03E0 ( 0x0004 ) [ CPF_Edit ]
	class UClass*                                      HitEffectMetal_PT;                                		// 0x03E4 ( 0x0004 ) [ CPF_Edit ]
	class UClass*                                      HitEffectWood;                                    		// 0x03E8 ( 0x0004 ) [ CPF_Edit ]
	class UClass*                                      HitEffectPlant;                                   		// 0x03EC ( 0x0004 ) [ CPF_Edit ]
	class UClass*                                      HitEffectFlesh;                                   		// 0x03F0 ( 0x0004 ) [ CPF_Edit ]
	class UClass*                                      HitEffectIce;                                     		// 0x03F4 ( 0x0004 ) [ CPF_Edit ]
	class UClass*                                      HitEffectSnow;                                    		// 0x03F8 ( 0x0004 ) [ CPF_Edit ]
	class UClass*                                      HitEffectWater;                                   		// 0x03FC ( 0x0004 ) [ CPF_Edit ]
	class UClass*                                      HitEffectGlass;                                   		// 0x0400 ( 0x0004 ) [ CPF_Edit ]
	class UClass*                                      HitEffectcotton;                                  		// 0x0404 ( 0x0004 ) [ CPF_Edit ]
	class UClass*                                      HitEffect_blood_headshot;                         		// 0x0408 ( 0x0004 ) [ CPF_Edit ]
	class UClass*                                      HitEffect_Blood;                                  		// 0x040C ( 0x0004 ) [ CPF_Edit ]
	class UClass*                                      HitEffect_blood_death;                            		// 0x0410 ( 0x0004 ) [ CPF_Edit ]
	class UClass*                                      HitEffect_blood_spurt;                            		// 0x0414 ( 0x0004 ) [ CPF_Edit ]
	class UClass*                                      HitEffectCrackWood;                               		// 0x0418 ( 0x0004 ) [ CPF_Edit ]
	class UClass*                                      HitEffectPlastic;                                 		// 0x041C ( 0x0004 ) [ CPF_Edit ]
	class UClass*                                      HitEffectPaper;                                   		// 0x0420 ( 0x0004 ) [ CPF_Edit ]
	class UClass*                                      HitEffectRubber;                                  		// 0x0424 ( 0x0004 ) [ CPF_Edit ]
	class UClass*                                      HitEffectCarpet;                                  		// 0x0428 ( 0x0004 ) [ CPF_Edit ]
	class UClass*                                      HitEffectLeaves;                                  		// 0x042C ( 0x0004 ) [ CPF_Edit ]
	class UClass*                                      HitEffectCloth;                                   		// 0x0430 ( 0x0004 ) [ CPF_Edit ]
	class UClass*                                      HitEffectSand;                                    		// 0x0434 ( 0x0004 ) [ CPF_Edit ]
	class UClass*                                      HitEffectMud;                                     		// 0x0438 ( 0x0004 ) [ CPF_Edit ]
	class UClass*                                      HitEffectWaterFoot;                               		// 0x043C ( 0x0004 ) [ CPF_Edit ]
	class UClass*                                      HitEffectWaterWall;                               		// 0x0440 ( 0x0004 ) [ CPF_Edit ]
	class UClass*                                      alien_tankersheld_hit;                            		// 0x0444 ( 0x0004 ) [ CPF_Edit ]

	// UScript Functions
	 class UClass*             GetHitEffectByMaterial ( class UMaterial* mVictim );		//  XWeapons.HitEffect.GetHitEffectByMaterial
	 class UClass*             GetHitEffect ( class AActor* Victim, struct FVector HitLocation, struct FVector HitNormal );		//  XWeapons.HitEffect.GetHitEffect
}; // Size: 0x0080

#ifdef _MSC_VER
#pragma pack ( pop )
#endif

