#pragma once
/*
# ======================================================================================== #
# > ArcticCombat SDK
# > Generated By HJSdkGen v1.06b
# ---------------------------------------------------------------------------------------- #
# > Package : XWeapons
# >    File : ParamStructs.h
# ======================================================================================== #
*/

#ifdef _MSC_VER
#pragma pack ( push, 4 )
#endif

// Function XWeapons.HitEffect.GetHitEffectByMaterial
// Flags: 
struct AHitEffect_execGetHitEffectByMaterial_Parms
{
	class UMaterial*                                   mVictim;                                          		// 0x0000 ( 0x0004[ CPF_Parm ]
	class UClass*                                      ReturnValue;                                      		// 0x0004 ( 0x0004[ CPF_Parm | CPF_OutParm | CPF_ReturnParm ]
};

// Function XWeapons.HitEffect.GetHitEffect
// Flags: 
struct AHitEffect_execGetHitEffect_Parms
{
	class AActor*                                      Victim;                                           		// 0x0000 ( 0x0004[ CPF_Parm ]
	struct FVector                                     HitLocation;                                      		// 0x0004 ( 0x000C[ CPF_Parm ]
	struct FVector                                     HitNormal;                                        		// 0x0010 ( 0x000C[ CPF_Parm ]
	class UClass*                                      ReturnValue;                                      		// 0x001C ( 0x0004[ CPF_Parm | CPF_OutParm | CPF_ReturnParm ]
};

#ifdef _MSC_VER
#pragma pack ( pop )
#endif

