#pragma once
/*
# ======================================================================================== #
# > ArcticCombat SDK
# > Generated By HJSdkGen v1.06b
# ---------------------------------------------------------------------------------------- #
# > Package : UnrealGame
# >    File : Structs.h
# ======================================================================================== #
*/

#ifdef _MSC_VER
#pragma pack ( push, 4 )
#endif


/*
# ======================================================================================== #
# > Structs
# ======================================================================================== #
*/

// Struct UnrealGame.DeathMatch.AddBotInfo
struct DLL_IMPORT FAddBotInfo
{
	class UClass*                                      BotClass;                                         		// 0x0000 ( 0x0004
	int                                                Team;                                             		// 0x0004 ( 0x0004
	int                                                Grade;                                            		// 0x0008 ( 0x0004
	int                                                NPCID;                                            		// 0x000C ( 0x0004
	int                                                RegenLoc;                                         		// 0x0010 ( 0x0004
}; // Size: 0x0014

// Struct UnrealGame.GameObjective.ScorerRecord
struct DLL_IMPORT FScorerRecord
{
	class AController*                                 C;                                                		// 0x0000 ( 0x0004
	float                                              Pct;                                              		// 0x0004 ( 0x0004
}; // Size: 0x0008

// Struct UnrealGame.TeamPlayerReplicationInfo.VehicleStats
struct DLL_IMPORT FVehicleStats
{
	class UClass*                                      VehicleClass;                                     		// 0x0000 ( 0x0004
	int                                                Kills;                                            		// 0x0004 ( 0x0004
	int                                                Deaths;                                           		// 0x0008 ( 0x0004
	int                                                DeathsDriving;                                    		// 0x000C ( 0x0004
}; // Size: 0x0010

// Struct UnrealGame.TeamPlayerReplicationInfo.WeaponStats
struct DLL_IMPORT FWeaponStats
{
	class UClass*                                      WeaponClass;                                      		// 0x0000 ( 0x0004
	int                                                Kills;                                            		// 0x0004 ( 0x0004
	int                                                Deaths;                                           		// 0x0008 ( 0x0004
	int                                                deathsholding;                                    		// 0x000C ( 0x0004
}; // Size: 0x0010

// Struct UnrealGame.CustomBotConfig.CustomConfiguration
struct DLL_IMPORT FCustomConfiguration
{
	struct FString                                     CharacterName;                                    		// 0x0000 ( 0x000C[ CPF_Config | CPF_NeedCtorLink ]
	struct FString                                     PlayerName;                                       		// 0x000C ( 0x000C[ CPF_Config | CPF_NeedCtorLink ]
	struct FString                                     CustomVoice;                                      		// 0x0018 ( 0x000C[ CPF_Config | CPF_NeedCtorLink ]
	unsigned char                                      CustomOrders;                                     		// 0x0024 ( 0x0001[ CPF_Config ]
	struct FString                                     FavoriteWeapon;                                   		// 0x0028 ( 0x000C[ CPF_Edit | CPF_Config | CPF_NeedCtorLink ]
	float                                              Aggressiveness;                                   		// 0x0034 ( 0x0004[ CPF_Edit | CPF_Config ]
	float                                              Accuracy;                                         		// 0x0038 ( 0x0004[ CPF_Edit | CPF_Config ]
	float                                              CombatStyle;                                      		// 0x003C ( 0x0004[ CPF_Edit | CPF_Config ]
	float                                              StrafingAbility;                                  		// 0x0040 ( 0x0004[ CPF_Edit | CPF_Config ]
	float                                              Tactics;                                          		// 0x0044 ( 0x0004[ CPF_Edit | CPF_Config ]
	float                                              ReactionTime;                                     		// 0x0048 ( 0x0004[ CPF_Edit | CPF_Config ]
	float                                              Jumpiness;                                        		// 0x004C ( 0x0004[ CPF_Edit | CPF_Config ]
	unsigned long                                      bJumpy:1;                                         		// 0x0050 ( 0x0004 [0x00000001][ CPF_Config ]
}; // Size: 0x0054

// Struct UnrealGame.HoldObjective.TouchingPlayer
struct DLL_IMPORT FTouchingPlayer
{
	class AController*                                 C;                                                		// 0x0000 ( 0x0004
	float                                              TouchTime;                                        		// 0x0004 ( 0x0004
}; // Size: 0x0008

// Struct UnrealGame.UnrealPlayerChatManager.ChatBan
struct DLL_IMPORT FChatBan
{
	int                                                PlayerID;                                         		// 0x0000 ( 0x0004
	struct FString                                     PlayerHash;                                       		// 0x0004 ( 0x000C[ CPF_NeedCtorLink ]
	struct FString                                     PlayerAddress;                                    		// 0x0010 ( 0x000C[ CPF_NeedCtorLink ]
	unsigned char                                      PlayerVoiceMask;                                  		// 0x001C ( 0x0001
	unsigned char                                      Restriction;                                      		// 0x001D ( 0x0001
}; // Size: 0x0020

// Struct UnrealGame.UnrealPlayerChatManager.StoredChatBan
struct DLL_IMPORT FStoredChatBan
{
	struct FString                                     PlayerHash;                                       		// 0x0000 ( 0x000C[ CPF_NeedCtorLink ]
	unsigned char                                      Restriction;                                      		// 0x000C ( 0x0001
}; // Size: 0x0010

#ifdef _MSC_VER
#pragma pack ( pop )
#endif

