#pragma once
/*
# ======================================================================================== #
# > ArcticCombat SDK
# > Generated By HJSdkGen v1.06b
# ---------------------------------------------------------------------------------------- #
# > Package : UnrealGame
# >    File : UnrealGame\UnrealGame.h
# ======================================================================================== #
*/


/*
# ======================================================================================== #
# > Forward Declarations
# ======================================================================================== #
*/

class AStartupMessage;
class AUnrealMPGameInfo;
class ADeathMatch;
class URosterEntry;
class AUnrealPawn;
class AJumpSpot;
class AGameObjective;
class AGameObject;
class ATeamPlayerReplicationInfo;
class ASpecialVehicleObjective;
class ADMStatsScreen;
class AUnrealVoiceReplicationInfo;
class ABot;
class AKillingSpreeMessage;
class ASquadAI;
class ADMSquad;
class AUnrealPlayer;
class AUnrealTeamInfo;
class AWeaponDamageType;
class AVehicleDamageType;
class ALevelGameRules;
class AUnrealScriptedSequence;
class AHoldSpot;
class ATeamGame;
class ADestroyableObjective;
class ARestingFormation;
class AShootTarget;
class AProximityObjective;
class AHoldObjective;
class ATeamAI;
class AAssaultPath;
class AUnrealChatHandler;
class AIdleKickWarningMessage;
class AAnnounceAdrenaline;
class UCustomBotConfig;
class AUnrealChatRoom;
class ASnipingVolume;
class ATeamVoiceReplicationInfo;
class AWillowWhisp;
class AUnrealTeamChatRoom;
class ADMMutator;
class AUnrealPlayerChatManager;
class AUseObjective;
class APickupMessagePlus;
class AwFlagObjectiveBase;
class AWillowWhispPath;
class AStringMessagePlus;
class ASayMessagePlus;
class ATeamSayMessagePlus;
class APlayerNameMessage;
class ATurretController;
class AUnrealSecurity;
class AFemaleAnnouncer;
class AMaleAnnouncer;

/*
# ======================================================================================== #
# > Includes
# ======================================================================================== #
*/

#include "Structs.h"
#include "ParamStructs.h"
#include "Classes.h"
