#pragma once
/*
# ======================================================================================== #
# > ArcticCombat SDK
# > Generated By HJSdkGen v1.06b
# ---------------------------------------------------------------------------------------- #
# > Package : BatteryNet
# >    File : Structs.h
# ======================================================================================== #
*/

#ifdef _MSC_VER
#pragma pack ( push, 4 )
#endif


/*
# ======================================================================================== #
# > Structs
# ======================================================================================== #
*/

// Struct BatteryNet.BTTcpLink_Channel.GameRoomInfo
class DLL_IMPORT FGameRoomInfo
{
public:
	int                                                RoomNumber;                                       		// 0x0000 ( 0x0004
	struct FString                                     RoomName;                                         		// 0x0004 ( 0x000C[ CPF_NeedCtorLink ]
	struct FString                                     MapName;                                          		// 0x0010 ( 0x000C[ CPF_NeedCtorLink ]
	struct FString                                     GameClass;                                        		// 0x001C ( 0x000C[ CPF_NeedCtorLink ]
	unsigned char                                      GameModeNum;                                      		// 0x0028 ( 0x0001
	unsigned char                                      MaxUserCnt;                                       		// 0x0029 ( 0x0001
	unsigned char                                      TeamCnt;                                          		// 0x002A ( 0x0001
	unsigned char                                      WeaponLimit;                                      		// 0x002B ( 0x0001
	int                                                GameRound;                                        		// 0x002C ( 0x0004
	int                                                GameMinute;                                       		// 0x0030 ( 0x0004
	unsigned char                                      IsHardCore;                                       		// 0x0034 ( 0x0001
	struct FString                                     RoomOwner;                                        		// 0x0038 ( 0x000C[ CPF_NeedCtorLink ]
	unsigned char                                      MapNum;                                           		// 0x0044 ( 0x0001
	unsigned char                                      IsIntervention;                                   		// 0x0045 ( 0x0001
	unsigned char                                      IsFreeCam;                                        		// 0x0046 ( 0x0001
	unsigned char                                      IsVoiceChat;                                      		// 0x0047 ( 0x0001
	unsigned char                                      IsTeamValance;                                    		// 0x0048 ( 0x0001
	unsigned char                                      IsOurForcesDamage;                                		// 0x0049 ( 0x0001
	unsigned char                                      IsKillCam;                                        		// 0x004A ( 0x0001
	unsigned char                                      IsVote;                                           		// 0x004B ( 0x0001
	unsigned char                                      IsChangeOffenseAndDefense;                        		// 0x004C ( 0x0001
	unsigned char                                      ChangeOffenseAndDefenseRound;                     		// 0x004D ( 0x0001
	unsigned char                                      BombHold;                                         		// 0x004E ( 0x0001
	unsigned char                                      IsPassword;                                       		// 0x004F ( 0x0001
	struct FString                                     Password;                                         		// 0x0050 ( 0x000C[ CPF_NeedCtorLink ]
	unsigned char                                      PlayWithBots;                                     		// 0x005C ( 0x0001
	unsigned char                                      MaxAFUserAndBotNum;                               		// 0x005D ( 0x0001
	unsigned char                                      MaxRSAUserAndBotNum;                              		// 0x005E ( 0x0001
	unsigned char                                      UserTeamNum;                                      		// 0x005F ( 0x0001
	unsigned char                                      BotModeDifficulty;                                		// 0x0060 ( 0x0001
	unsigned char                                      RoomType;                                         		// 0x0061 ( 0x0001
	unsigned char                                      ResponType;                                       		// 0x0062 ( 0x0001

	// Public Imports
	FGameRoomInfo(struct FGameRoomInfo const &);
	FGameRoomInfo(void);
	~FGameRoomInfo(void);
	struct FGameRoomInfo &  operator=(struct FGameRoomInfo const &);
}; // Size: 0x0064

// Struct BatteryNet.BTTcpLink_Channel.NetAuctionItem
class DLL_IMPORT FNetAuctionItem
{
public:
	int                                                UniqueID;                                         		// 0x0000 ( 0x0004
	int                                                ItemID;                                           		// 0x0004 ( 0x0004
	int                                                AddPartsID;                                       		// 0x0008 ( 0x0004
	int                                                UntilTime;                                        		// 0x000C ( 0x0004
	int                                                BiddingPrice;                                     		// 0x0010 ( 0x0004
	int                                                InstantlyBuyingPrice;                             		// 0x0014 ( 0x0004
	int                                                ItemDamaged;                                      		// 0x0018 ( 0x0004
	struct FString                                     HighestBidderName;                                		// 0x001C ( 0x000C[ CPF_NeedCtorLink ]
	struct FString                                     SellerName;                                       		// 0x0028 ( 0x000C[ CPF_NeedCtorLink ]
	int                                                GuarantyPoint;                                    		// 0x0034 ( 0x0004

	// Public Imports
	FNetAuctionItem(struct FNetAuctionItem const &);
	FNetAuctionItem(void);
	~FNetAuctionItem(void);
	struct FNetAuctionItem &  operator=(struct FNetAuctionItem const &);
}; // Size: 0x0038

// Struct BatteryNet.BTTcpLink_Channel.SystemMsgParam
class DLL_IMPORT FSystemMsgParam
{
public:
	int                                                MsgCode;                                          		// 0x0000 ( 0x0004
	struct FString                                     CharName;                                         		// 0x0004 ( 0x000C[ CPF_NeedCtorLink ]
	int                                                ServerID;                                         		// 0x0010 ( 0x0004
	int                                                ChannelNum;                                       		// 0x0014 ( 0x0004
	int                                                CharLevel;                                        		// 0x0018 ( 0x0004
	int                                                ItemID;                                           		// 0x001C ( 0x0004
	int                                                Point;                                            		// 0x0020 ( 0x0004

	// Public Imports
	FSystemMsgParam(struct FSystemMsgParam const &);
	FSystemMsgParam(void);
	~FSystemMsgParam(void);
	struct FSystemMsgParam &  operator=(struct FSystemMsgParam const &);
}; // Size: 0x0024

// Struct BatteryNet.BTTcpLink_Channel.ClanInfo
class DLL_IMPORT FClanInfo
{
public:
	struct FString                                     ClanMasterCharname;                               		// 0x0000 ( 0x000C[ CPF_NeedCtorLink ]
	int                                                ClanWin;                                          		// 0x000C ( 0x0004
	int                                                ClanLose;                                         		// 0x0010 ( 0x0004
	int                                                ClanDraw;                                         		// 0x0014 ( 0x0004
	int                                                tRankCur;                                         		// 0x0018 ( 0x0004
	int                                                tRankPrev;                                        		// 0x001C ( 0x0004
	int                                                mRankCur;                                         		// 0x0020 ( 0x0004
	int                                                mRankPrev;                                        		// 0x0024 ( 0x0004
	unsigned char                                      Region;                                           		// 0x0028 ( 0x0001
	int                                                MemberCnt;                                        		// 0x002C ( 0x0004
	int                                                MemberTotal;                                      		// 0x0030 ( 0x0004
	unsigned char                                      IsRecruit;                                        		// 0x0034 ( 0x0001
	struct FString                                     HowOld;                                           		// 0x0038 ( 0x000C[ CPF_NeedCtorLink ]
	struct FString                                     Keyword;                                          		// 0x0044 ( 0x000C[ CPF_NeedCtorLink ]
	struct FString                                     Intro;                                            		// 0x0050 ( 0x000C[ CPF_NeedCtorLink ]
	struct FString                                     CM_ClanName;                                      		// 0x005C ( 0x000C[ CPF_NeedCtorLink ]
	int                                                CM_Pattern;                                       		// 0x0068 ( 0x0004
	int                                                CM_BG;                                            		// 0x006C ( 0x0004
	int                                                CM_BL;                                            		// 0x0070 ( 0x0004
	struct FString                                     ClanNoti;                                         		// 0x0074 ( 0x000C[ CPF_NeedCtorLink ]
	int                                                ClanExp;                                          		// 0x0080 ( 0x0004
	int                                                ClanKill;                                         		// 0x0084 ( 0x0004
	int                                                ClanDeath;                                        		// 0x0088 ( 0x0004
	int                                                ClanAssist;                                       		// 0x008C ( 0x0004
	int                                                ClanActivity;                                     		// 0x0090 ( 0x0004
	int                                                ClanActivityRank;                                 		// 0x0094 ( 0x0004
	int                                                ClanActivityRankPrev;                             		// 0x0098 ( 0x0004
	int                                                ClanActivityMRank;                                		// 0x009C ( 0x0004
	int                                                ClanActivityMRankPrev;                            		// 0x00A0 ( 0x0004
	int                                                ClanLevel;                                        		// 0x00A4 ( 0x0004

	// Public Imports
	FClanInfo(struct FClanInfo const &);
	FClanInfo(void);
	~FClanInfo(void);
	struct FClanInfo &  operator=(struct FClanInfo const &);
}; // Size: 0x00A8

// Struct BatteryNet.BTTcpLink_Channel.CharInfo
class DLL_IMPORT FCharInfo
{
public:
	int                                                Level;                                            		// 0x0000 ( 0x0004
	int                                                Exp;                                              		// 0x0004 ( 0x0004
	int                                                Stamina;                                          		// 0x0008 ( 0x0004
	int                                                HP;                                               		// 0x000C ( 0x0004
	int                                                PrevRanking;                                      		// 0x0010 ( 0x0004
	int                                                Ranking;                                          		// 0x0014 ( 0x0004
	int                                                PrevHeadShotRanking;                              		// 0x0018 ( 0x0004
	int                                                HeadShotRanking;                                  		// 0x001C ( 0x0004
	int                                                PrevWomanRanking;                                 		// 0x0020 ( 0x0004
	int                                                WomanRanking;                                     		// 0x0024 ( 0x0004
	int                                                MonthlyPrevRanking;                               		// 0x0028 ( 0x0004
	int                                                MonthlyRanking;                                   		// 0x002C ( 0x0004
	int                                                MonthlyPrevHeadShotRanking;                       		// 0x0030 ( 0x0004
	int                                                MonthlyHeadShotRanking;                           		// 0x0034 ( 0x0004
	int                                                MonthlyPrevWomanRanking;                          		// 0x0038 ( 0x0004
	int                                                MonthlyWomanRanking;                              		// 0x003C ( 0x0004
	int                                                Kill;                                             		// 0x0040 ( 0x0004
	int                                                Death;                                            		// 0x0044 ( 0x0004
	int                                                Win;                                              		// 0x0048 ( 0x0004
	int                                                Lose;                                             		// 0x004C ( 0x0004
	int                                                TeamKill;                                         		// 0x0050 ( 0x0004
	int                                                Assist;                                           		// 0x0054 ( 0x0004
	int                                                Point;                                            		// 0x0058 ( 0x0004
	int                                                Cash;                                             		// 0x005C ( 0x0004
	int                                                HeadShot2;                                        		// 0x0060 ( 0x0004
	int                                                DisCon;                                           		// 0x0064 ( 0x0004
	int                                                TotPlayTime;                                      		// 0x0068 ( 0x0004
	int                                                DispHeadItem;                                     		// 0x006C ( 0x0004
	int                                                DispHeadAddItem;                                  		// 0x0070 ( 0x0004
	int                                                DispFaceItem;                                     		// 0x0074 ( 0x0004
	unsigned char                                      LookForClan;                                      		// 0x0078 ( 0x0001
	int                                                ClanContribue;                                    		// 0x007C ( 0x0004
	int                                                ClanWin;                                          		// 0x0080 ( 0x0004
	int                                                ClanLose;                                         		// 0x0084 ( 0x0004
	int                                                ClanKill;                                         		// 0x0088 ( 0x0004
	int                                                ClanDeath;                                        		// 0x008C ( 0x0004
	int                                                ClanAssist;                                       		// 0x0090 ( 0x0004
	int                                                ClanHeadshot;                                     		// 0x0094 ( 0x0004
	int                                                ClanDiscon;                                       		// 0x0098 ( 0x0004
	int                                                ClanRankingPrev;                                  		// 0x009C ( 0x0004
	int                                                ClanRanking;                                      		// 0x00A0 ( 0x0004
	int                                                ClanRankingMonthlyPrev;                           		// 0x00A4 ( 0x0004
	int                                                ClanRankingMonthly;                               		// 0x00A8 ( 0x0004
	int                                                LevelMarkID;                                      		// 0x00AC ( 0x0004
	int                                                TitleMarkID;                                      		// 0x00B0 ( 0x0004
	int                                                Reserved1;                                        		// 0x00B4 ( 0x0004
	int                                                Reserved2;                                        		// 0x00B8 ( 0x0004
	int                                                Reserved3;                                        		// 0x00BC ( 0x0004

	// Public Imports
	struct FCharInfo &  operator=(struct FCharInfo const &);
}; // Size: 0x00C0


#ifdef _MSC_VER
#pragma pack ( pop )
#endif

