#pragma once
/*
# ======================================================================================== #
# > ArcticCombat SDK
# > Generated By HJSdkGen v1.06b
# ---------------------------------------------------------------------------------------- #
# > Package : WGame
# >    File : Structs.h
# ======================================================================================== #
*/

#ifdef _MSC_VER
#pragma pack ( push, 4 )
#endif


/*
# ======================================================================================== #
# > Structs
# ======================================================================================== #
*/

// Struct WGame.wUtil.PlayerRecord
class DLL_IMPORT FPlayerRecord
{
public:
	struct FString                                     DefaultName;                                      		// 0x0000 ( 0x000C[ CPF_Edit | CPF_NeedCtorLink ]
	class UClass*                                      Species;                                          		// 0x000C ( 0x0004[ CPF_Edit ]
	struct FString                                     MeshName;                                         		// 0x0010 ( 0x000C[ CPF_Edit | CPF_NeedCtorLink ]
	struct FString                                     BodySkinName;                                     		// 0x001C ( 0x000C[ CPF_Edit | CPF_NeedCtorLink ]
	struct FString                                     FaceSkinName;                                     		// 0x0028 ( 0x000C[ CPF_Edit | CPF_NeedCtorLink ]
	class UMaterial*                                   Portrait;                                         		// 0x0034 ( 0x0004[ CPF_Edit ]
	struct FString                                     TextName;                                         		// 0x0038 ( 0x000C[ CPF_Edit | CPF_NeedCtorLink ]
	struct FString                                     VoiceClassName;                                   		// 0x0044 ( 0x000C[ CPF_Edit | CPF_NeedCtorLink ]
	struct FString                                     Sex;                                              		// 0x0050 ( 0x000C[ CPF_NeedCtorLink ]
	struct FString                                     Accuracy;                                         		// 0x005C ( 0x000C[ CPF_NeedCtorLink ]
	struct FString                                     Aggressiveness;                                   		// 0x0068 ( 0x000C[ CPF_NeedCtorLink ]
	struct FString                                     StrafingAbility;                                  		// 0x0074 ( 0x000C[ CPF_NeedCtorLink ]
	struct FString                                     CombatStyle;                                      		// 0x0080 ( 0x000C[ CPF_NeedCtorLink ]
	struct FString                                     Tactics;                                          		// 0x008C ( 0x000C[ CPF_NeedCtorLink ]
	struct FString                                     ReactionTime;                                     		// 0x0098 ( 0x000C[ CPF_NeedCtorLink ]
	struct FString                                     Jumpiness;                                        		// 0x00A4 ( 0x000C[ CPF_NeedCtorLink ]
	struct FString                                     Race;                                             		// 0x00B0 ( 0x000C[ CPF_NeedCtorLink ]
	struct FString                                     FavoriteWeapon;                                   		// 0x00BC ( 0x000C[ CPF_NeedCtorLink ]
	struct FString                                     Menu;                                             		// 0x00C8 ( 0x000C[ CPF_NeedCtorLink ]
	struct FString                                     Skeleton;                                         		// 0x00D4 ( 0x000C[ CPF_NeedCtorLink ]
	int                                                RecordIndex;                                      		// 0x00E0 ( 0x0004[ CPF_Edit | CPF_Const ]
	struct FString                                     Ragdoll;                                          		// 0x00E4 ( 0x000C[ CPF_NeedCtorLink ]
	unsigned char                                      BotUse;                                           		// 0x00F0 ( 0x0001
	unsigned long                                      UseSpecular:1;                                    		// 0x00F4 ( 0x0004 [0x00000001]
	unsigned long                                      TeamFace:1;                                       		// 0x00F4 ( 0x0004 [0x00000002]
	unsigned long                                      ZeroWeaponOffsets:1;                              		// 0x00F4 ( 0x0004 [0x00000004]
	class UClass*                                      PlayerInfo;                                       		// 0x00F8 ( 0x0004[ CPF_Edit ]

	// Public Imports
	FPlayerRecord(struct FPlayerRecord const &);
	FPlayerRecord(void);
	~FPlayerRecord(void);
	struct FPlayerRecord &  operator=(struct FPlayerRecord const &);
}; // Size: 0x00FC

#ifdef _MSC_VER
#pragma pack ( pop )
#endif

