#pragma once
/*
# ======================================================================================== #
# > ArcticCombat SDK
# > Generated By HJSdkGen v1.06b
# ---------------------------------------------------------------------------------------- #
# > Package : WGame
# >    File : WGame\WGame.h
# ======================================================================================== #
*/


/*
# ======================================================================================== #
# > Forward Declarations
# ======================================================================================== #
*/

class AwAILevel;
class UwState;
class UShortMemory;
class UMemoryItem;
class AwAIBotBase;
class UwPlayerInfo;
class USpeciesType;
class AAimedAttachment;
class UwUtil;
class UCachePlayers;
class UDecoText;
class AwEntryGameInfo;
class UPlayerRecordClass;
class AwPawn;
class UwPawnSoundGroup;
class AwPlayer;
class AwSupplyPack;
class AwHealthPack;
class AwUAVPack;
class AwHeliPack;
class AwArtilleryPack;
class AwMedalPack;
class AwBotVehicleController;
class ACombo;
class AwWeaponAttachment;
class UwRosterEntry;
class USPECIES_Human;
class USPECIES_Merc;
class UwMercMaleSoundGroup;
class AwBot;
class AwBotVehicle;
class AwHelicopter;
class AAttractCamera;
class AComboMessage;
class AwPlayerReplicationInfo;
class UGoal;
class UGoal_PlanAndExec;
class UGoal_Fire;
class UGoal_MovePathToward;
class UGoal_Roam;
class UGoal_Shoot;
class UGoal_Test;
class UwPurpose;
class UwPurposeExplore;
class UwActionContainer;
class AwAIPawn;
class UwActionPlanner;
class UwFutureState;
class UTargetingSystem;
class UwPlanMaster;
class UwAction;
class AwHelicopterController;
class AwHelicopterRSA;
class UGoal_MoveToward;
class UDAE;
class UDAE_Multiple;
class UDAE_InSight;
class UDAE_Visibility;
class UDAE_Proximity;
class UDAE_IsTurret;
class UDAE_RecentTarget;
class UwAction_Empty;
class UwActionLayer;
class UwAction_Fire;
class UwAction_Reload;
class UwAction_Explore;
class UwAction_ExploreTutorial;
class UwAction_IdleHands;
class UwAction_ApproachAndMelee;
class UwAction_MoveToEnemyInfluence;
class UwAction_MoveToSeeTarget;
class UwAction_LookAround;
class UwAction_UseHelicopter;
class UwAction_UseAIrstrikeRealTime;
class UwAction_UseUAV;
class UwAction_MeleeNoTarget;
class UwAction_FireSpecialTarget;
class UwAction_PickTarget;
class UwAction_ThrowGrenadeRealTime;
class UwAction_PickHealth;
class UwAction_PickHelicopter;
class UwAction_PickAirstrike;
class UwAction_PickUAV;
class UwAction_SwitchWeapon;
class AwAIBot;
class UGoal_Stay;
class UGoal_SwitchWeapon;
class UGoal_ExecPlan;
class UGoal_UseAirstrikeRealTime;
class UGoal_SwitchAndUse;
class UGoal_Reload;
class UGoal_Fail;
class UGoal_MoveToEnemyInfluence;
class UGoal_MeleeNoTarget;
class UGoal_LookAround;
class UGoal_ApproachAndMelee;
class UGoal_ThrowGrenadeRealTime;
class UGoal_PickTarget;
class UGoal_MoveToSeeTarget;
class UGoal_ExecPartialPlan;
class UGoal_Melee;
class UGoal_Throw;
class UGoal_SwitchAndThrow;
class UGoal_SwitchAndFire;
class UGoal_Look;
class AwDeathMessage;
class AwWeaponPickup_Location;
class AwWeaponPickup_M2B;
class AwWeaponPickup_RPG7;
class AwVehicle;
class AwTurret;
class AwTurret_FNM240;
class AwAmmoSupplyObjective;
class AwBTR_ArrangeTurret;
class AwBTR_Turret_FNM240;
class AwTurret_Base;
class AwKillerMessagePlus;
class AwTurret_FNM240_Base;
class AwTurret_FNM240_Swivel;
class ABulletSplash;
class UPrecacheGameClient;
class AwTeamGame;
class UwPurposeAttackTarget;
class UwPurposeAttackTargetDOM;
class UwPurposeCaptureFlag;
class UwAction_GotoFlag;
class UwAction_CaptureFlag;
class UGoal_CaptureFlag;
class UGoal_GoToFlag;
class AwTeamRoster;

/*
# ======================================================================================== #
# > Includes
# ======================================================================================== #
*/

#include "Structs.h"
#include "ParamStructs.h"
#include "Classes.h"
