class wWeaponRes_BarrettM82A1 extends wWeaponRes_Base;

defaultproperties
{
    szClass_Shell="Xeffects.ShellSpewer_127"
    szClass_Shell_3rd="Xeffects.ShellSpewer_127_3rd"
    fTracerPop=1.0000000
    szClass_Muzz_1st="Xeffects.SR_MuzFlash_02_1RD"
    szClass_Muzz_3rd="Xeffects.SR_MuzFlash_02_3RD"
    szClass_Smoke_1st="XEffects.AssaultMuzzleSmoke"
    szClass_Smoke_3rd="Xeffects.SR_MuzFlash_smoke_3rd"
    effect_Melee_Attack1=Class'XEffects.HitEffect_Stock_Meleeattack'
    effect_Melee_Attack2=Class'XEffects.HitEffect_Stock_Meleeattack'
    szIcon_HUD="Warfare_UI_Item.HUDIcon.Item_HUD_WP_SR_BARRETT"
    szIcon_Kill="Warfare_UI_Item.Item_killIcon"
    ibIcon_Kill=(X=0,Y=546,W=128,H=32)
    szType_DisplayAmmo="ammoSniper"
    fsound_Fire="Warfare_Sound_Weapon/SR/BarrettM82/fire"
    fsound_Fire_Stereo="Warfare_Sound_Weapon/SR/BarrettM82/fire_s"
    fsound_Fire_Shell="Warfare_Sound_Weapon/ETC/shell/shell_762mm"
    fsound_Fire_Empty="Warfare_Sound_Weapon/ETC/dryfire/weapon_sr_fire_nobullet"
    fsound_Melee_Ok="Warfare_Sound_Weapon/ETC/buttplate/weapon_melee_buttplate_attack"
    fsound_Melee_Miss="Warfare_Sound_Weapon/ETC/buttplate/weapon_melee_buttplate_miss"
    fsound_Rechamber="Warfare_Sound_Weapon/SR/BarrettM82/rechamber"
    fsound_Reload="Warfare_Sound_Weapon/SR/BarrettM82/reload"
    fsound_ReloadEmpty="Warfare_Sound_Weapon/SR/BarrettM82/reload_empty"
    fsound_Select="Warfare_Sound_Weapon/SR/BarrettM82/select"
    fsound_Pickup="Warfare_Sound_Char/GetItem/char_getitem_weapon"
    fsound_Select_New="Warfare_Sound_Weapon/SR/BarrettM82/select_n"
}