#pragma once
/*
# ======================================================================================== #
# > ArcticCombat SDK
# > Generated By HJSdkGen v1.06b
# ---------------------------------------------------------------------------------------- #
# > Package : WinDrv
# >    File : Classes.h
# ======================================================================================== #
*/

#ifdef _MSC_VER
#pragma pack ( push, 4 )
#endif


/*
# ======================================================================================== #
# > Classes
# ======================================================================================== #
*/

// Class WinDrv.WindowsWebLog
class DLL_IMPORT UWindowsWebLog : public UWebLog
{
public:

	// Public Imports
	UWindowsWebLog(class UWindowsWebLog const &);
	UWindowsWebLog(void);
	class UWindowsWebLog &  operator=(class UWindowsWebLog const &);
	static void  InternalConstructor(void *);
	static class UClass *  StaticClass(void);

	// Private Imports
private:
	static class UClass PrivateStaticClass;
	void  SendURL(unsigned short const *);
}; // Size: 0x0000

// Class WinDrv.WindowsViewport
class DLL_IMPORT UWindowsViewport : public UViewport
{
public:
	unsigned char                                      _0x01C0[ 0x144 ];                                 		// 0x01C0 ( 0x0144 )

	// Public Imports
	UWindowsViewport(class UWindowsViewport const &);
	UWindowsViewport(void);
	class UWindowsViewport &  operator=(class UWindowsViewport const &);
	void  AttachDebugger(void);
	int  CauseInputEvent(int,enum EInputAction,float);
	static int CoInitialized;
	static struct IDirectInput8W * DirectInput8;
	void  EndFullscreen(void);
	static int  EnumAxesCallback(struct DIDEVICEOBJECTINSTANCEW const *,void *);
	static int  EnumJoysticksCallback(struct DIDEVICEINSTANCEW const *,void *);
	class UWindowsClient *  GetOuterUWindowsClient(void)const ;
	unsigned long  GetViewportButtonFlags(unsigned long);
	static void  InternalConstructor(void *);
	static struct IDirectInputDevice8W * Joystick;
	static struct IDirectInputDevice8W * Mouse;
	void  SetTopness(void);
	static class FSpeechAudioInput * SpeechAudioInput;
	static class FSpeechRecognitionSAPI * SpeechRecognition;
	static class UClass *  StaticClass(void);
	static struct ISpVoice * TextToSpeechObject;
	static float TextToSpeechVolume;
	void  ToggleFullscreen(void);
	void  ToggleIME(int);
	long  ViewportWndProc(unsigned int,unsigned int,long);

	// Private Imports
private:
	static class UClass PrivateStaticClass;
}; // Size: 0x0144

// Class WinDrv.WindowsClient
class DLL_IMPORT UWindowsClient : public UClient
{
public:
	unsigned char                                      _0x0178[ 0x04 ];                                  		// 0x0178 ( 0x0004 )
	unsigned long                                      UseJoystick:1;                                    		// 0x017C ( 0x0004 )  [0x00000001][ CPF_Edit ]
	unsigned long                                      StartupFullscreen:1;                              		// 0x0180 ( 0x0004 )  [0x00000001][ CPF_Edit ]
	unsigned long                                      LobbyWindowMode:1;                                		// 0x0184 ( 0x0004 )  [0x00000001][ CPF_Edit ]
	unsigned long                                      UseSpeechRecognition:1;                           		// 0x0188 ( 0x0004 )  [0x00000001][ CPF_Edit ]
	float                                              MouseXMultiplier;                                 		// 0x018C ( 0x0004 ) [ CPF_Edit ]
	float                                              MouseYMultiplier;                                 		// 0x0190 ( 0x0004 ) [ CPF_Edit ]
	unsigned char                                      _0x0194[ 0x38 ];                                  		// 0x0194 ( 0x0038 )

	// Public Imports
	UWindowsClient(class UWindowsClient const &);
	UWindowsClient(void);
	class UWindowsClient &  operator=(class UWindowsClient const &);
	static void  InternalConstructor(void *);
	static class UClass *  StaticClass(void);
	void  StaticConstructor(void);

	// Private Imports
private:
	static class UClass PrivateStaticClass;
}; // Size: 0x0054

#ifdef _MSC_VER
#pragma pack ( pop )
#endif

