#pragma once
/*
# ======================================================================================== #
# > ArcticCombat SDK
# > Generated By HJSdkGen v1.06b
# ---------------------------------------------------------------------------------------- #
# > Package : Window
# >    File : Classes.h
# ======================================================================================== #
*/

#ifdef _MSC_VER
#pragma pack ( push, 4 )
#endif


/*
# ======================================================================================== #
# > Classes
# ======================================================================================== #
*/

// Class Window.WindowManager
class DLL_IMPORT UWindowManager : public UObject
{
public:
	unsigned char                                      _0x002C[ 0x04 ];                                  		// 0x002C ( 0x0004 )
}; // Size: 0x0004

#ifdef _MSC_VER
#pragma pack ( pop )
#endif

