#pragma once
/*
# ======================================================================================== #
# > ArcticCombat SDK
# > Generated By HJSdkGen v1.06b
# ---------------------------------------------------------------------------------------- #
# > Package : XInterface
# >    File : Structs.h
# ======================================================================================== #
*/

#ifdef _MSC_VER
#pragma pack ( push, 4 )
#endif


/*
# ======================================================================================== #
# > Structs
# ======================================================================================== #
*/

// Struct XInterface.GUIController.RestoreMenuItem
class DLL_IMPORT FRestoreMenuItem
{
public:
	struct FString                                     MenuClassName;                                    		// 0x0000 ( 0x000C[ CPF_Edit | CPF_NeedCtorLink ]
	struct FString                                     Param1;                                           		// 0x000C ( 0x000C[ CPF_Edit | CPF_NeedCtorLink ]
	struct FString                                     Param2;                                           		// 0x0018 ( 0x000C[ CPF_Edit | CPF_NeedCtorLink ]

	// Public Imports
	FRestoreMenuItem(struct FRestoreMenuItem const &);
	FRestoreMenuItem(void);
	~FRestoreMenuItem(void);
	struct FRestoreMenuItem &  operator=(struct FRestoreMenuItem const &);
}; // Size: 0x0024

// Struct XInterface.GUIController.AutoLoadMenu
class DLL_IMPORT FAutoLoadMenu
{
public:
	struct FString                                     MenuClassName;                                    		// 0x0000 ( 0x000C[ CPF_NeedCtorLink ]
	unsigned long                                      bPreInitialize:1;                                 		// 0x000C ( 0x0004 [0x00000001]

	// Public Imports
	FAutoLoadMenu(struct FAutoLoadMenu const &);
	FAutoLoadMenu(void);
	~FAutoLoadMenu(void);
	struct FAutoLoadMenu &  operator=(struct FAutoLoadMenu const &);
}; // Size: 0x0010

// Struct XInterface.GUIController.eOwnageMap
class DLL_IMPORT FeOwnageMap
{
public:
	int                                                RLevel;                                           		// 0x0000 ( 0x0004
	struct FString                                     MapName;                                          		// 0x0004 ( 0x000C[ CPF_NeedCtorLink ]
	struct FString                                     MapDesc;                                          		// 0x0010 ( 0x000C[ CPF_NeedCtorLink ]
	struct FString                                     MapURL;                                           		// 0x001C ( 0x000C[ CPF_NeedCtorLink ]

	// Public Imports
	FeOwnageMap(struct FeOwnageMap const &);
	FeOwnageMap(void);
	~FeOwnageMap(void);
	struct FeOwnageMap &  operator=(struct FeOwnageMap const &);
}; // Size: 0x0028

// Struct XInterface.GUIController.ProfileStruct
class DLL_IMPORT FProfileStruct
{
public:
	struct FString                                     ProfileName;                                      		// 0x0000 ( 0x000C[ CPF_NeedCtorLink ]
	float                                              ProfileSeconds;                                   		// 0x000C ( 0x0004

	// Public Imports
	FProfileStruct(struct FProfileStruct const &);
	FProfileStruct(void);
	~FProfileStruct(void);
	struct FProfileStruct &  operator=(struct FProfileStruct const &);
}; // Size: 0x0010

// Struct XInterface.GUIController.DesignModeHint
class DLL_IMPORT FDesignModeHint
{
public:
	struct FString                                     key;                                              		// 0x0000 ( 0x000C[ CPF_Edit | CPF_Localized | CPF_NeedCtorLink ]
	struct FString                                     Description;                                      		// 0x000C ( 0x000C[ CPF_Edit | CPF_Localized | CPF_NeedCtorLink ]

	// Public Imports
	FDesignModeHint(struct FDesignModeHint const &);
	FDesignModeHint(void);
	~FDesignModeHint(void);
	struct FDesignModeHint &  operator=(struct FDesignModeHint const &);
}; // Size: 0x0018

// Struct XInterface.GUI.GUITabItem
struct DLL_IMPORT FGUITabItem
{
	struct FString                                     ClassName;                                        		// 0x0000 ( 0x000C[ CPF_Edit | CPF_NeedCtorLink ]
	struct FString                                     Caption;                                          		// 0x000C ( 0x000C[ CPF_Edit | CPF_Localized | CPF_NeedCtorLink ]
	struct FString                                     Hint;                                             		// 0x0018 ( 0x000C[ CPF_Edit | CPF_Localized | CPF_NeedCtorLink ]
}; // Size: 0x0024

// Struct XInterface.GUI.AutoLoginInfo
struct DLL_IMPORT FAutoLoginInfo
{
	struct FString                                     IP;                                               		// 0x0000 ( 0x000C[ CPF_Edit | CPF_NeedCtorLink ]
	struct FString                                     Port;                                             		// 0x000C ( 0x000C[ CPF_Edit | CPF_NeedCtorLink ]
	struct FString                                     UserName;                                         		// 0x0018 ( 0x000C[ CPF_Edit | CPF_NeedCtorLink ]
	struct FString                                     Password;                                         		// 0x0024 ( 0x000C[ CPF_Edit | CPF_NeedCtorLink ]
	unsigned long                                      bAutologin:1;                                     		// 0x0030 ( 0x0004 [0x00000001][ CPF_Edit ]
}; // Size: 0x0034

// Struct XInterface.GUI.GUITreeNode
class DLL_IMPORT FGUITreeNode
{
public:
	struct FString                                     Caption;                                          		// 0x0000 ( 0x000C[ CPF_Edit | CPF_NeedCtorLink ]
	struct FString                                     Value;                                            		// 0x000C ( 0x000C[ CPF_Edit | CPF_NeedCtorLink ]
	struct FString                                     ParentCaption;                                    		// 0x0018 ( 0x000C[ CPF_Edit | CPF_NeedCtorLink ]
	struct FString                                     ExtraInfo;                                        		// 0x0024 ( 0x000C[ CPF_Edit | CPF_NeedCtorLink ]
	int                                                Level;                                            		// 0x0030 ( 0x0004[ CPF_Edit ]
	unsigned long                                      bEnabled:1;                                       		// 0x0034 ( 0x0004 [0x00000001][ CPF_Edit ]

	// Public Imports
	FGUITreeNode(struct FGUITreeNode const &);
	FGUITreeNode(void);
	~FGUITreeNode(void);
	struct FGUITreeNode &  operator=(struct FGUITreeNode const &);
	int  operator==(struct FGUITreeNode const &)const ;
}; // Size: 0x0038

// Struct XInterface.GUI.ImageListElem
class DLL_IMPORT FImageListElem
{
public:
	int                                                Item;                                             		// 0x0000 ( 0x0004
	class UMaterial*                                   Image;                                            		// 0x0004 ( 0x0004
	int                                                Locked;                                           		// 0x0008 ( 0x0004

	// Public Imports
	struct FImageListElem &  operator=(struct FImageListElem const &);
}; // Size: 0x000C

// Struct XInterface.GUI.MultiSelectListElem
class DLL_IMPORT FMultiSelectListElem
{
public:
	struct FString                                     Item;                                             		// 0x0000 ( 0x000C[ CPF_NeedCtorLink ]
	class UObject*                                     ExtraData;                                        		// 0x000C ( 0x0004
	struct FString                                     ExtraStrData;                                     		// 0x0010 ( 0x000C[ CPF_NeedCtorLink ]
	unsigned long                                      bSelected:1;                                      		// 0x001C ( 0x0004 [0x00000001]
	int                                                SelectionIndex;                                   		// 0x0020 ( 0x0004
	unsigned long                                      bSection:1;                                       		// 0x0024 ( 0x0004 [0x00000001]

	// Public Imports
	FMultiSelectListElem(struct FMultiSelectListElem const &);
	FMultiSelectListElem(void);
	~FMultiSelectListElem(void);
	struct FMultiSelectListElem &  operator=(struct FMultiSelectListElem const &);
}; // Size: 0x0028

// Struct XInterface.GUI.APackInfo
struct DLL_IMPORT FAPackInfo
{
	struct FString                                     PackageName;                                      		// 0x0000 ( 0x000C[ CPF_NeedCtorLink ]
	struct FString                                     Description;                                      		// 0x000C ( 0x000C[ CPF_Localized | CPF_NeedCtorLink ]
}; // Size: 0x0018

// Struct XInterface.GUI.GUIListElem
class DLL_IMPORT FGUIListElem
{
public:
	struct FString                                     Item;                                             		// 0x0000 ( 0x000C[ CPF_NeedCtorLink ]
	class UObject*                                     ExtraData;                                        		// 0x000C ( 0x0004
	struct FString                                     ExtraStrData;                                     		// 0x0010 ( 0x000C[ CPF_NeedCtorLink ]
	unsigned long                                      bSection:1;                                       		// 0x001C ( 0x0004 [0x00000001]

	// Public Imports
	FGUIListElem(struct FGUIListElem const &);
	FGUIListElem(void);
	~FGUIListElem(void);
	struct FGUIListElem &  operator=(struct FGUIListElem const &);
}; // Size: 0x0020

// Struct XInterface.GUIComponent.TimerData
class DLL_IMPORT FTimerData
{
public:
	unsigned long                                      bLoop:1;                                          		// 0x0000 ( 0x0004 [0x00000001]
	struct FName                                       FuncName;                                         		// 0x0004 ( 0x0004
	float                                              Rate;                                             		// 0x0008 ( 0x0004
	float                                              Count;                                            		// 0x000C ( 0x0004

	// Public Imports
	FTimerData(void);
	struct FTimerData &  operator=(struct FTimerData const &);
}; // Size: 0x0010

// Struct XInterface.GUIButton.PaddingPercent
class DLL_IMPORT FPaddingPercent
{
public:
	float                                              HorzPerc;                                         		// 0x0000 ( 0x0004[ CPF_Edit ]
	float                                              VertPerc;                                         		// 0x0004 ( 0x0004[ CPF_Edit ]

	// Public Imports
	struct FPaddingPercent &  operator=(struct FPaddingPercent const &);
}; // Size: 0x0008

// Struct XInterface.GUIMultiColumnList.MultiColumnSortData
class DLL_IMPORT FMultiColumnSortData
{
public:
	struct FString                                     SortString;                                       		// 0x0000 ( 0x000C[ CPF_Edit | CPF_Const | CPF_EditConst | CPF_NeedCtorLink ]
	int                                                SortItem;                                         		// 0x000C ( 0x0004[ CPF_Edit | CPF_Const | CPF_EditConst ]

	// Public Imports
	FMultiColumnSortData(struct FMultiColumnSortData const &);
	FMultiColumnSortData(int,unsigned short const *);
	~FMultiColumnSortData(void);
	struct FMultiColumnSortData &  operator=(struct FMultiColumnSortData const &);
}; // Size: 0x0010

// Struct XInterface.ExtendedConsole.ServerFavorite
struct DLL_IMPORT FServerFavorite
{
	int                                                ServerID;                                         		// 0x0000 ( 0x0004[ CPF_Edit ]
	struct FString                                     IP;                                               		// 0x0004 ( 0x000C[ CPF_Edit | CPF_NeedCtorLink ]
	int                                                Port;                                             		// 0x0010 ( 0x0004[ CPF_Edit ]
	int                                                QueryPort;                                        		// 0x0014 ( 0x0004[ CPF_Edit ]
	struct FString                                     ServerName;                                       		// 0x0018 ( 0x000C[ CPF_Edit | CPF_NeedCtorLink ]
}; // Size: 0x0024

// Struct XInterface.ExtendedConsole.StoredPassword
struct DLL_IMPORT FStoredPassword
{
	struct FString                                     Server;                                           		// 0x0000 ( 0x000C[ CPF_NeedCtorLink ]
	struct FString                                     Password;                                         		// 0x000C ( 0x000C[ CPF_NeedCtorLink ]
}; // Size: 0x0018

// Struct XInterface.ExtendedConsole.ChatStruct
struct DLL_IMPORT FChatStruct
{
	struct FString                                     Message;                                          		// 0x0000 ( 0x000C[ CPF_NeedCtorLink ]
	int                                                Team;                                             		// 0x000C ( 0x0004
}; // Size: 0x0010

// Struct XInterface.HudBase.HudLocalizedMessage
class DLL_IMPORT FHudLocalizedMessage
{
public:
	class UClass*                                      Message;                                          		// 0x0000 ( 0x0004
	struct FString                                     StringMessage;                                    		// 0x0004 ( 0x000C[ CPF_NeedCtorLink ]
	int                                                Switch;                                           		// 0x0010 ( 0x0004
	class APlayerReplicationInfo*                      RelatedPRI;                                       		// 0x0014 ( 0x0004
	class APlayerReplicationInfo*                      RelatedPRI2;                                      		// 0x0018 ( 0x0004
	class UObject*                                     OptionalObject;                                   		// 0x001C ( 0x0004
	float                                              EndOfLife;                                        		// 0x0020 ( 0x0004
	float                                              Lifetime;                                         		// 0x0024 ( 0x0004
	float                                              StartTime;                                        		// 0x0028 ( 0x0004
	class UFont*                                       StringFont;                                       		// 0x002C ( 0x0004
	class FColor                                       DrawColor;                                        		// 0x0030 ( 0x0004
	unsigned char                                      DrawPivot;                                        		// 0x0034 ( 0x0001
	unsigned char                                      StackMode;                                        		// 0x0035 ( 0x0001
	float                                              PosX;                                             		// 0x0038 ( 0x0004
	float                                              PosY;                                             		// 0x003C ( 0x0004
	float                                              dx;                                               		// 0x0040 ( 0x0004
	float                                              dy;                                               		// 0x0044 ( 0x0004
	unsigned long                                      Drawn:1;                                          		// 0x0048 ( 0x0004 [0x00000001]
	unsigned long                                      PlaySound:1;                                      		// 0x0048 ( 0x0004 [0x00000002]

	// Public Imports
	FHudLocalizedMessage(struct FHudLocalizedMessage const &);
	FHudLocalizedMessage(void);
	~FHudLocalizedMessage(void);
	struct FHudLocalizedMessage &  operator=(struct FHudLocalizedMessage const &);
}; // Size: 0x004C

// Struct XInterface.HudCDeathmatch.GameNotice
struct DLL_IMPORT FGameNotice
{
	struct FString                                     sNotice;                                          		// 0x0000 ( 0x000C[ CPF_NeedCtorLink ]
	float                                              fStartTime;                                       		// 0x000C ( 0x0004
	float                                              fEndTime;                                         		// 0x0010 ( 0x0004
	float                                              fLifeTime;                                        		// 0x0014 ( 0x0004
	unsigned long                                      bSendConsole:1;                                   		// 0x0018 ( 0x0004 [0x00000001]
	int                                                NoticeStartPosX;                                  		// 0x001C ( 0x0004
}; // Size: 0x0020

// Struct XInterface.HudCDeathmatch.WeaponState
struct DLL_IMPORT FWeaponState
{
	float                                              PickupTimer;                                      		// 0x0000 ( 0x0004
	unsigned long                                      HasWeapon:1;                                      		// 0x0004 ( 0x0004 [0x00000001]
}; // Size: 0x0008

// Struct XInterface.HudCDeathmatch.SelfKillMessage
struct DLL_IMPORT FSelfKillMessage
{
	struct FString                                     KillerName;                                       		// 0x0000 ( 0x000C[ CPF_NeedCtorLink ]
	struct FString                                     VictimName;                                       		// 0x000C ( 0x000C[ CPF_NeedCtorLink ]
	class UClass*                                      Type;                                             		// 0x0018 ( 0x0004
	float                                              Time;                                             		// 0x001C ( 0x0004
	struct FString                                     Message;                                          		// 0x0020 ( 0x000C[ CPF_NeedCtorLink ]
	class FColor                                       MessageColor;                                     		// 0x002C ( 0x0004
}; // Size: 0x0030

// Struct XInterface.HudCDeathmatch.DamageIndicationInfo
struct DLL_IMPORT FDamageIndicationInfo
{
	struct FVector                                     AttackerLocation;                                 		// 0x0000 ( 0x000C
	int                                                Damage;                                           		// 0x000C ( 0x0004
	class UClass*                                      DamageType;                                       		// 0x0010 ( 0x0004
	float                                              TimeInserted;                                     		// 0x0014 ( 0x0004
	float                                              TimeToRemove;                                     		// 0x0018 ( 0x0004
}; // Size: 0x001C

// Struct XInterface.wHudPart_KillMessage.KillMessageItem
class DLL_IMPORT FKillMessageItem
{
public:
	class APlayerReplicationInfo*                      KillerPRI;                                        		// 0x0000 ( 0x0004
	class APlayerReplicationInfo*                      victimPRI;                                        		// 0x0004 ( 0x0004
	struct FString                                     KillerName;                                       		// 0x0008 ( 0x000C[ CPF_NeedCtorLink ]
	struct FString                                     VictimName;                                       		// 0x0014 ( 0x000C[ CPF_NeedCtorLink ]
	class UClass*                                      DamageType;                                       		// 0x0020 ( 0x0004
	float                                              TimeToRemove;                                     		// 0x0024 ( 0x0004
	unsigned long                                      NoKillerName:1;                                   		// 0x0028 ( 0x0004 [0x00000001]
	unsigned long                                      NoVictimName:1;                                   		// 0x0028 ( 0x0004 [0x00000002]
	class UMaterial*                                   Image;                                            		// 0x002C ( 0x0004
	struct FIntBoxWH                                   ImageCoord;                                       		// 0x0030 ( 0x0010
	class FColor                                       KillerColor;                                      		// 0x0040 ( 0x0004
	class FColor                                       VictimColor;                                      		// 0x0044 ( 0x0004
	unsigned long                                      IsHeadShot:1;                                     		// 0x0048 ( 0x0004 [0x00000001]
	unsigned long                                      IsAimShot:1;                                      		// 0x0048 ( 0x0004 [0x00000002]
	int                                                NumKillSuccession;                                		// 0x004C ( 0x0004
	unsigned long                                      Cached:1;                                         		// 0x0050 ( 0x0004 [0x00000001]
	float                                              CacheFontSize;                                    		// 0x0054 ( 0x0004
	float                                              CacheHeight;                                      		// 0x0058 ( 0x0004
	float                                              CacheTotalWidth;                                  		// 0x005C ( 0x0004
	float                                              CacheKillerNameWidth;                             		// 0x0060 ( 0x0004
	float                                              CacheKillerNameHeight;                            		// 0x0064 ( 0x0004
	float                                              CacheVictimNameWidth;                             		// 0x0068 ( 0x0004
	float                                              CacheVictimNameHeight;                            		// 0x006C ( 0x0004
	float                                              CacheImageWidth;                                  		// 0x0070 ( 0x0004
	float                                              CacheImageHeight;                                 		// 0x0074 ( 0x0004
	float                                              CacheKillerNameX1;                                		// 0x0078 ( 0x0004
	float                                              CacheKillerNameX2;                                		// 0x007C ( 0x0004
	float                                              CacheImageX1;                                     		// 0x0080 ( 0x0004
	float                                              CacheImageX2;                                     		// 0x0084 ( 0x0004
	float                                              CacheVictimNameX1;                                		// 0x0088 ( 0x0004
	float                                              CacheVictimNameX2;                                		// 0x008C ( 0x0004
	float                                              CacheHSImageWidth;                                		// 0x0090 ( 0x0004
	float                                              CacheHSImageHeight;                               		// 0x0094 ( 0x0004
	float                                              CacheHSImageX1;                                   		// 0x0098 ( 0x0004
	float                                              CacheHSImageX2;                                   		// 0x009C ( 0x0004
	float                                              CacheKSImageWidth;                                		// 0x00A0 ( 0x0004
	float                                              CacheKSImageHeight;                               		// 0x00A4 ( 0x0004
	float                                              CacheKSImageX1;                                   		// 0x00A8 ( 0x0004
	float                                              CacheKSImageX2;                                   		// 0x00AC ( 0x0004
	float                                              CacheASImageWidth;                                		// 0x00B0 ( 0x0004
	float                                              CacheASImageHeight;                               		// 0x00B4 ( 0x0004
	float                                              CacheASImageX1;                                   		// 0x00B8 ( 0x0004
	float                                              CacheASImageX2;                                   		// 0x00BC ( 0x0004

	// Public Imports
	FKillMessageItem(struct FKillMessageItem const &);
	FKillMessageItem(void);
	~FKillMessageItem(void);
	struct FKillMessageItem &  operator=(struct FKillMessageItem const &);
}; // Size: 0x00C0

// Struct XInterface.HudCDeathmatch.TeamDeathInfo
struct DLL_IMPORT FTeamDeathInfo
{
	int                                                TeamIndex;                                        		// 0x0000 ( 0x0004
	struct FVector                                     Position;                                         		// 0x0004 ( 0x000C
	struct FVector                                     HeadPosition;                                     		// 0x0010 ( 0x000C
	float                                              TimeToRemove;                                     		// 0x001C ( 0x0004
	float                                              TimeToStartFade;                                  		// 0x0020 ( 0x0004
}; // Size: 0x0024

// Struct XInterface.HudCDeathmatch.AmmoSet
struct DLL_IMPORT FAmmoSet
{
	class UMaterial*                                   DigitTexture;                                     		// 0x0000 ( 0x0004
	struct FIntBox                                     TextureCoords[ 0x04 ];                            		// 0x0004 ( 0x0040
	int                                                X2;                                               		// 0x0044 ( 0x0004
	int                                                Y2;                                               		// 0x0048 ( 0x0004
	int                                                XL;                                               		// 0x004C ( 0x0004
	int                                                YL;                                               		// 0x0050 ( 0x0004
	int                                                ExtraOffsetX;                                     		// 0x0054 ( 0x0004
}; // Size: 0x0058

// Struct XInterface.HudCDeathmatch.SkillProperty
struct DLL_IMPORT FSkillProperty
{
	int                                                iState;                                           		// 0x0000 ( 0x0004
	int                                                iSlotPos;                                         		// 0x0004 ( 0x0004
	int                                                iSkillID;                                         		// 0x0008 ( 0x0004
	int                                                iWeaponID;                                        		// 0x000C ( 0x0004
	float                                              fActiveTime;                                      		// 0x0010 ( 0x0004
	unsigned long                                      bDrawedIcon:1;                                    		// 0x0014 ( 0x0004 [0x00000001]
	unsigned long                                      bDrawed:1;                                        		// 0x0014 ( 0x0004 [0x00000002]
	class UMaterial*                                   matIcon;                                          		// 0x0018 ( 0x0004
	struct FSpriteWidget                               wTex[ 0x02 ];                                     		// 0x001C ( 0x0080
}; // Size: 0x009C

// Struct XInterface.UT2MusicManager.PlayListStruct
struct DLL_IMPORT FPlayListStruct
{
	unsigned long                                      bRepeat:1;                                        		// 0x0000 ( 0x0004 [0x00000001][ CPF_Config ]
	unsigned long                                      bShuffle:1;                                       		// 0x0000 ( 0x0004 [0x00000002][ CPF_Config ]
	struct FString                                     Current;                                          		// 0x0004 ( 0x000C[ CPF_Config | CPF_NeedCtorLink ]
	class TArray< struct FString >                     Songs;                                            		// 0x0010 ( 0x000C[ CPF_Config | CPF_NeedCtorLink ]
}; // Size: 0x001C

// Struct XInterface.wHudPart_MinimapBase.CachedSpecialPosInfo
struct DLL_IMPORT FCachedSpecialPosInfo
{
	struct FVector                                     pos;                                              		// 0x0000 ( 0x000C
	class UMaterial*                                   Image;                                            		// 0x000C ( 0x0004
	int                                                Index;                                            		// 0x0010 ( 0x0004
	unsigned long                                      IsDraw:1;                                         		// 0x0014 ( 0x0004 [0x00000001]
}; // Size: 0x0018

// Struct XInterface.wHudPart_MinimapBase.MinimapDeadInfo
struct DLL_IMPORT FMinimapDeadInfo
{
	int                                                TeamIndex;                                        		// 0x0000 ( 0x0004
	struct FVector                                     Location;                                         		// 0x0004 ( 0x000C
	float                                              TimeToRemove;                                     		// 0x0010 ( 0x0004
}; // Size: 0x0014

// Struct XInterface.wHudPart_DisplayQuest.SQuest
struct DLL_IMPORT FSQuest
{
	int                                                iCurProgress;                                     		// 0x0000 ( 0x0004
	int                                                imaxProgress;                                     		// 0x0004 ( 0x0004
	float                                              fStartTime;                                       		// 0x0008 ( 0x0004
	float                                              fEndTime;                                         		// 0x000C ( 0x0004
	float                                              fLifeTime;                                        		// 0x0010 ( 0x0004
	unsigned long                                      bDraw:1;                                          		// 0x0014 ( 0x0004 [0x00000001]
	struct FString                                     MissionDesc;                                      		// 0x0018 ( 0x000C[ CPF_NeedCtorLink ]
	unsigned long                                      bPlaySound:1;                                     		// 0x0024 ( 0x0004 [0x00000001]
}; // Size: 0x0028

// Struct XInterface.xScoreBoardTutorial.stTutorialContent
struct DLL_IMPORT FstTutorialContent
{
	unsigned long                                      bCompleted:1;                                     		// 0x0000 ( 0x0004 [0x00000001]
	int                                                iGoal;                                            		// 0x0004 ( 0x0004
	int                                                iCurrent;                                         		// 0x0008 ( 0x0004
	int                                                iTutorialID;                                      		// 0x000C ( 0x0004
	struct FString                                     sContents;                                        		// 0x0010 ( 0x000C[ CPF_NeedCtorLink ]
}; // Size: 0x001C

#ifdef _MSC_VER
#pragma pack ( pop )
#endif

