#pragma once
/*
# ======================================================================================== #
# > ArcticCombat SDK
# > Generated By HJSdkGen v1.06b
# ---------------------------------------------------------------------------------------- #
# > Package : Gameplay
# >    File : Gameplay\Gameplay.h
# ======================================================================================== #
*/


/*
# ======================================================================================== #
# > Forward Declarations
# ======================================================================================== #
*/

class UAnimNotify_EjectShell;
class UAnimNotify_ReloadWeapon;
class UAnimNotify_EjectShell_3rd;
class UAnimNotify_EjectShell_Recham;
class ACriticalEventPlus;
class AScriptedController;
class AScriptedSequence;
class UScriptedAction;
class ULatentScriptedAction;
class UAction_PLAYANIM;
class ADrowned;
class UAction_MOVETOPOINT;
class UAction_WAITFORTIMER;
class AActionMessage;
class ASunlight;
class UEFFECT_ICEPALACE_CUPBOARD;
class UEFFECT_CASTLE_MEDIUMROOM;

/*
# ======================================================================================== #
# > Includes
# ======================================================================================== #
*/

#include "Structs.h"
#include "ParamStructs.h"
#include "Classes.h"
