#pragma once
/*
# ======================================================================================== #
# > ArcticCombat SDK
# > Generated By HJSdkGen v1.06b
# ---------------------------------------------------------------------------------------- #
# > Package : -
# >    File : ArcticCombat.h
# ======================================================================================== #
*/
#pragma warning ( disable : 4099 )
#pragma warning ( disable : 4251 )
#pragma warning ( disable : 4273 )
/*
# ======================================================================================== #
# > Includes
# ======================================================================================== #
*/
#undef DrawText
#undef Log

#include "Core\Core.h"
#include "Core\Structs.h"
#include "Core\ParamStructs.h"
#include "Window\Window.h"
#include "Engine\Engine.h"
#include "BTData\BTData.h"
#include "BatteryNet\BatteryNet.h"
#include "WinDrv\WinDrv.h"
#include "IpDrv\IpDrv.h"
#include "Editor\Editor.h"
#include "Fire\Fire.h"
#include "WWeapons_Res\WWeapons_Res.h"
#include "XEffects\XEffects.h"
#include "XInterface\XInterface.h"
#include "GUI2K4\GUI2K4.h"
#include "UWeb\UWeb.h"
#include "Gameplay\Gameplay.h"
#include "BatteryUI\BatteryUI.h"
#include "D3D9Drv\D3D9Drv.h"
#include "UnrealGame\UnrealGame.h"
#include "WGame\WGame.h"
#include "GUIWarfareStyles\GUIWarfareStyles.h"
#include "GUIWarfareControls\GUIWarfareControls.h"
#include "GUIWarfare\GUIWarfare.h"
#include "WWeapons\WWeapons.h"
#include "XWeapons\XWeapons.h"
#include "WMission\WMission.h"
#include "ALAudio\ALAudio.h"
#include "Names.h"
#include "InputNames.h"
#include "Bones.h"
#include "HShieldManager.h"

#define Log CLog::GetPtr()
/*
# ======================================================================================== #
# > Libs
# ======================================================================================== #
*/

#pragma comment ( lib, "Window.lib" )
#pragma comment ( lib, "Core.lib" )
#pragma comment ( lib, "Engine.lib" )
#pragma comment ( lib, "BTData.lib" )
#pragma comment ( lib, "BatteryNet.lib" )
#pragma comment ( lib, "WinDrv.lib" )
#pragma comment ( lib, "IpDrv.lib" )
#pragma comment ( lib, "Editor.lib" )
#pragma comment ( lib, "Fire.lib" )
#pragma comment ( lib, "XInterface.lib" )
#pragma comment ( lib, "UWeb.lib" )
#pragma comment ( lib, "D3D9Drv.lib" )
#pragma comment ( lib, "BatteryUI.lib" )
#pragma comment ( lib, "WGame.lib" )
#pragma comment ( lib, "ALAudio.lib" )
