#pragma once
/*
# ======================================================================================== #
# > ArcticCombat SDK
# > Generated By HJSdkGen v1.06b
# ---------------------------------------------------------------------------------------- #
# > Package : XEffects
# >    File : Classes.h
# ======================================================================================== #
*/

#ifdef _MSC_VER
#pragma pack ( push, 4 )
#endif


/*
# ======================================================================================== #
# > Enums
# ======================================================================================== #
*/

// Enum XEffects.xPawnGibGroup.EGibType
enum EGibType
{
	EGT_Arm_L                                          = 0,
	EGT_Arm_R                                          = 1,
	EGT_Leg_L                                          = 2,
	EGT_Leg_R                                          = 3,
	EGT_Head                                           = 4,
	EGT_Body                                           = 5,
	EGT_Mix                                            = 6,
	EGT_None                                           = 7
};


/*
# ======================================================================================== #
# > Classes
# ======================================================================================== #
*/

// Class XEffects.XWFX_Artillery_explosion
class DLL_IMPORT AXWFX_Artillery_explosion : public AEmitter
{
public:

	// UScript Functions
	 void                      PostBeginPlay (  );                               		// [ FUNC_Simulated ] XEffects.XWFX_Artillery_explosion.PostBeginPlay
}; // Size: 0x0000

// Class XEffects.WFX_ArtilleryTrailSmoke
class DLL_IMPORT AWFX_ArtilleryTrailSmoke : public AEmitter
{
public:
}; // Size: 0x0000

// Class XEffects.RocketCorona
class DLL_IMPORT ARocketCorona : public AEffects
{
public:
}; // Size: 0x0000

// Class XEffects.xScorch
class DLL_IMPORT AxScorch : public AProjector
{
public:
	float                                              Lifetime;                                         		// 0x0558 ( 0x0004 ) [ CPF_Edit ]
	float                                              PushBack;                                         		// 0x055C ( 0x0004 ) [ CPF_Edit ]
	unsigned long                                      RandomOrient:1;                                   		// 0x0560 ( 0x0004 )  [0x00000001][ CPF_Edit ]

	// UScript Functions
	 void                      PostBeginPlay (  );                               		//  XEffects.xScorch.PostBeginPlay
	 void                      eventPreBeginPlay (  );                           		// [ FUNC_Event ] XEffects.xScorch.PreBeginPlay
}; // Size: 0x000C

// Class XEffects.RocketMark
class DLL_IMPORT ARocketMark : public AxScorch
{
public:

	// UScript Functions
	 void                      PostBeginPlay (  );                               		//  XEffects.RocketMark.PostBeginPlay
}; // Size: 0x0000

// Class XEffects.XWFX_SD_Bomb_explosion
class DLL_IMPORT AXWFX_SD_Bomb_explosion : public AEmitter
{
public:

	// UScript Functions
	 void                      PostBeginPlay (  );                               		// [ FUNC_Simulated ] XEffects.XWFX_SD_Bomb_explosion.PostBeginPlay
}; // Size: 0x0000

// Class XEffects.XWFX_Grenade_explosion
class DLL_IMPORT AXWFX_Grenade_explosion : public AEmitter
{
public:

	// UScript Functions
	 void                      PostBeginPlay (  );                               		// [ FUNC_Simulated ] XEffects.XWFX_Grenade_explosion.PostBeginPlay
}; // Size: 0x0000

// Class XEffects.XWFX_Grenade_explosion_dirt
class DLL_IMPORT AXWFX_Grenade_explosion_dirt : public AEmitter
{
public:

	// UScript Functions
	 void                      PostBeginPlay (  );                               		// [ FUNC_Simulated ] XEffects.XWFX_Grenade_explosion_dirt.PostBeginPlay
}; // Size: 0x0000

// Class XEffects.XWFX_Grenade_explosion_grass
class DLL_IMPORT AXWFX_Grenade_explosion_grass : public AEmitter
{
public:

	// UScript Functions
	 void                      PostBeginPlay (  );                               		// [ FUNC_Simulated ] XEffects.XWFX_Grenade_explosion_grass.PostBeginPlay
}; // Size: 0x0000

// Class XEffects.XWFX_Grenade_explosion_metal
class DLL_IMPORT AXWFX_Grenade_explosion_metal : public AEmitter
{
public:

	// UScript Functions
	 void                      PostBeginPlay (  );                               		// [ FUNC_Simulated ] XEffects.XWFX_Grenade_explosion_metal.PostBeginPlay
}; // Size: 0x0000

// Class XEffects.XWFX_Grenade_explosion_snow
class DLL_IMPORT AXWFX_Grenade_explosion_snow : public AEmitter
{
public:

	// UScript Functions
	 void                      PostBeginPlay (  );                               		// [ FUNC_Simulated ] XEffects.XWFX_Grenade_explosion_snow.PostBeginPlay
}; // Size: 0x0000

// Class XEffects.XWFX_Grenade_explosion_water
class DLL_IMPORT AXWFX_Grenade_explosion_water : public AEmitter
{
public:

	// UScript Functions
	 void                      PostBeginPlay (  );                               		// [ FUNC_Simulated ] XEffects.XWFX_Grenade_explosion_water.PostBeginPlay
}; // Size: 0x0000

// Class XEffects.XWFX_Grenade_explosion_wood
class DLL_IMPORT AXWFX_Grenade_explosion_wood : public AEmitter
{
public:

	// UScript Functions
	 void                      PostBeginPlay (  );                               		// [ FUNC_Simulated ] XEffects.XWFX_Grenade_explosion_wood.PostBeginPlay
}; // Size: 0x0000

// Class XEffects.WFX_RocketTrailSmoke
class DLL_IMPORT AWFX_RocketTrailSmoke : public AEmitter
{
public:
}; // Size: 0x0000

// Class XEffects.XWFX_Time_C4_explosion
class DLL_IMPORT AXWFX_Time_C4_explosion : public AEmitter
{
public:

	// UScript Functions
	 void                      PostBeginPlay (  );                               		// [ FUNC_Simulated ] XEffects.XWFX_Time_C4_explosion.PostBeginPlay
}; // Size: 0x0000

// Class XEffects.XWFX_Stun_explosion
class DLL_IMPORT AXWFX_Stun_explosion : public AEmitter
{
public:

	// UScript Functions
	 void                      PostBeginPlay (  );                               		// [ FUNC_Simulated ] XEffects.XWFX_Stun_explosion.PostBeginPlay
}; // Size: 0x0000

// Class XEffects.WFX_PinpointBomb_redmark
class DLL_IMPORT AWFX_PinpointBomb_redmark : public AEmitter
{
public:
}; // Size: 0x0000

// Class XEffects.XWFX_Grenade_smoke
class DLL_IMPORT AXWFX_Grenade_smoke : public AEmitter
{
public:

	// UScript Functions
	 void                      PostBeginPlay (  );                               		// [ FUNC_Simulated ] XEffects.XWFX_Grenade_smoke.PostBeginPlay
}; // Size: 0x0000

// Class XEffects.HitEffect_heli_attack_hit
class DLL_IMPORT AHitEffect_heli_attack_hit : public AEmitter
{
public:
}; // Size: 0x0000

// Class XEffects.WFX_HeliTrailSmoke
class DLL_IMPORT AWFX_HeliTrailSmoke : public AEmitter
{
public:
}; // Size: 0x0000

// Class XEffects.HitEffect_heli_attack_BulletHole
class DLL_IMPORT AHitEffect_heli_attack_BulletHole : public AxScorch
{
public:

	// UScript Functions
	 void                      PostBeginPlay (  );                               		//  XEffects.HitEffect_heli_attack_BulletHole.PostBeginPlay
}; // Size: 0x0000

// Class XEffects.WFX_HeliRocketSmoke
class DLL_IMPORT AWFX_HeliRocketSmoke : public AEmitter
{
public:
}; // Size: 0x0000

// Class XEffects.RocketMark_gr
class DLL_IMPORT ARocketMark_gr : public AxScorch
{
public:

	// UScript Functions
	 void                      PostBeginPlay (  );                               		//  XEffects.RocketMark_gr.PostBeginPlay
}; // Size: 0x0000

// Class XEffects.XWFX_IncGrenade_explosion
class DLL_IMPORT AXWFX_IncGrenade_explosion : public AEmitter
{
public:

	// UScript Functions
	 void                      PostBeginPlay (  );                               		// [ FUNC_Simulated ] XEffects.XWFX_IncGrenade_explosion.PostBeginPlay
}; // Size: 0x0000

// Class XEffects.XWFX_IncGrenade_Flame_Ally
class DLL_IMPORT AXWFX_IncGrenade_Flame_Ally : public AEmitter
{
public:

	// UScript Functions
	 void                      eventTick ( float DeltaTime );                    		// [ FUNC_Simulated | FUNC_Event ] XEffects.XWFX_IncGrenade_Flame_Ally.Tick
	 void                      PostBeginPlay (  );                               		// [ FUNC_Simulated ] XEffects.XWFX_IncGrenade_Flame_Ally.PostBeginPlay
}; // Size: 0x0000

// Class XEffects.XWFX_IncGrenade_Flame_Enemy
class DLL_IMPORT AXWFX_IncGrenade_Flame_Enemy : public AEmitter
{
public:

	// UScript Functions
	 void                      eventTick ( float DeltaTime );                    		// [ FUNC_Simulated | FUNC_Event ] XEffects.XWFX_IncGrenade_Flame_Enemy.Tick
	 void                      PostBeginPlay (  );                               		// [ FUNC_Simulated ] XEffects.XWFX_IncGrenade_Flame_Enemy.PostBeginPlay
}; // Size: 0x0000

// Class XEffects.XWFX_SplitGrenade
class DLL_IMPORT AXWFX_SplitGrenade : public AEmitter
{
public:

	// UScript Functions
	 void                      PostBeginPlay (  );                               		// [ FUNC_Simulated ] XEffects.XWFX_SplitGrenade.PostBeginPlay
}; // Size: 0x0000

// Class XEffects.XWFX_SplitGndFragment_explo
class DLL_IMPORT AXWFX_SplitGndFragment_explo : public AEmitter
{
public:

	// UScript Functions
	 void                      PostBeginPlay (  );                               		// [ FUNC_Simulated ] XEffects.XWFX_SplitGndFragment_explo.PostBeginPlay
}; // Size: 0x0000

// Class XEffects.WFX_PinpointBombTrailSmoke
class DLL_IMPORT AWFX_PinpointBombTrailSmoke : public AEmitter
{
public:
}; // Size: 0x0000

// Class XEffects.Event_Cash_Gacha_XMAS_GR_mark_01
class DLL_IMPORT AEvent_Cash_Gacha_XMAS_GR_mark_01 : public AxScorch
{
public:

	// UScript Functions
	 void                      PostBeginPlay (  );                               		//  XEffects.Event_Cash_Gacha_XMAS_GR_mark_01.PostBeginPlay
}; // Size: 0x0000

// Class XEffects.xPawnGibGroup
class DLL_IMPORT UxPawnGibGroup : public UObject
{
public:
	class TArray< class UClass* >                      Gibs;                                             		// 0x002C ( 0x000C ) [ CPF_Edit | CPF_NeedCtorLink ]
	class UClass*                                      BloodHitClass;                                    		// 0x0038 ( 0x0004 ) 
	class UClass*                                      BloodHitHeadshotClass;                            		// 0x003C ( 0x0004 ) 
	class UClass*                                      BloodHitClass_01;                                 		// 0x0040 ( 0x0004 ) 
	class UClass*                                      BloodHitClass_02;                                 		// 0x0044 ( 0x0004 ) 
	class UClass*                                      Teen_BloodHitClass;                               		// 0x0048 ( 0x0004 ) 
	class UClass*                                      Teen_BloodHitHeadshotClass;                       		// 0x004C ( 0x0004 ) 
	class UClass*                                      Teen_BloodHitClass_01;                            		// 0x0050 ( 0x0004 ) 
	class UClass*                                      Teen_BloodHitClass_02;                            		// 0x0054 ( 0x0004 ) 
	class UClass*                                      BloodGibClass;                                    		// 0x0058 ( 0x0004 ) 
	class UClass*                                      BloodEmitClass;                                   		// 0x005C ( 0x0004 ) 
	class UClass*                                      HelicopterHitClass;                               		// 0x0060 ( 0x0004 ) 
	class UClass*                                      IdentificationFriendClass;                        		// 0x0064 ( 0x0004 ) 
	class USound*                                      GibSounds;                                        		// 0x0068 ( 0x0004 ) 

	// UScript Functions
	 class USound*             GibSound (  );                                    		//  XEffects.xPawnGibGroup.GibSound
	 class UClass*             GetBloodEmitClass (  );                           		//  XEffects.xPawnGibGroup.GetBloodEmitClass
	 class UClass*             GetGibClass ( unsigned char gibType );            		//  XEffects.xPawnGibGroup.GetGibClass
	 void                      PrecacheContent ( class ALevelInfo* Level );      		//  XEffects.xPawnGibGroup.PrecacheContent
}; // Size: 0x0040

// Class XEffects.Gib
class DLL_IMPORT AGib : public AActor
{
public:
	class UClass*                                      GibGroupClass;                                    		// 0x03C8 ( 0x0004 ) 
	class UClass*                                      TrailClass;                                       		// 0x03CC ( 0x0004 ) [ CPF_Edit ]
	class AwEmitter*                                   Trail;                                            		// 0x03D0 ( 0x0004 ) [ CPF_Edit ]
	float                                              DampenFactor;                                     		// 0x03D4 ( 0x0004 ) [ CPF_Edit ]
	class USound*                                      HitSounds;                                        		// 0x03D8 ( 0x0004 ) 
	unsigned long                                      bFlaming:1;                                       		// 0x03DC ( 0x0004 )  [0x00000001]
	class UClass*                                      GibBloodClass;                                    		// 0x03E0 ( 0x0004 ) 

	// UScript Functions
	 void                      SetTeam ( struct FString strSTMeshName );         		// [ FUNC_Simulated ] XEffects.Gib.SetTeam
	 void                      SpawnTrail (  );                                  		// [ FUNC_Simulated ] XEffects.Gib.SpawnTrail
	 void                      HitWall ( struct FVector HitNormal, class AActor* Wall, class UMaterial* HitMaterial );		// [ FUNC_Simulated ] XEffects.Gib.HitWall
	 void                      Landed ( struct FVector HitNormal );              		// [ FUNC_Simulated ] XEffects.Gib.Landed
	 void                      RandSpin ( float spinRate );                      		// [ FUNC_Final | FUNC_Simulated ] XEffects.Gib.RandSpin
	 void                      Destroyed (  );                                   		// [ FUNC_Simulated ] XEffects.Gib.Destroyed
}; // Size: 0x001C

// Class XEffects.GibArmL
class DLL_IMPORT AGibArmL : public AGib
{
public:

	// UScript Functions
	 void                      SetTeam ( struct FString strSTMeshName );         		// [ FUNC_Simulated ] XEffects.GibArmL.SetTeam
}; // Size: 0x0000

// Class XEffects.GibArmR
class DLL_IMPORT AGibArmR : public AGib
{
public:

	// UScript Functions
	 void                      SetTeam ( struct FString strSTMeshName );         		// [ FUNC_Simulated ] XEffects.GibArmR.SetTeam
}; // Size: 0x0000

// Class XEffects.GibLegL
class DLL_IMPORT AGibLegL : public AGib
{
public:

	// UScript Functions
	 void                      SetTeam ( struct FString strSTMeshName );         		// [ FUNC_Simulated ] XEffects.GibLegL.SetTeam
}; // Size: 0x0000

// Class XEffects.GibLegR
class DLL_IMPORT AGibLegR : public AGib
{
public:

	// UScript Functions
	 void                      SetTeam ( struct FString strSTMeshName );         		// [ FUNC_Simulated ] XEffects.GibLegR.SetTeam
}; // Size: 0x0000

// Class XEffects.GibHead
class DLL_IMPORT AGibHead : public AGib
{
public:

	// UScript Functions
	 void                      SetTeam ( struct FString strSTMeshName );         		// [ FUNC_Simulated ] XEffects.GibHead.SetTeam
}; // Size: 0x0000

// Class XEffects.GibOrganicRedTorso
class DLL_IMPORT AGibOrganicRedTorso : public AGib
{
public:
}; // Size: 0x0000

// Class XEffects.BloodSpurt
class DLL_IMPORT ABloodSpurt : public AwEmitter
{
public:
	class UClass*                                      BloodDecalClass;                                  		// 0x05B8 ( 0x0004 ) 
	class UTexture*                                    Splats[ 0x04 ];                                   		// 0x05BC ( 0x0010 ) 
	struct FVector                                     HitDir;                                           		// 0x05CC ( 0x000C ) [ CPF_Net ]
	unsigned long                                      bMustShow:1;                                      		// 0x05D8 ( 0x0004 )  [0x00000001][ CPF_Net ]
	class UClass*                                      HitEffectClass;                                   		// 0x05DC ( 0x0004 ) 

	// UScript Functions
	 void                      PrecacheContent ( class ALevelInfo* Level );      		//  XEffects.BloodSpurt.PrecacheContent
	 void                      WallSplat (  );                                   		// [ FUNC_Simulated ] XEffects.BloodSpurt.WallSplat
	 void                      PostNetBeginPlay (  );                            		// [ FUNC_Simulated ] XEffects.BloodSpurt.PostNetBeginPlay
}; // Size: 0x0028

// Class XEffects.BloodSpurt_Headshot
class DLL_IMPORT ABloodSpurt_Headshot : public ABloodSpurt
{
public:
}; // Size: 0x0000

// Class XEffects.BloodSmallHit_A
class DLL_IMPORT ABloodSmallHit_A : public ABloodSpurt
{
public:

	// UScript Functions
	 void                      PostNetBeginPlay (  );                            		// [ FUNC_Simulated ] XEffects.BloodSmallHit_A.PostNetBeginPlay
}; // Size: 0x0000

// Class XEffects.BloodSmallHit_B
class DLL_IMPORT ABloodSmallHit_B : public ABloodSpurt
{
public:

	// UScript Functions
	 void                      PostNetBeginPlay (  );                            		// [ FUNC_Simulated ] XEffects.BloodSmallHit_B.PostNetBeginPlay
}; // Size: 0x0000

// Class XEffects.BloodSpurt_Teen
class DLL_IMPORT ABloodSpurt_Teen : public AwEmitter
{
public:
	class UClass*                                      BloodDecalClass;                                  		// 0x05B8 ( 0x0004 ) 
	class UTexture*                                    Splats[ 0x04 ];                                   		// 0x05BC ( 0x0010 ) 
	struct FVector                                     HitDir;                                           		// 0x05CC ( 0x000C ) [ CPF_Net ]
	unsigned long                                      bMustShow:1;                                      		// 0x05D8 ( 0x0004 )  [0x00000001][ CPF_Net ]
	class UClass*                                      HitEffectClass;                                   		// 0x05DC ( 0x0004 ) 

	// UScript Functions
	 void                      PrecacheContent ( class ALevelInfo* Level );      		//  XEffects.BloodSpurt_Teen.PrecacheContent
	 void                      WallSplat (  );                                   		// [ FUNC_Simulated ] XEffects.BloodSpurt_Teen.WallSplat
	 void                      PostNetBeginPlay (  );                            		// [ FUNC_Simulated ] XEffects.BloodSpurt_Teen.PostNetBeginPlay
}; // Size: 0x0028

// Class XEffects.BloodSpurt_Headshot_Teen
class DLL_IMPORT ABloodSpurt_Headshot_Teen : public ABloodSpurt_Teen
{
public:
}; // Size: 0x0000

// Class XEffects.BloodExplosion
class DLL_IMPORT ABloodExplosion : public AwEmitter
{
public:
}; // Size: 0x0000

// Class XEffects.BloodJet
class DLL_IMPORT ABloodJet : public AwEmitter
{
public:
	class UClass*                                      SplatterClass;                                    		// 0x05B8 ( 0x0004 ) 

	// UScript Functions
	 void                      WallSplat (  );                                   		// [ FUNC_Simulated ] XEffects.BloodJet.WallSplat
	 void                      PostNetBeginPlay (  );                            		// [ FUNC_Simulated ] XEffects.BloodJet.PostNetBeginPlay
	 void                      Timer (  );                                       		// [ FUNC_Simulated ] XEffects.BloodJet.Timer
}; // Size: 0x0004

// Class XEffects.HelicopterHitEffect
class DLL_IMPORT AHelicopterHitEffect : public AwEmitter
{
public:
	class UClass*                                      HitEffectClass;                                   		// 0x05B8 ( 0x0004 ) 

	// UScript Functions
	 void                      PostNetBeginPlay (  );                            		// [ FUNC_Simulated ] XEffects.HelicopterHitEffect.PostNetBeginPlay
}; // Size: 0x0004

// Class XEffects.Charater_FX_Strobo_light_Blue
class DLL_IMPORT ACharater_FX_Strobo_light_Blue : public AEmitter
{
public:
}; // Size: 0x0000

// Class XEffects.HitFlameBig
class DLL_IMPORT AHitFlameBig : public AwEmitter
{
public:

	// UScript Functions
	 void                      PostNetBeginPlay (  );                            		// [ FUNC_Simulated ] XEffects.HitFlameBig.PostNetBeginPlay
	 void                      Timer (  );                                       		// [ FUNC_Simulated ] XEffects.HitFlameBig.Timer
}; // Size: 0x0000

// Class XEffects.BloodHit_spurt
class DLL_IMPORT ABloodHit_spurt : public ABloodSpurt
{
public:

	// UScript Functions
	 void                      WallSplat (  );                                   		// [ FUNC_Simulated ] XEffects.BloodHit_spurt.WallSplat
	 void                      PostNetBeginPlay (  );                            		// [ FUNC_Simulated ] XEffects.BloodHit_spurt.PostNetBeginPlay
}; // Size: 0x0000

// Class XEffects.BloodSplatter
class DLL_IMPORT ABloodSplatter : public AxScorch
{
public:
	class UTexture*                                    Splats[ 0x04 ];                                   		// 0x0564 ( 0x0010 ) 

	// UScript Functions
	 void                      PostBeginPlay (  );                               		// [ FUNC_Simulated ] XEffects.BloodSplatter.PostBeginPlay
}; // Size: 0x0010

// Class XEffects.HitEffect_Blood
class DLL_IMPORT AHitEffect_Blood : public AEffects
{
public:
	class USound*                                      ImpactSound;                                      		// 0x03C8 ( 0x0004 ) 

	// UScript Functions
	 void                      SpawnEffects (  );                                		// [ FUNC_Simulated ] XEffects.HitEffect_Blood.SpawnEffects
	 void                      PostNetBeginPlay (  );                            		// [ FUNC_Simulated ] XEffects.HitEffect_Blood.PostNetBeginPlay
}; // Size: 0x0004

// Class XEffects.BloodSplatter_Teen
class DLL_IMPORT ABloodSplatter_Teen : public AxScorch
{
public:
	class UTexture*                                    Splats[ 0x04 ];                                   		// 0x0564 ( 0x0010 ) 

	// UScript Functions
	 void                      PostBeginPlay (  );                               		// [ FUNC_Simulated ] XEffects.BloodSplatter_Teen.PostBeginPlay
}; // Size: 0x0010

// Class XEffects.HitEffect_Teen_Blood
class DLL_IMPORT AHitEffect_Teen_Blood : public AEffects
{
public:
	class USound*                                      ImpactSound;                                      		// 0x03C8 ( 0x0004 ) 

	// UScript Functions
	 void                      SpawnEffects (  );                                		// [ FUNC_Simulated ] XEffects.HitEffect_Teen_Blood.SpawnEffects
	 void                      PostNetBeginPlay (  );                            		// [ FUNC_Simulated ] XEffects.HitEffect_Teen_Blood.PostNetBeginPlay
}; // Size: 0x0004

// Class XEffects.HitEffect_Metal
class DLL_IMPORT AHitEffect_Metal : public AEffects
{
public:
	class USound*                                      ImpactSound;                                      		// 0x03C8 ( 0x0004 ) 

	// UScript Functions
	 void                      SpawnEffects (  );                                		// [ FUNC_Simulated ] XEffects.HitEffect_Metal.SpawnEffects
	 void                      PostNetBeginPlay (  );                            		// [ FUNC_Simulated ] XEffects.HitEffect_Metal.PostNetBeginPlay
}; // Size: 0x0004

// Class XEffects.HitEffect_blood_headshot
class DLL_IMPORT AHitEffect_blood_headshot : public AEffects
{
public:
	class USound*                                      ImpactSound;                                      		// 0x03C8 ( 0x0004 ) 

	// UScript Functions
	 void                      SpawnEffects (  );                                		// [ FUNC_Simulated ] XEffects.HitEffect_blood_headshot.SpawnEffects
	 void                      PostNetBeginPlay (  );                            		// [ FUNC_Simulated ] XEffects.HitEffect_blood_headshot.PostNetBeginPlay
}; // Size: 0x0004

// Class XEffects.HitEffect_teen_blood_headshot
class DLL_IMPORT AHitEffect_teen_blood_headshot : public AEffects
{
public:
	class USound*                                      ImpactSound;                                      		// 0x03C8 ( 0x0004 ) 

	// UScript Functions
	 void                      SpawnEffects (  );                                		// [ FUNC_Simulated ] XEffects.HitEffect_teen_blood_headshot.SpawnEffects
	 void                      PostNetBeginPlay (  );                            		// [ FUNC_Simulated ] XEffects.HitEffect_teen_blood_headshot.PostNetBeginPlay
}; // Size: 0x0004

// Class XEffects.HitEffect_Blood_hit
class DLL_IMPORT AHitEffect_Blood_hit : public AEmitter
{
public:
}; // Size: 0x0000

// Class XEffects.HitEffect_blood_headshot_hit
class DLL_IMPORT AHitEffect_blood_headshot_hit : public AEmitter
{
public:
}; // Size: 0x0000

// Class XEffects.HitEffect_blood_spurt
class DLL_IMPORT AHitEffect_blood_spurt : public AEffects
{
public:
	class USound*                                      ImpactSound;                                      		// 0x03C8 ( 0x0004 ) 

	// UScript Functions
	 void                      SpawnEffects (  );                                		// [ FUNC_Simulated ] XEffects.HitEffect_blood_spurt.SpawnEffects
	 void                      PostNetBeginPlay (  );                            		// [ FUNC_Simulated ] XEffects.HitEffect_blood_spurt.PostNetBeginPlay
}; // Size: 0x0004

// Class XEffects.HitEffect_metal_BulletHole
class DLL_IMPORT AHitEffect_metal_BulletHole : public AxScorch
{
public:

	// UScript Functions
	 void                      PostBeginPlay (  );                               		//  XEffects.HitEffect_metal_BulletHole.PostBeginPlay
}; // Size: 0x0000

// Class XEffects.HitEffect_Metal_hit
class DLL_IMPORT AHitEffect_Metal_hit : public AEmitter
{
public:
}; // Size: 0x0000

// Class XEffects.HitEffect_teen_blood_headshot_hit
class DLL_IMPORT AHitEffect_teen_blood_headshot_hit : public AEmitter
{
public:
}; // Size: 0x0000

// Class XEffects.HitEffect_Teen_blood_hit
class DLL_IMPORT AHitEffect_Teen_blood_hit : public AEmitter
{
public:
}; // Size: 0x0000

// Class XEffects.HitEffect_Concrete_BulletHole
class DLL_IMPORT AHitEffect_Concrete_BulletHole : public AxScorch
{
public:

	// UScript Functions
	 void                      PostBeginPlay (  );                               		//  XEffects.HitEffect_Concrete_BulletHole.PostBeginPlay
}; // Size: 0x0000

// Class XEffects.HitEffect_blood_spurt_hit
class DLL_IMPORT AHitEffect_blood_spurt_hit : public AEmitter
{
public:
}; // Size: 0x0000

// Class XEffects.Warfare_Tracer
class DLL_IMPORT AWarfare_Tracer : public AEmitter
{
public:

	// UScript Functions
	 void                      SpawnParticle ( int Amount );                     		// [ FUNC_Simulated ] XEffects.Warfare_Tracer.SpawnParticle
}; // Size: 0x0000

// Class XEffects.HitEffect_Default
class DLL_IMPORT AHitEffect_Default : public AEffects
{
public:
	class USound*                                      ImpactSound;                                      		// 0x03C8 ( 0x0004 ) 

	// UScript Functions
	 void                      SpawnEffects (  );                                		// [ FUNC_Simulated ] XEffects.HitEffect_Default.SpawnEffects
	 void                      PostNetBeginPlay (  );                            		// [ FUNC_Simulated ] XEffects.HitEffect_Default.PostNetBeginPlay
}; // Size: 0x0004

// Class XEffects.HitEffect_ETC
class DLL_IMPORT AHitEffect_ETC : public AEffects
{
public:
	class USound*                                      ImpactSound;                                      		// 0x03C8 ( 0x0004 ) 

	// UScript Functions
	 void                      SpawnEffects (  );                                		// [ FUNC_Simulated ] XEffects.HitEffect_ETC.SpawnEffects
	 void                      PostNetBeginPlay (  );                            		// [ FUNC_Simulated ] XEffects.HitEffect_ETC.PostNetBeginPlay
}; // Size: 0x0004

// Class XEffects.HitEffect_rock
class DLL_IMPORT AHitEffect_rock : public AEffects
{
public:
	class USound*                                      ImpactSound;                                      		// 0x03C8 ( 0x0004 ) 

	// UScript Functions
	 void                      SpawnEffects (  );                                		// [ FUNC_Simulated ] XEffects.HitEffect_rock.SpawnEffects
	 void                      PostNetBeginPlay (  );                            		// [ FUNC_Simulated ] XEffects.HitEffect_rock.PostNetBeginPlay
}; // Size: 0x0004

// Class XEffects.HitEffect_brick
class DLL_IMPORT AHitEffect_brick : public AEffects
{
public:
	class USound*                                      ImpactSound;                                      		// 0x03C8 ( 0x0004 ) 

	// UScript Functions
	 void                      SpawnEffects (  );                                		// [ FUNC_Simulated ] XEffects.HitEffect_brick.SpawnEffects
	 void                      PostNetBeginPlay (  );                            		// [ FUNC_Simulated ] XEffects.HitEffect_brick.PostNetBeginPlay
}; // Size: 0x0004

// Class XEffects.HitEffect_Concrete
class DLL_IMPORT AHitEffect_Concrete : public AEffects
{
public:
	class USound*                                      ImpactSound;                                      		// 0x03C8 ( 0x0004 ) 

	// UScript Functions
	 void                      SpawnEffects (  );                                		// [ FUNC_Simulated ] XEffects.HitEffect_Concrete.SpawnEffects
	 void                      PostNetBeginPlay (  );                            		// [ FUNC_Simulated ] XEffects.HitEffect_Concrete.PostNetBeginPlay
}; // Size: 0x0004

// Class XEffects.HitEffect_Dirt
class DLL_IMPORT AHitEffect_Dirt : public AEffects
{
public:
	class USound*                                      ImpactSound;                                      		// 0x03C8 ( 0x0004 ) 

	// UScript Functions
	 void                      SpawnEffects (  );                                		// [ FUNC_Simulated ] XEffects.HitEffect_Dirt.SpawnEffects
	 void                      PostNetBeginPlay (  );                            		// [ FUNC_Simulated ] XEffects.HitEffect_Dirt.PostNetBeginPlay
}; // Size: 0x0004

// Class XEffects.HitEffect_Metal_PT
class DLL_IMPORT AHitEffect_Metal_PT : public AEffects
{
public:
	class USound*                                      ImpactSound;                                      		// 0x03C8 ( 0x0004 ) 

	// UScript Functions
	 void                      SpawnEffects (  );                                		// [ FUNC_Simulated ] XEffects.HitEffect_Metal_PT.SpawnEffects
	 void                      PostNetBeginPlay (  );                            		// [ FUNC_Simulated ] XEffects.HitEffect_Metal_PT.PostNetBeginPlay
}; // Size: 0x0004

// Class XEffects.HitEffect_Wood
class DLL_IMPORT AHitEffect_Wood : public AEffects
{
public:
	class USound*                                      ImpactSound;                                      		// 0x03C8 ( 0x0004 ) 

	// UScript Functions
	 void                      SpawnEffects (  );                                		// [ FUNC_Simulated ] XEffects.HitEffect_Wood.SpawnEffects
	 void                      PostNetBeginPlay (  );                            		// [ FUNC_Simulated ] XEffects.HitEffect_Wood.PostNetBeginPlay
}; // Size: 0x0004

// Class XEffects.HitEffect_plant
class DLL_IMPORT AHitEffect_plant : public AEffects
{
public:
	class USound*                                      ImpactSound;                                      		// 0x03C8 ( 0x0004 ) 

	// UScript Functions
	 void                      SpawnEffects (  );                                		// [ FUNC_Simulated ] XEffects.HitEffect_plant.SpawnEffects
	 void                      PostNetBeginPlay (  );                            		// [ FUNC_Simulated ] XEffects.HitEffect_plant.PostNetBeginPlay
}; // Size: 0x0004

// Class XEffects.HitEffect_flesh
class DLL_IMPORT AHitEffect_flesh : public AEffects
{
public:
	class USound*                                      ImpactSound;                                      		// 0x03C8 ( 0x0004 ) 

	// UScript Functions
	 void                      SpawnEffects (  );                                		// [ FUNC_Simulated ] XEffects.HitEffect_flesh.SpawnEffects
	 void                      PostNetBeginPlay (  );                            		// [ FUNC_Simulated ] XEffects.HitEffect_flesh.PostNetBeginPlay
}; // Size: 0x0004

// Class XEffects.HitEffect_snow
class DLL_IMPORT AHitEffect_snow : public AEffects
{
public:
	class USound*                                      ImpactSound;                                      		// 0x03C8 ( 0x0004 ) 

	// UScript Functions
	 void                      SpawnEffects (  );                                		// [ FUNC_Simulated ] XEffects.HitEffect_snow.SpawnEffects
	 void                      PostNetBeginPlay (  );                            		// [ FUNC_Simulated ] XEffects.HitEffect_snow.PostNetBeginPlay
}; // Size: 0x0004

// Class XEffects.HitEffect_water
class DLL_IMPORT AHitEffect_water : public AEffects
{
public:
	class USound*                                      ImpactSound;                                      		// 0x03C8 ( 0x0004 ) 

	// UScript Functions
	 void                      SpawnEffects (  );                                		// [ FUNC_Simulated ] XEffects.HitEffect_water.SpawnEffects
	 void                      PostNetBeginPlay (  );                            		// [ FUNC_Simulated ] XEffects.HitEffect_water.PostNetBeginPlay
}; // Size: 0x0004

// Class XEffects.HitEffect_glass
class DLL_IMPORT AHitEffect_glass : public AEffects
{
public:
	class USound*                                      ImpactSound;                                      		// 0x03C8 ( 0x0004 ) 

	// UScript Functions
	 void                      SpawnEffects (  );                                		// [ FUNC_Simulated ] XEffects.HitEffect_glass.SpawnEffects
	 void                      PostNetBeginPlay (  );                            		// [ FUNC_Simulated ] XEffects.HitEffect_glass.PostNetBeginPlay
}; // Size: 0x0004

// Class XEffects.HitEffect_cotton
class DLL_IMPORT AHitEffect_cotton : public AEffects
{
public:
	class USound*                                      ImpactSound;                                      		// 0x03C8 ( 0x0004 ) 

	// UScript Functions
	 void                      SpawnEffects (  );                                		// [ FUNC_Simulated ] XEffects.HitEffect_cotton.SpawnEffects
	 void                      PostNetBeginPlay (  );                            		// [ FUNC_Simulated ] XEffects.HitEffect_cotton.PostNetBeginPlay
}; // Size: 0x0004

// Class XEffects.HitEffect_blood_death
class DLL_IMPORT AHitEffect_blood_death : public AEffects
{
public:
	class USound*                                      ImpactSound;                                      		// 0x03C8 ( 0x0004 ) 

	// UScript Functions
	 void                      SpawnEffects (  );                                		// [ FUNC_Simulated ] XEffects.HitEffect_blood_death.SpawnEffects
	 void                      PostNetBeginPlay (  );                            		// [ FUNC_Simulated ] XEffects.HitEffect_blood_death.PostNetBeginPlay
}; // Size: 0x0004

// Class XEffects.HitEffect_CrackWood
class DLL_IMPORT AHitEffect_CrackWood : public AEffects
{
public:
	class USound*                                      ImpactSound;                                      		// 0x03C8 ( 0x0004 ) 

	// UScript Functions
	 void                      SpawnEffects (  );                                		// [ FUNC_Simulated ] XEffects.HitEffect_CrackWood.SpawnEffects
	 void                      PostNetBeginPlay (  );                            		// [ FUNC_Simulated ] XEffects.HitEffect_CrackWood.PostNetBeginPlay
}; // Size: 0x0004

// Class XEffects.HitEffect_Plastic
class DLL_IMPORT AHitEffect_Plastic : public AEffects
{
public:
	class USound*                                      ImpactSound;                                      		// 0x03C8 ( 0x0004 ) 

	// UScript Functions
	 void                      SpawnEffects (  );                                		// [ FUNC_Simulated ] XEffects.HitEffect_Plastic.SpawnEffects
	 void                      PostNetBeginPlay (  );                            		// [ FUNC_Simulated ] XEffects.HitEffect_Plastic.PostNetBeginPlay
}; // Size: 0x0004

// Class XEffects.HitEffect_Paper
class DLL_IMPORT AHitEffect_Paper : public AEffects
{
public:
	class USound*                                      ImpactSound;                                      		// 0x03C8 ( 0x0004 ) 

	// UScript Functions
	 void                      SpawnEffects (  );                                		// [ FUNC_Simulated ] XEffects.HitEffect_Paper.SpawnEffects
	 void                      PostNetBeginPlay (  );                            		// [ FUNC_Simulated ] XEffects.HitEffect_Paper.PostNetBeginPlay
}; // Size: 0x0004

// Class XEffects.HitEffect_Rubber
class DLL_IMPORT AHitEffect_Rubber : public AEffects
{
public:
	class USound*                                      ImpactSound;                                      		// 0x03C8 ( 0x0004 ) 

	// UScript Functions
	 void                      SpawnEffects (  );                                		// [ FUNC_Simulated ] XEffects.HitEffect_Rubber.SpawnEffects
	 void                      PostNetBeginPlay (  );                            		// [ FUNC_Simulated ] XEffects.HitEffect_Rubber.PostNetBeginPlay
}; // Size: 0x0004

// Class XEffects.HitEffect_Carpet
class DLL_IMPORT AHitEffect_Carpet : public AEffects
{
public:
	class USound*                                      ImpactSound;                                      		// 0x03C8 ( 0x0004 ) 

	// UScript Functions
	 void                      SpawnEffects (  );                                		// [ FUNC_Simulated ] XEffects.HitEffect_Carpet.SpawnEffects
	 void                      PostNetBeginPlay (  );                            		// [ FUNC_Simulated ] XEffects.HitEffect_Carpet.PostNetBeginPlay
}; // Size: 0x0004

// Class XEffects.HitEffect_Leaves
class DLL_IMPORT AHitEffect_Leaves : public AEffects
{
public:
	class USound*                                      ImpactSound;                                      		// 0x03C8 ( 0x0004 ) 

	// UScript Functions
	 void                      SpawnEffects (  );                                		// [ FUNC_Simulated ] XEffects.HitEffect_Leaves.SpawnEffects
	 void                      PostNetBeginPlay (  );                            		// [ FUNC_Simulated ] XEffects.HitEffect_Leaves.PostNetBeginPlay
}; // Size: 0x0004

// Class XEffects.HitEffect_Cloth
class DLL_IMPORT AHitEffect_Cloth : public AEffects
{
public:
	class USound*                                      ImpactSound;                                      		// 0x03C8 ( 0x0004 ) 

	// UScript Functions
	 void                      SpawnEffects (  );                                		// [ FUNC_Simulated ] XEffects.HitEffect_Cloth.SpawnEffects
	 void                      PostNetBeginPlay (  );                            		// [ FUNC_Simulated ] XEffects.HitEffect_Cloth.PostNetBeginPlay
}; // Size: 0x0004

// Class XEffects.HitEffect_Sand
class DLL_IMPORT AHitEffect_Sand : public AEffects
{
public:
	class USound*                                      ImpactSound;                                      		// 0x03C8 ( 0x0004 ) 

	// UScript Functions
	 void                      SpawnEffects (  );                                		// [ FUNC_Simulated ] XEffects.HitEffect_Sand.SpawnEffects
	 void                      PostNetBeginPlay (  );                            		// [ FUNC_Simulated ] XEffects.HitEffect_Sand.PostNetBeginPlay
}; // Size: 0x0004

// Class XEffects.HitEffect_Mud
class DLL_IMPORT AHitEffect_Mud : public AEffects
{
public:
	class USound*                                      ImpactSound;                                      		// 0x03C8 ( 0x0004 ) 

	// UScript Functions
	 void                      SpawnEffects (  );                                		// [ FUNC_Simulated ] XEffects.HitEffect_Mud.SpawnEffects
	 void                      PostNetBeginPlay (  );                            		// [ FUNC_Simulated ] XEffects.HitEffect_Mud.PostNetBeginPlay
}; // Size: 0x0004

// Class XEffects.HitEffect_WaterFoot
class DLL_IMPORT AHitEffect_WaterFoot : public AEffects
{
public:
	class USound*                                      ImpactSound;                                      		// 0x03C8 ( 0x0004 ) 

	// UScript Functions
	 void                      SpawnEffects (  );                                		// [ FUNC_Simulated ] XEffects.HitEffect_WaterFoot.SpawnEffects
	 void                      PostNetBeginPlay (  );                            		// [ FUNC_Simulated ] XEffects.HitEffect_WaterFoot.PostNetBeginPlay
}; // Size: 0x0004

// Class XEffects.HitEffect_water_wall
class DLL_IMPORT AHitEffect_water_wall : public AEffects
{
public:
	class USound*                                      ImpactSound;                                      		// 0x03C8 ( 0x0004 ) 

	// UScript Functions
	 void                      SpawnEffects (  );                                		// [ FUNC_Simulated ] XEffects.HitEffect_water_wall.SpawnEffects
	 void                      PostNetBeginPlay (  );                            		// [ FUNC_Simulated ] XEffects.HitEffect_water_wall.PostNetBeginPlay
}; // Size: 0x0004

// Class XEffects.alien_tankersheld_hit
class DLL_IMPORT Aalien_tankersheld_hit : public AEffects
{
public:
	class USound*                                      ImpactSound;                                      		// 0x03C8 ( 0x0004 ) 

	// UScript Functions
	 void                      SpawnEffects (  );                                		// [ FUNC_Simulated ] XEffects.alien_tankersheld_hit.SpawnEffects
	 void                      PostNetBeginPlay (  );                            		// [ FUNC_Simulated ] XEffects.alien_tankersheld_hit.PostNetBeginPlay
}; // Size: 0x0004

// Class XEffects.HitEffect_rock_BulletHole
class DLL_IMPORT AHitEffect_rock_BulletHole : public AxScorch
{
public:

	// UScript Functions
	 void                      PostBeginPlay (  );                               		//  XEffects.HitEffect_rock_BulletHole.PostBeginPlay
}; // Size: 0x0000

// Class XEffects.HitEffect_rock_hit
class DLL_IMPORT AHitEffect_rock_hit : public AEmitter
{
public:
}; // Size: 0x0000

// Class XEffects.HitEffect_dirt_BulletHole
class DLL_IMPORT AHitEffect_dirt_BulletHole : public AxScorch
{
public:

	// UScript Functions
	 void                      PostBeginPlay (  );                               		//  XEffects.HitEffect_dirt_BulletHole.PostBeginPlay
}; // Size: 0x0000

// Class XEffects.HitEffect_Dirt_hit
class DLL_IMPORT AHitEffect_Dirt_hit : public AEmitter
{
public:
}; // Size: 0x0000

// Class XEffects.alien_tankersheld_hit_BulletHole
class DLL_IMPORT Aalien_tankersheld_hit_BulletHole : public AxScorch
{
public:

	// UScript Functions
	 void                      PostBeginPlay (  );                               		//  XEffects.alien_tankersheld_hit_BulletHole.PostBeginPlay
}; // Size: 0x0000

// Class XEffects.alien_tankersheld_hiteffect
class DLL_IMPORT Aalien_tankersheld_hiteffect : public AEmitter
{
public:
}; // Size: 0x0000

// Class XEffects.HitEffect_ETC_BulletHole
class DLL_IMPORT AHitEffect_ETC_BulletHole : public AxScorch
{
public:

	// UScript Functions
	 void                      PostBeginPlay (  );                               		//  XEffects.HitEffect_ETC_BulletHole.PostBeginPlay
}; // Size: 0x0000

// Class XEffects.HitEffect_ETC_hit
class DLL_IMPORT AHitEffect_ETC_hit : public AEmitter
{
public:
}; // Size: 0x0000

// Class XEffects.HitEffect_water_hit
class DLL_IMPORT AHitEffect_water_hit : public AEmitter
{
public:
}; // Size: 0x0000

// Class XEffects.HitEffect_wood_BulletHole
class DLL_IMPORT AHitEffect_wood_BulletHole : public AxScorch
{
public:

	// UScript Functions
	 void                      PostBeginPlay (  );                               		//  XEffects.HitEffect_wood_BulletHole.PostBeginPlay
}; // Size: 0x0000

// Class XEffects.HitEffect_Wood_hit
class DLL_IMPORT AHitEffect_Wood_hit : public AEmitter
{
public:
}; // Size: 0x0000

// Class XEffects.HitEffect_flesh_BulletHole
class DLL_IMPORT AHitEffect_flesh_BulletHole : public AxScorch
{
public:

	// UScript Functions
	 void                      PostBeginPlay (  );                               		//  XEffects.HitEffect_flesh_BulletHole.PostBeginPlay
}; // Size: 0x0000

// Class XEffects.HitEffect_flesh_hit
class DLL_IMPORT AHitEffect_flesh_hit : public AEmitter
{
public:
}; // Size: 0x0000

// Class XEffects.HitEffect_water_wall_hit
class DLL_IMPORT AHitEffect_water_wall_hit : public AEmitter
{
public:
}; // Size: 0x0000

// Class XEffects.HitEffect_brick_BulletHole
class DLL_IMPORT AHitEffect_brick_BulletHole : public AxScorch
{
public:

	// UScript Functions
	 void                      PostBeginPlay (  );                               		//  XEffects.HitEffect_brick_BulletHole.PostBeginPlay
}; // Size: 0x0000

// Class XEffects.HitEffect_brick_hit
class DLL_IMPORT AHitEffect_brick_hit : public AEmitter
{
public:
}; // Size: 0x0000

// Class XEffects.HitEffect_snow_BulletHole
class DLL_IMPORT AHitEffect_snow_BulletHole : public AxScorch
{
public:

	// UScript Functions
	 void                      PostBeginPlay (  );                               		//  XEffects.HitEffect_snow_BulletHole.PostBeginPlay
}; // Size: 0x0000

// Class XEffects.HitEffect_snow_hit
class DLL_IMPORT AHitEffect_snow_hit : public AEmitter
{
public:
}; // Size: 0x0000

// Class XEffects.HitEffect_glass_BulletHole
class DLL_IMPORT AHitEffect_glass_BulletHole : public AxScorch
{
public:

	// UScript Functions
	 void                      PostBeginPlay (  );                               		//  XEffects.HitEffect_glass_BulletHole.PostBeginPlay
}; // Size: 0x0000

// Class XEffects.HitEffect_glass_hit
class DLL_IMPORT AHitEffect_glass_hit : public AEmitter
{
public:
}; // Size: 0x0000

// Class XEffects.HitEffect_plant_BulletHole
class DLL_IMPORT AHitEffect_plant_BulletHole : public AxScorch
{
public:

	// UScript Functions
	 void                      PostBeginPlay (  );                               		//  XEffects.HitEffect_plant_BulletHole.PostBeginPlay
}; // Size: 0x0000

// Class XEffects.HitEffect_plant_hit
class DLL_IMPORT AHitEffect_plant_hit : public AEmitter
{
public:
}; // Size: 0x0000

// Class XEffects.HitEffect_Concrete_hit
class DLL_IMPORT AHitEffect_Concrete_hit : public AEmitter
{
public:
}; // Size: 0x0000

// Class XEffects.HitEffect_metal_pt_BulletHole
class DLL_IMPORT AHitEffect_metal_pt_BulletHole : public AxScorch
{
public:

	// UScript Functions
	 void                      PostBeginPlay (  );                               		//  XEffects.HitEffect_metal_pt_BulletHole.PostBeginPlay
}; // Size: 0x0000

// Class XEffects.HitEffect_Metal_PT_hit
class DLL_IMPORT AHitEffect_Metal_PT_hit : public AEmitter
{
public:
}; // Size: 0x0000

// Class XEffects.HitEffect_blood_death_hit
class DLL_IMPORT AHitEffect_blood_death_hit : public AEmitter
{
public:
}; // Size: 0x0000

// Class XEffects.HitEffect_cotton_BulletHole
class DLL_IMPORT AHitEffect_cotton_BulletHole : public AxScorch
{
public:

	// UScript Functions
	 void                      PostBeginPlay (  );                               		//  XEffects.HitEffect_cotton_BulletHole.PostBeginPlay
}; // Size: 0x0000

// Class XEffects.HitEffect_cotton_hit
class DLL_IMPORT AHitEffect_cotton_hit : public AEmitter
{
public:
}; // Size: 0x0000

// Class XEffects.BG_FX_dust_sand
class DLL_IMPORT ABG_FX_dust_sand : public AEmitter
{
public:
}; // Size: 0x0000

// Class XEffects.BG_FX_deco_box_paper01
class DLL_IMPORT ABG_FX_deco_box_paper01 : public AEmitter
{
public:
}; // Size: 0x0000

// Class XEffects.BG_FX_dust_sand_large
class DLL_IMPORT ABG_FX_dust_sand_large : public AEmitter
{
public:
}; // Size: 0x0000

// Class XEffects.BG_FX_deco_news_paper
class DLL_IMPORT ABG_FX_deco_news_paper : public AEmitter
{
public:
}; // Size: 0x0000

// Class XEffects.BG_FX_fountain_water_wave
class DLL_IMPORT ABG_FX_fountain_water_wave : public AEmitter
{
public:
}; // Size: 0x0000

// Class XEffects.BG_FX_fountain_water
class DLL_IMPORT ABG_FX_fountain_water : public AEmitter
{
public:
}; // Size: 0x0000

// Class XEffects.BG_FX_large_deco_smoke_burn
class DLL_IMPORT ABG_FX_large_deco_smoke_burn : public AEmitter
{
public:
}; // Size: 0x0000

// Class XEffects.BG_FX_bonfire
class DLL_IMPORT ABG_FX_bonfire : public AEmitter
{
public:
}; // Size: 0x0000

// Class XEffects.ShellSpewer
class DLL_IMPORT AShellSpewer : public AwEmitter
{
public:
	class USound*                                      ShellImpactSnd;                                   		// 0x05B8 ( 0x0004 ) [ CPF_Edit ]

	// UScript Functions
	 void                      Trigger ( class AActor* Other, class APawn* EventInstigator );		// [ FUNC_Simulated ] XEffects.ShellSpewer.Trigger
	 void                      CollisionSound (  );                              		//  XEffects.ShellSpewer.CollisionSound
}; // Size: 0x0004

// Class XEffects.ShellSpewer_9
class DLL_IMPORT AShellSpewer_9 : public AShellSpewer
{
public:
}; // Size: 0x0000

// Class XEffects.Pistol_MuzFlash_01_1rd
class DLL_IMPORT APistol_MuzFlash_01_1rd : public AwEmitter
{
public:
	int                                                mNumPerFlash;                                     		// 0x05B8 ( 0x0004 ) 

	// UScript Functions
	 void                      Trigger ( class AActor* Other, class APawn* EventInstigator );		// [ FUNC_Simulated ] XEffects.Pistol_MuzFlash_01_1rd.Trigger
}; // Size: 0x0004

// Class XEffects.PistolMuzzleSmoke
class DLL_IMPORT APistolMuzzleSmoke : public AwEmitter
{
public:
	int                                                mNumPerFire;                                      		// 0x05B8 ( 0x0004 ) 

	// UScript Functions
	 void                      Trigger ( class AActor* Other, class APawn* EventInstigator );		// [ FUNC_Simulated ] XEffects.PistolMuzzleSmoke.Trigger
}; // Size: 0x0004

// Class XEffects.ShellSpewer_762
class DLL_IMPORT AShellSpewer_762 : public AShellSpewer
{
public:
}; // Size: 0x0000

// Class XEffects.AR_MuzFlash_03_1RD
class DLL_IMPORT AAR_MuzFlash_03_1RD : public AwEmitter
{
public:
	int                                                mNumPerFlash;                                     		// 0x05B8 ( 0x0004 ) 

	// UScript Functions
	 void                      Trigger ( class AActor* Other, class APawn* EventInstigator );		// [ FUNC_Simulated ] XEffects.AR_MuzFlash_03_1RD.Trigger
}; // Size: 0x0004

// Class XEffects.AssaultMuzzleSmoke
class DLL_IMPORT AAssaultMuzzleSmoke : public AwEmitter
{
public:
	int                                                mNumPerFire;                                      		// 0x05B8 ( 0x0004 ) 

	// UScript Functions
	 void                      Trigger ( class AActor* Other, class APawn* EventInstigator );		// [ FUNC_Simulated ] XEffects.AssaultMuzzleSmoke.Trigger
}; // Size: 0x0004

// Class XEffects.pclSmoke
class DLL_IMPORT ApclSmoke : public AwEmitter
{
public:
}; // Size: 0x0000

// Class XEffects.TransTrail
class DLL_IMPORT ATransTrail : public ApclSmoke
{
public:
}; // Size: 0x0000

// Class XEffects.AR_MuzFlash_01_3RD
class DLL_IMPORT AAR_MuzFlash_01_3RD : public AwEmitter
{
public:
	int                                                mNumPerFlash;                                     		// 0x05B8 ( 0x0004 ) 

	// UScript Functions
	 void                      Trigger ( class AActor* Other, class APawn* EventInstigator );		//  XEffects.AR_MuzFlash_01_3RD.Trigger
}; // Size: 0x0004

// Class XEffects.AR_MuzFlash_smoke_3RD
class DLL_IMPORT AAR_MuzFlash_smoke_3RD : public AEmitterThirdPerson
{
public:
}; // Size: 0x0000

// Class XEffects.Silencer_smoke_3RD
class DLL_IMPORT ASilencer_smoke_3RD : public AEmitterThirdPerson
{
public:
}; // Size: 0x0000

// Class XEffects.ShellSpewer_762_3rd
class DLL_IMPORT AShellSpewer_762_3rd : public AShellSpewer
{
public:
}; // Size: 0x0000

// Class XEffects.SMG_MuzFlash_01_3RD
class DLL_IMPORT ASMG_MuzFlash_01_3RD : public AwEmitter
{
public:
	int                                                mNumPerFlash;                                     		// 0x05B8 ( 0x0004 ) 

	// UScript Functions
	 void                      Trigger ( class AActor* Other, class APawn* EventInstigator );		//  XEffects.SMG_MuzFlash_01_3RD.Trigger
}; // Size: 0x0004

// Class XEffects.SMG_MuzFlash_smoke_3RD
class DLL_IMPORT ASMG_MuzFlash_smoke_3RD : public AEmitterThirdPerson
{
public:
}; // Size: 0x0000

// Class XEffects.ShellSpewer_9_3rd
class DLL_IMPORT AShellSpewer_9_3rd : public AShellSpewer
{
public:
}; // Size: 0x0000

// Class XEffects.SR_MuzFlash_04_3RD
class DLL_IMPORT ASR_MuzFlash_04_3RD : public AwEmitter
{
public:
	int                                                mNumPerFlash;                                     		// 0x05B8 ( 0x0004 ) 

	// UScript Functions
	 void                      Trigger ( class AActor* Other, class APawn* EventInstigator );		//  XEffects.SR_MuzFlash_04_3RD.Trigger
}; // Size: 0x0004

// Class XEffects.SR_MuzFlash_smoke_3RD
class DLL_IMPORT ASR_MuzFlash_smoke_3RD : public AEmitterThirdPerson
{
public:
}; // Size: 0x0000

// Class XEffects.AR_MuzFlash_02_3RD
class DLL_IMPORT AAR_MuzFlash_02_3RD : public AwEmitter
{
public:
	int                                                mNumPerFlash;                                     		// 0x05B8 ( 0x0004 ) 

	// UScript Functions
	 void                      Trigger ( class AActor* Other, class APawn* EventInstigator );		//  XEffects.AR_MuzFlash_02_3RD.Trigger
}; // Size: 0x0004

// Class XEffects.AR_MuzFlash_03_3RD
class DLL_IMPORT AAR_MuzFlash_03_3RD : public AwEmitter
{
public:
	int                                                mNumPerFlash;                                     		// 0x05B8 ( 0x0004 ) 

	// UScript Functions
	 void                      Trigger ( class AActor* Other, class APawn* EventInstigator );		//  XEffects.AR_MuzFlash_03_3RD.Trigger
}; // Size: 0x0004

// Class XEffects.AR_MuzFlash_03_3RD_M4A1
class DLL_IMPORT AAR_MuzFlash_03_3RD_M4A1 : public AwEmitter
{
public:
	int                                                mNumPerFlash;                                     		// 0x05B8 ( 0x0004 ) 

	// UScript Functions
	 void                      Trigger ( class AActor* Other, class APawn* EventInstigator );		//  XEffects.AR_MuzFlash_03_3RD_M4A1.Trigger
}; // Size: 0x0004

// Class XEffects.AR_MuzFlash_04_3RD
class DLL_IMPORT AAR_MuzFlash_04_3RD : public AwEmitter
{
public:
	int                                                mNumPerFlash;                                     		// 0x05B8 ( 0x0004 ) 

	// UScript Functions
	 void                      Trigger ( class AActor* Other, class APawn* EventInstigator );		//  XEffects.AR_MuzFlash_04_3RD.Trigger
}; // Size: 0x0004

// Class XEffects.Pistol_MuzFlash_01_3rd
class DLL_IMPORT APistol_MuzFlash_01_3rd : public AwEmitter
{
public:
	int                                                mNumPerFlash;                                     		// 0x05B8 ( 0x0004 ) 

	// UScript Functions
	 void                      Trigger ( class AActor* Other, class APawn* EventInstigator );		//  XEffects.Pistol_MuzFlash_01_3rd.Trigger
}; // Size: 0x0004

// Class XEffects.Pistol_MuzFlash_smoke_3RD
class DLL_IMPORT APistol_MuzFlash_smoke_3RD : public AEmitterThirdPerson
{
public:
}; // Size: 0x0000

// Class XEffects.ShellSpewer_50AE_3rd
class DLL_IMPORT AShellSpewer_50AE_3rd : public AShellSpewer
{
public:
}; // Size: 0x0000

// Class XEffects.RPG_MuzFlash_smoke_F_3RD
class DLL_IMPORT ARPG_MuzFlash_smoke_F_3RD : public AEmitterThirdPerson
{
public:
}; // Size: 0x0000

#ifdef _MSC_VER
#pragma pack ( pop )
#endif

