#pragma once
/*
# ======================================================================================== #
# > ArcticCombat SDK
# > Generated By HJSdkGen v1.06b
# ---------------------------------------------------------------------------------------- #
# > Package : XEffects
# >    File : ParamStructs.h
# ======================================================================================== #
*/

#ifdef _MSC_VER
#pragma pack ( push, 4 )
#endif

// Function XEffects.XWFX_Artillery_explosion.PostBeginPlay
// Flags: [ FUNC_Simulated ]
struct AXWFX_Artillery_explosion_execPostBeginPlay_Parms
{
	class APlayerController*                           PC;                                               		// 0x0000 ( 0x0004
	float                                              dist;                                             		// 0x0004 ( 0x0004
};

// Function XEffects.RocketMark.PostBeginPlay
// Flags: 
struct ARocketMark_execPostBeginPlay_Parms
{
};

// Function XEffects.xScorch.PostBeginPlay
// Flags: 
struct AxScorch_execPostBeginPlay_Parms
{
	struct FVector                                     rX;                                               		// 0x0000 ( 0x000C
	struct FVector                                     rY;                                               		// 0x000C ( 0x000C
	struct FVector                                     RZ;                                               		// 0x0018 ( 0x000C
	struct FRotator                                    R;                                                		// 0x0024 ( 0x000C
};

// Function XEffects.xScorch.PreBeginPlay
// Flags: [ FUNC_Event ]
struct AxScorch_eventPreBeginPlay_Parms
{
	class APlayerController*                           PC;                                               		// 0x0000 ( 0x0004
};

// Function XEffects.XWFX_SD_Bomb_explosion.PostBeginPlay
// Flags: [ FUNC_Simulated ]
struct AXWFX_SD_Bomb_explosion_execPostBeginPlay_Parms
{
	class APlayerController*                           PC;                                               		// 0x0000 ( 0x0004
	float                                              dist;                                             		// 0x0004 ( 0x0004
};

// Function XEffects.XWFX_Grenade_explosion.PostBeginPlay
// Flags: [ FUNC_Simulated ]
struct AXWFX_Grenade_explosion_execPostBeginPlay_Parms
{
	class APlayerController*                           PC;                                               		// 0x0000 ( 0x0004
	float                                              dist;                                             		// 0x0004 ( 0x0004
};

// Function XEffects.XWFX_Grenade_explosion_dirt.PostBeginPlay
// Flags: [ FUNC_Simulated ]
struct AXWFX_Grenade_explosion_dirt_execPostBeginPlay_Parms
{
	class APlayerController*                           PC;                                               		// 0x0000 ( 0x0004
	float                                              dist;                                             		// 0x0004 ( 0x0004
};

// Function XEffects.XWFX_Grenade_explosion_grass.PostBeginPlay
// Flags: [ FUNC_Simulated ]
struct AXWFX_Grenade_explosion_grass_execPostBeginPlay_Parms
{
	class APlayerController*                           PC;                                               		// 0x0000 ( 0x0004
	float                                              dist;                                             		// 0x0004 ( 0x0004
};

// Function XEffects.XWFX_Grenade_explosion_metal.PostBeginPlay
// Flags: [ FUNC_Simulated ]
struct AXWFX_Grenade_explosion_metal_execPostBeginPlay_Parms
{
	class APlayerController*                           PC;                                               		// 0x0000 ( 0x0004
	float                                              dist;                                             		// 0x0004 ( 0x0004
};

// Function XEffects.XWFX_Grenade_explosion_snow.PostBeginPlay
// Flags: [ FUNC_Simulated ]
struct AXWFX_Grenade_explosion_snow_execPostBeginPlay_Parms
{
	class APlayerController*                           PC;                                               		// 0x0000 ( 0x0004
	float                                              dist;                                             		// 0x0004 ( 0x0004
};

// Function XEffects.XWFX_Grenade_explosion_water.PostBeginPlay
// Flags: [ FUNC_Simulated ]
struct AXWFX_Grenade_explosion_water_execPostBeginPlay_Parms
{
	class APlayerController*                           PC;                                               		// 0x0000 ( 0x0004
	float                                              dist;                                             		// 0x0004 ( 0x0004
};

// Function XEffects.XWFX_Grenade_explosion_wood.PostBeginPlay
// Flags: [ FUNC_Simulated ]
struct AXWFX_Grenade_explosion_wood_execPostBeginPlay_Parms
{
	class APlayerController*                           PC;                                               		// 0x0000 ( 0x0004
	float                                              dist;                                             		// 0x0004 ( 0x0004
};

// Function XEffects.XWFX_Time_C4_explosion.PostBeginPlay
// Flags: [ FUNC_Simulated ]
struct AXWFX_Time_C4_explosion_execPostBeginPlay_Parms
{
	class APlayerController*                           PC;                                               		// 0x0000 ( 0x0004
	float                                              dist;                                             		// 0x0004 ( 0x0004
};

// Function XEffects.XWFX_Stun_explosion.PostBeginPlay
// Flags: [ FUNC_Simulated ]
struct AXWFX_Stun_explosion_execPostBeginPlay_Parms
{
	class APlayerController*                           PC;                                               		// 0x0000 ( 0x0004
	float                                              dist;                                             		// 0x0004 ( 0x0004
};

// Function XEffects.XWFX_Grenade_smoke.PostBeginPlay
// Flags: [ FUNC_Simulated ]
struct AXWFX_Grenade_smoke_execPostBeginPlay_Parms
{
	class APlayerController*                           PC;                                               		// 0x0000 ( 0x0004
	float                                              dist;                                             		// 0x0004 ( 0x0004
};

// Function XEffects.HitEffect_heli_attack_BulletHole.PostBeginPlay
// Flags: 
struct AHitEffect_heli_attack_BulletHole_execPostBeginPlay_Parms
{
};

// Function XEffects.RocketMark_gr.PostBeginPlay
// Flags: 
struct ARocketMark_gr_execPostBeginPlay_Parms
{
};

// Function XEffects.XWFX_IncGrenade_explosion.PostBeginPlay
// Flags: [ FUNC_Simulated ]
struct AXWFX_IncGrenade_explosion_execPostBeginPlay_Parms
{
	class APlayerController*                           PC;                                               		// 0x0000 ( 0x0004
	float                                              dist;                                             		// 0x0004 ( 0x0004
};

// Function XEffects.XWFX_IncGrenade_Flame_Ally.Tick
// Flags: [ FUNC_Simulated | FUNC_Event ]
struct AXWFX_IncGrenade_Flame_Ally_eventTick_Parms
{
	float                                              DeltaTime;                                        		// 0x0000 ( 0x0004[ CPF_Parm ]
	int                                                i;                                                		// 0x0004 ( 0x0004
};

// Function XEffects.XWFX_IncGrenade_Flame_Ally.PostBeginPlay
// Flags: [ FUNC_Simulated ]
struct AXWFX_IncGrenade_Flame_Ally_execPostBeginPlay_Parms
{
	class APlayerController*                           PC;                                               		// 0x0000 ( 0x0004
	float                                              dist;                                             		// 0x0004 ( 0x0004
};

// Function XEffects.XWFX_IncGrenade_Flame_Enemy.Tick
// Flags: [ FUNC_Simulated | FUNC_Event ]
struct AXWFX_IncGrenade_Flame_Enemy_eventTick_Parms
{
	float                                              DeltaTime;                                        		// 0x0000 ( 0x0004[ CPF_Parm ]
	int                                                i;                                                		// 0x0004 ( 0x0004
};

// Function XEffects.XWFX_IncGrenade_Flame_Enemy.PostBeginPlay
// Flags: [ FUNC_Simulated ]
struct AXWFX_IncGrenade_Flame_Enemy_execPostBeginPlay_Parms
{
	class APlayerController*                           PC;                                               		// 0x0000 ( 0x0004
	float                                              dist;                                             		// 0x0004 ( 0x0004
};

// Function XEffects.XWFX_SplitGrenade.PostBeginPlay
// Flags: [ FUNC_Simulated ]
struct AXWFX_SplitGrenade_execPostBeginPlay_Parms
{
	class APlayerController*                           PC;                                               		// 0x0000 ( 0x0004
	float                                              dist;                                             		// 0x0004 ( 0x0004
};

// Function XEffects.XWFX_SplitGndFragment_explo.PostBeginPlay
// Flags: [ FUNC_Simulated ]
struct AXWFX_SplitGndFragment_explo_execPostBeginPlay_Parms
{
	class APlayerController*                           PC;                                               		// 0x0000 ( 0x0004
	float                                              dist;                                             		// 0x0004 ( 0x0004
};

// Function XEffects.Event_Cash_Gacha_XMAS_GR_mark_01.PostBeginPlay
// Flags: 
struct AEvent_Cash_Gacha_XMAS_GR_mark_01_execPostBeginPlay_Parms
{
};

// Function XEffects.xPawnGibGroup.GibSound
// Flags: 
struct UxPawnGibGroup_execGibSound_Parms
{
	class USound*                                      ReturnValue;                                      		// 0x0000 ( 0x0004[ CPF_Parm | CPF_OutParm | CPF_ReturnParm ]
};

// Function XEffects.xPawnGibGroup.GetBloodEmitClass
// Flags: 
struct UxPawnGibGroup_execGetBloodEmitClass_Parms
{
	class UClass*                                      ReturnValue;                                      		// 0x0000 ( 0x0004[ CPF_Parm | CPF_OutParm | CPF_ReturnParm ]
};

// Function XEffects.xPawnGibGroup.GetGibClass
// Flags: 
struct UxPawnGibGroup_execGetGibClass_Parms
{
	unsigned char                                      gibType;                                          		// 0x0000 ( 0x0001[ CPF_Parm ]
	class UClass*                                      ReturnValue;                                      		// 0x0004 ( 0x0004[ CPF_Parm | CPF_OutParm | CPF_ReturnParm ]
};

// Function XEffects.xPawnGibGroup.PrecacheContent
// Flags: 
struct UxPawnGibGroup_execPrecacheContent_Parms
{
	class ALevelInfo*                                  Level;                                            		// 0x0000 ( 0x0004[ CPF_Parm ]
	int                                                i;                                                		// 0x0004 ( 0x0004
};

// Function XEffects.Gib.SetTeam
// Flags: [ FUNC_Simulated ]
struct AGib_execSetTeam_Parms
{
	struct FString                                     strSTMeshName;                                    		// 0x0000 ( 0x000C[ CPF_Parm | CPF_NeedCtorLink ]
};

// Function XEffects.Gib.SpawnTrail
// Flags: [ FUNC_Simulated ]
struct AGib_execSpawnTrail_Parms
{
};

// Function XEffects.Gib.HitWall
// Flags: [ FUNC_Simulated ]
struct AGib_execHitWall_Parms
{
	struct FVector                                     HitNormal;                                        		// 0x0000 ( 0x000C[ CPF_Parm ]
	class AActor*                                      Wall;                                             		// 0x000C ( 0x0004[ CPF_Parm ]
	class UMaterial*                                   HitMaterial;                                      		// 0x0010 ( 0x0004[ CPF_Parm ]
	float                                              Speed;                                            		// 0x0014 ( 0x0004
	float                                              MinSpeed;                                         		// 0x0018 ( 0x0004
};

// Function XEffects.Gib.Landed
// Flags: [ FUNC_Simulated ]
struct AGib_execLanded_Parms
{
	struct FVector                                     HitNormal;                                        		// 0x0000 ( 0x000C[ CPF_Parm ]
};

// Function XEffects.Gib.RandSpin
// Flags: [ FUNC_Final | FUNC_Simulated ]
struct AGib_execRandSpin_Parms
{
	float                                              spinRate;                                         		// 0x0000 ( 0x0004[ CPF_Parm ]
};

// Function XEffects.Gib.Destroyed
// Flags: [ FUNC_Simulated ]
struct AGib_execDestroyed_Parms
{
};

// Function XEffects.GibArmL.SetTeam
// Flags: [ FUNC_Simulated ]
struct AGibArmL_execSetTeam_Parms
{
	struct FString                                     strSTMeshName;                                    		// 0x0000 ( 0x000C[ CPF_Parm | CPF_NeedCtorLink ]
	class UStaticMesh*                                 NewMesh;                                          		// 0x000C ( 0x0004
};

// Function XEffects.GibArmR.SetTeam
// Flags: [ FUNC_Simulated ]
struct AGibArmR_execSetTeam_Parms
{
	struct FString                                     strSTMeshName;                                    		// 0x0000 ( 0x000C[ CPF_Parm | CPF_NeedCtorLink ]
	class UStaticMesh*                                 NewMesh;                                          		// 0x000C ( 0x0004
};

// Function XEffects.GibLegL.SetTeam
// Flags: [ FUNC_Simulated ]
struct AGibLegL_execSetTeam_Parms
{
	struct FString                                     strSTMeshName;                                    		// 0x0000 ( 0x000C[ CPF_Parm | CPF_NeedCtorLink ]
	class UStaticMesh*                                 NewMesh;                                          		// 0x000C ( 0x0004
};

// Function XEffects.GibLegR.SetTeam
// Flags: [ FUNC_Simulated ]
struct AGibLegR_execSetTeam_Parms
{
	struct FString                                     strSTMeshName;                                    		// 0x0000 ( 0x000C[ CPF_Parm | CPF_NeedCtorLink ]
	class UStaticMesh*                                 NewMesh;                                          		// 0x000C ( 0x0004
};

// Function XEffects.GibHead.SetTeam
// Flags: [ FUNC_Simulated ]
struct AGibHead_execSetTeam_Parms
{
	struct FString                                     strSTMeshName;                                    		// 0x0000 ( 0x000C[ CPF_Parm | CPF_NeedCtorLink ]
	class UStaticMesh*                                 NewMesh;                                          		// 0x000C ( 0x0004
};

// Function XEffects.BloodSpurt.PrecacheContent
// Flags: 
struct ABloodSpurt_execPrecacheContent_Parms
{
	class ALevelInfo*                                  Level;                                            		// 0x0000 ( 0x0004[ CPF_Parm ]
	int                                                i;                                                		// 0x0004 ( 0x0004
};

// Function XEffects.BloodSpurt.WallSplat
// Flags: [ FUNC_Simulated ]
struct ABloodSpurt_execWallSplat_Parms
{
	struct FVector                                     WallHit;                                          		// 0x0000 ( 0x000C
	struct FVector                                     WallNormal;                                       		// 0x000C ( 0x000C
	class AActor*                                      WallActor;                                        		// 0x0018 ( 0x0004
};

// Function XEffects.BloodSpurt.PostNetBeginPlay
// Flags: [ FUNC_Simulated ]
struct ABloodSpurt_execPostNetBeginPlay_Parms
{
};

// Function XEffects.BloodSmallHit_A.PostNetBeginPlay
// Flags: [ FUNC_Simulated ]
struct ABloodSmallHit_A_execPostNetBeginPlay_Parms
{
};

// Function XEffects.BloodSmallHit_B.PostNetBeginPlay
// Flags: [ FUNC_Simulated ]
struct ABloodSmallHit_B_execPostNetBeginPlay_Parms
{
};

// Function XEffects.BloodSpurt_Teen.PrecacheContent
// Flags: 
struct ABloodSpurt_Teen_execPrecacheContent_Parms
{
	class ALevelInfo*                                  Level;                                            		// 0x0000 ( 0x0004[ CPF_Parm ]
	int                                                i;                                                		// 0x0004 ( 0x0004
};

// Function XEffects.BloodSpurt_Teen.WallSplat
// Flags: [ FUNC_Simulated ]
struct ABloodSpurt_Teen_execWallSplat_Parms
{
	struct FVector                                     WallHit;                                          		// 0x0000 ( 0x000C
	struct FVector                                     WallNormal;                                       		// 0x000C ( 0x000C
	class AActor*                                      WallActor;                                        		// 0x0018 ( 0x0004
};

// Function XEffects.BloodSpurt_Teen.PostNetBeginPlay
// Flags: [ FUNC_Simulated ]
struct ABloodSpurt_Teen_execPostNetBeginPlay_Parms
{
};

// Function XEffects.BloodJet.WallSplat
// Flags: [ FUNC_Simulated ]
struct ABloodJet_execWallSplat_Parms
{
	struct FVector                                     WallHit;                                          		// 0x0000 ( 0x000C
	struct FVector                                     WallNormal;                                       		// 0x000C ( 0x000C
	class AActor*                                      WallActor;                                        		// 0x0018 ( 0x0004
};

// Function XEffects.BloodJet.PostNetBeginPlay
// Flags: [ FUNC_Simulated ]
struct ABloodJet_execPostNetBeginPlay_Parms
{
};

// Function XEffects.BloodJet.Timer
// Flags: [ FUNC_Simulated ]
struct ABloodJet_execTimer_Parms
{
};

// Function XEffects.HelicopterHitEffect.PostNetBeginPlay
// Flags: [ FUNC_Simulated ]
struct AHelicopterHitEffect_execPostNetBeginPlay_Parms
{
};

// Function XEffects.HitFlameBig.PostNetBeginPlay
// Flags: [ FUNC_Simulated ]
struct AHitFlameBig_execPostNetBeginPlay_Parms
{
};

// Function XEffects.HitFlameBig.Timer
// Flags: [ FUNC_Simulated ]
struct AHitFlameBig_execTimer_Parms
{
};

// Function XEffects.BloodHit_spurt.WallSplat
// Flags: [ FUNC_Simulated ]
struct ABloodHit_spurt_execWallSplat_Parms
{
	struct FVector                                     WallHit;                                          		// 0x0000 ( 0x000C
	struct FVector                                     WallNormal;                                       		// 0x000C ( 0x000C
	class AActor*                                      WallActor;                                        		// 0x0018 ( 0x0004
};

// Function XEffects.BloodHit_spurt.PostNetBeginPlay
// Flags: [ FUNC_Simulated ]
struct ABloodHit_spurt_execPostNetBeginPlay_Parms
{
};

// Function XEffects.BloodSplatter.PostBeginPlay
// Flags: [ FUNC_Simulated ]
struct ABloodSplatter_execPostBeginPlay_Parms
{
};

// Function XEffects.HitEffect_Blood.SpawnEffects
// Flags: [ FUNC_Simulated ]
struct AHitEffect_Blood_execSpawnEffects_Parms
{
};

// Function XEffects.HitEffect_Blood.PostNetBeginPlay
// Flags: [ FUNC_Simulated ]
struct AHitEffect_Blood_execPostNetBeginPlay_Parms
{
};

// Function XEffects.BloodSplatter_Teen.PostBeginPlay
// Flags: [ FUNC_Simulated ]
struct ABloodSplatter_Teen_execPostBeginPlay_Parms
{
};

// Function XEffects.HitEffect_Teen_Blood.SpawnEffects
// Flags: [ FUNC_Simulated ]
struct AHitEffect_Teen_Blood_execSpawnEffects_Parms
{
};

// Function XEffects.HitEffect_Teen_Blood.PostNetBeginPlay
// Flags: [ FUNC_Simulated ]
struct AHitEffect_Teen_Blood_execPostNetBeginPlay_Parms
{
};

// Function XEffects.HitEffect_Metal.SpawnEffects
// Flags: [ FUNC_Simulated ]
struct AHitEffect_Metal_execSpawnEffects_Parms
{
	class APlayerController*                           P;                                                		// 0x0000 ( 0x0004
	unsigned long                                      bViewed:1;                                        		// 0x0004 ( 0x0004 [0x00000001]
};

// Function XEffects.HitEffect_Metal.PostNetBeginPlay
// Flags: [ FUNC_Simulated ]
struct AHitEffect_Metal_execPostNetBeginPlay_Parms
{
};

// Function XEffects.HitEffect_blood_headshot.SpawnEffects
// Flags: [ FUNC_Simulated ]
struct AHitEffect_blood_headshot_execSpawnEffects_Parms
{
};

// Function XEffects.HitEffect_blood_headshot.PostNetBeginPlay
// Flags: [ FUNC_Simulated ]
struct AHitEffect_blood_headshot_execPostNetBeginPlay_Parms
{
};

// Function XEffects.HitEffect_teen_blood_headshot.SpawnEffects
// Flags: [ FUNC_Simulated ]
struct AHitEffect_teen_blood_headshot_execSpawnEffects_Parms
{
};

// Function XEffects.HitEffect_teen_blood_headshot.PostNetBeginPlay
// Flags: [ FUNC_Simulated ]
struct AHitEffect_teen_blood_headshot_execPostNetBeginPlay_Parms
{
};

// Function XEffects.HitEffect_blood_spurt.SpawnEffects
// Flags: [ FUNC_Simulated ]
struct AHitEffect_blood_spurt_execSpawnEffects_Parms
{
	class APlayerController*                           P;                                                		// 0x0000 ( 0x0004
	unsigned long                                      bViewed:1;                                        		// 0x0004 ( 0x0004 [0x00000001]
};

// Function XEffects.HitEffect_blood_spurt.PostNetBeginPlay
// Flags: [ FUNC_Simulated ]
struct AHitEffect_blood_spurt_execPostNetBeginPlay_Parms
{
};

// Function XEffects.HitEffect_metal_BulletHole.PostBeginPlay
// Flags: 
struct AHitEffect_metal_BulletHole_execPostBeginPlay_Parms
{
};

// Function XEffects.HitEffect_Concrete_BulletHole.PostBeginPlay
// Flags: 
struct AHitEffect_Concrete_BulletHole_execPostBeginPlay_Parms
{
};

// Function XEffects.Warfare_Tracer.SpawnParticle
// Flags: [ FUNC_Simulated ]
struct AWarfare_Tracer_execSpawnParticle_Parms
{
	int                                                Amount;                                           		// 0x0000 ( 0x0004[ CPF_Parm ]
	class APlayerController*                           PC;                                               		// 0x0004 ( 0x0004
	struct FVector                                     Dir;                                              		// 0x0008 ( 0x000C
	struct FVector                                     LineDir;                                          		// 0x0014 ( 0x000C
	struct FVector                                     LinePos;                                          		// 0x0020 ( 0x000C
	struct FVector                                     RealLocation;                                     		// 0x002C ( 0x000C
};

// Function XEffects.HitEffect_Default.SpawnEffects
// Flags: [ FUNC_Simulated ]
struct AHitEffect_Default_execSpawnEffects_Parms
{
	class APlayerController*                           P;                                                		// 0x0000 ( 0x0004
	unsigned long                                      bViewed:1;                                        		// 0x0004 ( 0x0004 [0x00000001]
};

// Function XEffects.HitEffect_Default.PostNetBeginPlay
// Flags: [ FUNC_Simulated ]
struct AHitEffect_Default_execPostNetBeginPlay_Parms
{
};

// Function XEffects.HitEffect_ETC.SpawnEffects
// Flags: [ FUNC_Simulated ]
struct AHitEffect_ETC_execSpawnEffects_Parms
{
	class APlayerController*                           P;                                                		// 0x0000 ( 0x0004
	unsigned long                                      bViewed:1;                                        		// 0x0004 ( 0x0004 [0x00000001]
};

// Function XEffects.HitEffect_ETC.PostNetBeginPlay
// Flags: [ FUNC_Simulated ]
struct AHitEffect_ETC_execPostNetBeginPlay_Parms
{
};

// Function XEffects.HitEffect_rock.SpawnEffects
// Flags: [ FUNC_Simulated ]
struct AHitEffect_rock_execSpawnEffects_Parms
{
	class APlayerController*                           P;                                                		// 0x0000 ( 0x0004
	unsigned long                                      bViewed:1;                                        		// 0x0004 ( 0x0004 [0x00000001]
};

// Function XEffects.HitEffect_rock.PostNetBeginPlay
// Flags: [ FUNC_Simulated ]
struct AHitEffect_rock_execPostNetBeginPlay_Parms
{
};

// Function XEffects.HitEffect_brick.SpawnEffects
// Flags: [ FUNC_Simulated ]
struct AHitEffect_brick_execSpawnEffects_Parms
{
	class APlayerController*                           P;                                                		// 0x0000 ( 0x0004
	unsigned long                                      bViewed:1;                                        		// 0x0004 ( 0x0004 [0x00000001]
};

// Function XEffects.HitEffect_brick.PostNetBeginPlay
// Flags: [ FUNC_Simulated ]
struct AHitEffect_brick_execPostNetBeginPlay_Parms
{
};

// Function XEffects.HitEffect_Concrete.SpawnEffects
// Flags: [ FUNC_Simulated ]
struct AHitEffect_Concrete_execSpawnEffects_Parms
{
	class APlayerController*                           P;                                                		// 0x0000 ( 0x0004
	unsigned long                                      bViewed:1;                                        		// 0x0004 ( 0x0004 [0x00000001]
};

// Function XEffects.HitEffect_Concrete.PostNetBeginPlay
// Flags: [ FUNC_Simulated ]
struct AHitEffect_Concrete_execPostNetBeginPlay_Parms
{
};

// Function XEffects.HitEffect_Dirt.SpawnEffects
// Flags: [ FUNC_Simulated ]
struct AHitEffect_Dirt_execSpawnEffects_Parms
{
	class APlayerController*                           P;                                                		// 0x0000 ( 0x0004
	unsigned long                                      bViewed:1;                                        		// 0x0004 ( 0x0004 [0x00000001]
};

// Function XEffects.HitEffect_Dirt.PostNetBeginPlay
// Flags: [ FUNC_Simulated ]
struct AHitEffect_Dirt_execPostNetBeginPlay_Parms
{
};

// Function XEffects.HitEffect_Metal_PT.SpawnEffects
// Flags: [ FUNC_Simulated ]
struct AHitEffect_Metal_PT_execSpawnEffects_Parms
{
	class APlayerController*                           P;                                                		// 0x0000 ( 0x0004
	unsigned long                                      bViewed:1;                                        		// 0x0004 ( 0x0004 [0x00000001]
};

// Function XEffects.HitEffect_Metal_PT.PostNetBeginPlay
// Flags: [ FUNC_Simulated ]
struct AHitEffect_Metal_PT_execPostNetBeginPlay_Parms
{
};

// Function XEffects.HitEffect_Wood.SpawnEffects
// Flags: [ FUNC_Simulated ]
struct AHitEffect_Wood_execSpawnEffects_Parms
{
	class APlayerController*                           P;                                                		// 0x0000 ( 0x0004
	unsigned long                                      bViewed:1;                                        		// 0x0004 ( 0x0004 [0x00000001]
};

// Function XEffects.HitEffect_Wood.PostNetBeginPlay
// Flags: [ FUNC_Simulated ]
struct AHitEffect_Wood_execPostNetBeginPlay_Parms
{
};

// Function XEffects.HitEffect_plant.SpawnEffects
// Flags: [ FUNC_Simulated ]
struct AHitEffect_plant_execSpawnEffects_Parms
{
	class APlayerController*                           P;                                                		// 0x0000 ( 0x0004
	unsigned long                                      bViewed:1;                                        		// 0x0004 ( 0x0004 [0x00000001]
};

// Function XEffects.HitEffect_plant.PostNetBeginPlay
// Flags: [ FUNC_Simulated ]
struct AHitEffect_plant_execPostNetBeginPlay_Parms
{
};

// Function XEffects.HitEffect_flesh.SpawnEffects
// Flags: [ FUNC_Simulated ]
struct AHitEffect_flesh_execSpawnEffects_Parms
{
	class APlayerController*                           P;                                                		// 0x0000 ( 0x0004
	unsigned long                                      bViewed:1;                                        		// 0x0004 ( 0x0004 [0x00000001]
};

// Function XEffects.HitEffect_flesh.PostNetBeginPlay
// Flags: [ FUNC_Simulated ]
struct AHitEffect_flesh_execPostNetBeginPlay_Parms
{
};

// Function XEffects.HitEffect_snow.SpawnEffects
// Flags: [ FUNC_Simulated ]
struct AHitEffect_snow_execSpawnEffects_Parms
{
	class APlayerController*                           P;                                                		// 0x0000 ( 0x0004
	unsigned long                                      bViewed:1;                                        		// 0x0004 ( 0x0004 [0x00000001]
};

// Function XEffects.HitEffect_snow.PostNetBeginPlay
// Flags: [ FUNC_Simulated ]
struct AHitEffect_snow_execPostNetBeginPlay_Parms
{
};

// Function XEffects.HitEffect_water.SpawnEffects
// Flags: [ FUNC_Simulated ]
struct AHitEffect_water_execSpawnEffects_Parms
{
};

// Function XEffects.HitEffect_water.PostNetBeginPlay
// Flags: [ FUNC_Simulated ]
struct AHitEffect_water_execPostNetBeginPlay_Parms
{
};

// Function XEffects.HitEffect_glass.SpawnEffects
// Flags: [ FUNC_Simulated ]
struct AHitEffect_glass_execSpawnEffects_Parms
{
	class APlayerController*                           P;                                                		// 0x0000 ( 0x0004
	unsigned long                                      bViewed:1;                                        		// 0x0004 ( 0x0004 [0x00000001]
};

// Function XEffects.HitEffect_glass.PostNetBeginPlay
// Flags: [ FUNC_Simulated ]
struct AHitEffect_glass_execPostNetBeginPlay_Parms
{
};

// Function XEffects.HitEffect_cotton.SpawnEffects
// Flags: [ FUNC_Simulated ]
struct AHitEffect_cotton_execSpawnEffects_Parms
{
	class APlayerController*                           P;                                                		// 0x0000 ( 0x0004
	unsigned long                                      bViewed:1;                                        		// 0x0004 ( 0x0004 [0x00000001]
};

// Function XEffects.HitEffect_cotton.PostNetBeginPlay
// Flags: [ FUNC_Simulated ]
struct AHitEffect_cotton_execPostNetBeginPlay_Parms
{
};

// Function XEffects.HitEffect_blood_death.SpawnEffects
// Flags: [ FUNC_Simulated ]
struct AHitEffect_blood_death_execSpawnEffects_Parms
{
	class APlayerController*                           P;                                                		// 0x0000 ( 0x0004
	unsigned long                                      bViewed:1;                                        		// 0x0004 ( 0x0004 [0x00000001]
};

// Function XEffects.HitEffect_blood_death.PostNetBeginPlay
// Flags: [ FUNC_Simulated ]
struct AHitEffect_blood_death_execPostNetBeginPlay_Parms
{
};

// Function XEffects.HitEffect_CrackWood.SpawnEffects
// Flags: [ FUNC_Simulated ]
struct AHitEffect_CrackWood_execSpawnEffects_Parms
{
	class APlayerController*                           P;                                                		// 0x0000 ( 0x0004
	unsigned long                                      bViewed:1;                                        		// 0x0004 ( 0x0004 [0x00000001]
};

// Function XEffects.HitEffect_CrackWood.PostNetBeginPlay
// Flags: [ FUNC_Simulated ]
struct AHitEffect_CrackWood_execPostNetBeginPlay_Parms
{
};

// Function XEffects.HitEffect_Plastic.SpawnEffects
// Flags: [ FUNC_Simulated ]
struct AHitEffect_Plastic_execSpawnEffects_Parms
{
	class APlayerController*                           P;                                                		// 0x0000 ( 0x0004
	unsigned long                                      bViewed:1;                                        		// 0x0004 ( 0x0004 [0x00000001]
};

// Function XEffects.HitEffect_Plastic.PostNetBeginPlay
// Flags: [ FUNC_Simulated ]
struct AHitEffect_Plastic_execPostNetBeginPlay_Parms
{
};

// Function XEffects.HitEffect_Paper.SpawnEffects
// Flags: [ FUNC_Simulated ]
struct AHitEffect_Paper_execSpawnEffects_Parms
{
	class APlayerController*                           P;                                                		// 0x0000 ( 0x0004
	unsigned long                                      bViewed:1;                                        		// 0x0004 ( 0x0004 [0x00000001]
};

// Function XEffects.HitEffect_Paper.PostNetBeginPlay
// Flags: [ FUNC_Simulated ]
struct AHitEffect_Paper_execPostNetBeginPlay_Parms
{
};

// Function XEffects.HitEffect_Rubber.SpawnEffects
// Flags: [ FUNC_Simulated ]
struct AHitEffect_Rubber_execSpawnEffects_Parms
{
	class APlayerController*                           P;                                                		// 0x0000 ( 0x0004
	unsigned long                                      bViewed:1;                                        		// 0x0004 ( 0x0004 [0x00000001]
};

// Function XEffects.HitEffect_Rubber.PostNetBeginPlay
// Flags: [ FUNC_Simulated ]
struct AHitEffect_Rubber_execPostNetBeginPlay_Parms
{
};

// Function XEffects.HitEffect_Carpet.SpawnEffects
// Flags: [ FUNC_Simulated ]
struct AHitEffect_Carpet_execSpawnEffects_Parms
{
	class APlayerController*                           P;                                                		// 0x0000 ( 0x0004
	unsigned long                                      bViewed:1;                                        		// 0x0004 ( 0x0004 [0x00000001]
};

// Function XEffects.HitEffect_Carpet.PostNetBeginPlay
// Flags: [ FUNC_Simulated ]
struct AHitEffect_Carpet_execPostNetBeginPlay_Parms
{
};

// Function XEffects.HitEffect_Leaves.SpawnEffects
// Flags: [ FUNC_Simulated ]
struct AHitEffect_Leaves_execSpawnEffects_Parms
{
	class APlayerController*                           P;                                                		// 0x0000 ( 0x0004
	unsigned long                                      bViewed:1;                                        		// 0x0004 ( 0x0004 [0x00000001]
};

// Function XEffects.HitEffect_Leaves.PostNetBeginPlay
// Flags: [ FUNC_Simulated ]
struct AHitEffect_Leaves_execPostNetBeginPlay_Parms
{
};

// Function XEffects.HitEffect_Cloth.SpawnEffects
// Flags: [ FUNC_Simulated ]
struct AHitEffect_Cloth_execSpawnEffects_Parms
{
	class APlayerController*                           P;                                                		// 0x0000 ( 0x0004
	unsigned long                                      bViewed:1;                                        		// 0x0004 ( 0x0004 [0x00000001]
};

// Function XEffects.HitEffect_Cloth.PostNetBeginPlay
// Flags: [ FUNC_Simulated ]
struct AHitEffect_Cloth_execPostNetBeginPlay_Parms
{
};

// Function XEffects.HitEffect_Sand.SpawnEffects
// Flags: [ FUNC_Simulated ]
struct AHitEffect_Sand_execSpawnEffects_Parms
{
	class APlayerController*                           P;                                                		// 0x0000 ( 0x0004
	unsigned long                                      bViewed:1;                                        		// 0x0004 ( 0x0004 [0x00000001]
};

// Function XEffects.HitEffect_Sand.PostNetBeginPlay
// Flags: [ FUNC_Simulated ]
struct AHitEffect_Sand_execPostNetBeginPlay_Parms
{
};

// Function XEffects.HitEffect_Mud.SpawnEffects
// Flags: [ FUNC_Simulated ]
struct AHitEffect_Mud_execSpawnEffects_Parms
{
	class APlayerController*                           P;                                                		// 0x0000 ( 0x0004
	unsigned long                                      bViewed:1;                                        		// 0x0004 ( 0x0004 [0x00000001]
};

// Function XEffects.HitEffect_Mud.PostNetBeginPlay
// Flags: [ FUNC_Simulated ]
struct AHitEffect_Mud_execPostNetBeginPlay_Parms
{
};

// Function XEffects.HitEffect_WaterFoot.SpawnEffects
// Flags: [ FUNC_Simulated ]
struct AHitEffect_WaterFoot_execSpawnEffects_Parms
{
};

// Function XEffects.HitEffect_WaterFoot.PostNetBeginPlay
// Flags: [ FUNC_Simulated ]
struct AHitEffect_WaterFoot_execPostNetBeginPlay_Parms
{
};

// Function XEffects.HitEffect_water_wall.SpawnEffects
// Flags: [ FUNC_Simulated ]
struct AHitEffect_water_wall_execSpawnEffects_Parms
{
};

// Function XEffects.HitEffect_water_wall.PostNetBeginPlay
// Flags: [ FUNC_Simulated ]
struct AHitEffect_water_wall_execPostNetBeginPlay_Parms
{
};

// Function XEffects.alien_tankersheld_hit.SpawnEffects
// Flags: [ FUNC_Simulated ]
struct Aalien_tankersheld_hit_execSpawnEffects_Parms
{
	class APlayerController*                           P;                                                		// 0x0000 ( 0x0004
	unsigned long                                      bViewed:1;                                        		// 0x0004 ( 0x0004 [0x00000001]
};

// Function XEffects.alien_tankersheld_hit.PostNetBeginPlay
// Flags: [ FUNC_Simulated ]
struct Aalien_tankersheld_hit_execPostNetBeginPlay_Parms
{
};

// Function XEffects.HitEffect_rock_BulletHole.PostBeginPlay
// Flags: 
struct AHitEffect_rock_BulletHole_execPostBeginPlay_Parms
{
};

// Function XEffects.HitEffect_dirt_BulletHole.PostBeginPlay
// Flags: 
struct AHitEffect_dirt_BulletHole_execPostBeginPlay_Parms
{
};

// Function XEffects.alien_tankersheld_hit_BulletHole.PostBeginPlay
// Flags: 
struct Aalien_tankersheld_hit_BulletHole_execPostBeginPlay_Parms
{
};

// Function XEffects.HitEffect_ETC_BulletHole.PostBeginPlay
// Flags: 
struct AHitEffect_ETC_BulletHole_execPostBeginPlay_Parms
{
};

// Function XEffects.HitEffect_wood_BulletHole.PostBeginPlay
// Flags: 
struct AHitEffect_wood_BulletHole_execPostBeginPlay_Parms
{
};

// Function XEffects.HitEffect_flesh_BulletHole.PostBeginPlay
// Flags: 
struct AHitEffect_flesh_BulletHole_execPostBeginPlay_Parms
{
};

// Function XEffects.HitEffect_brick_BulletHole.PostBeginPlay
// Flags: 
struct AHitEffect_brick_BulletHole_execPostBeginPlay_Parms
{
};

// Function XEffects.HitEffect_snow_BulletHole.PostBeginPlay
// Flags: 
struct AHitEffect_snow_BulletHole_execPostBeginPlay_Parms
{
};

// Function XEffects.HitEffect_glass_BulletHole.PostBeginPlay
// Flags: 
struct AHitEffect_glass_BulletHole_execPostBeginPlay_Parms
{
};

// Function XEffects.HitEffect_plant_BulletHole.PostBeginPlay
// Flags: 
struct AHitEffect_plant_BulletHole_execPostBeginPlay_Parms
{
};

// Function XEffects.HitEffect_metal_pt_BulletHole.PostBeginPlay
// Flags: 
struct AHitEffect_metal_pt_BulletHole_execPostBeginPlay_Parms
{
};

// Function XEffects.HitEffect_cotton_BulletHole.PostBeginPlay
// Flags: 
struct AHitEffect_cotton_BulletHole_execPostBeginPlay_Parms
{
};

// Function XEffects.ShellSpewer.Trigger
// Flags: [ FUNC_Simulated ]
struct AShellSpewer_execTrigger_Parms
{
	class AActor*                                      Other;                                            		// 0x0000 ( 0x0004[ CPF_Parm ]
	class APawn*                                       EventInstigator;                                  		// 0x0004 ( 0x0004[ CPF_Parm ]
};

// Function XEffects.ShellSpewer.CollisionSound
// Flags: 
struct AShellSpewer_execCollisionSound_Parms
{
};

// Function XEffects.Pistol_MuzFlash_01_1rd.Trigger
// Flags: [ FUNC_Simulated ]
struct APistol_MuzFlash_01_1rd_execTrigger_Parms
{
	class AActor*                                      Other;                                            		// 0x0000 ( 0x0004[ CPF_Parm ]
	class APawn*                                       EventInstigator;                                  		// 0x0004 ( 0x0004[ CPF_Parm ]
};

// Function XEffects.PistolMuzzleSmoke.Trigger
// Flags: [ FUNC_Simulated ]
struct APistolMuzzleSmoke_execTrigger_Parms
{
	class AActor*                                      Other;                                            		// 0x0000 ( 0x0004[ CPF_Parm ]
	class APawn*                                       EventInstigator;                                  		// 0x0004 ( 0x0004[ CPF_Parm ]
};

// Function XEffects.AR_MuzFlash_03_1RD.Trigger
// Flags: [ FUNC_Simulated ]
struct AAR_MuzFlash_03_1RD_execTrigger_Parms
{
	class AActor*                                      Other;                                            		// 0x0000 ( 0x0004[ CPF_Parm ]
	class APawn*                                       EventInstigator;                                  		// 0x0004 ( 0x0004[ CPF_Parm ]
};

// Function XEffects.AssaultMuzzleSmoke.Trigger
// Flags: [ FUNC_Simulated ]
struct AAssaultMuzzleSmoke_execTrigger_Parms
{
	class AActor*                                      Other;                                            		// 0x0000 ( 0x0004[ CPF_Parm ]
	class APawn*                                       EventInstigator;                                  		// 0x0004 ( 0x0004[ CPF_Parm ]
};

// Function XEffects.AR_MuzFlash_01_3RD.Trigger
// Flags: 
struct AAR_MuzFlash_01_3RD_execTrigger_Parms
{
	class AActor*                                      Other;                                            		// 0x0000 ( 0x0004[ CPF_Parm ]
	class APawn*                                       EventInstigator;                                  		// 0x0004 ( 0x0004[ CPF_Parm ]
};

// Function XEffects.SMG_MuzFlash_01_3RD.Trigger
// Flags: 
struct ASMG_MuzFlash_01_3RD_execTrigger_Parms
{
	class AActor*                                      Other;                                            		// 0x0000 ( 0x0004[ CPF_Parm ]
	class APawn*                                       EventInstigator;                                  		// 0x0004 ( 0x0004[ CPF_Parm ]
};

// Function XEffects.SR_MuzFlash_04_3RD.Trigger
// Flags: 
struct ASR_MuzFlash_04_3RD_execTrigger_Parms
{
	class AActor*                                      Other;                                            		// 0x0000 ( 0x0004[ CPF_Parm ]
	class APawn*                                       EventInstigator;                                  		// 0x0004 ( 0x0004[ CPF_Parm ]
};

// Function XEffects.AR_MuzFlash_02_3RD.Trigger
// Flags: 
struct AAR_MuzFlash_02_3RD_execTrigger_Parms
{
	class AActor*                                      Other;                                            		// 0x0000 ( 0x0004[ CPF_Parm ]
	class APawn*                                       EventInstigator;                                  		// 0x0004 ( 0x0004[ CPF_Parm ]
};

// Function XEffects.AR_MuzFlash_03_3RD.Trigger
// Flags: 
struct AAR_MuzFlash_03_3RD_execTrigger_Parms
{
	class AActor*                                      Other;                                            		// 0x0000 ( 0x0004[ CPF_Parm ]
	class APawn*                                       EventInstigator;                                  		// 0x0004 ( 0x0004[ CPF_Parm ]
};

// Function XEffects.AR_MuzFlash_03_3RD_M4A1.Trigger
// Flags: 
struct AAR_MuzFlash_03_3RD_M4A1_execTrigger_Parms
{
	class AActor*                                      Other;                                            		// 0x0000 ( 0x0004[ CPF_Parm ]
	class APawn*                                       EventInstigator;                                  		// 0x0004 ( 0x0004[ CPF_Parm ]
};

// Function XEffects.AR_MuzFlash_04_3RD.Trigger
// Flags: 
struct AAR_MuzFlash_04_3RD_execTrigger_Parms
{
	class AActor*                                      Other;                                            		// 0x0000 ( 0x0004[ CPF_Parm ]
	class APawn*                                       EventInstigator;                                  		// 0x0004 ( 0x0004[ CPF_Parm ]
};

// Function XEffects.Pistol_MuzFlash_01_3rd.Trigger
// Flags: 
struct APistol_MuzFlash_01_3rd_execTrigger_Parms
{
	class AActor*                                      Other;                                            		// 0x0000 ( 0x0004[ CPF_Parm ]
	class APawn*                                       EventInstigator;                                  		// 0x0004 ( 0x0004[ CPF_Parm ]
};

#ifdef _MSC_VER
#pragma pack ( pop )
#endif

