#pragma once
/*
# ======================================================================================== #
# > ArcticCombat SDK
# > Generated By HJSdkGen v1.06b
# ---------------------------------------------------------------------------------------- #
# > Package : WMission
# >    File : WMission\WMission.h
# ======================================================================================== #
*/


/*
# ======================================================================================== #
# > Forward Declarations
# ======================================================================================== #
*/

class AwMSCinematic_Camera;
class AwMSCinematic_SceneManager;
class AwSetObjective;
class AwMSGameReplicationInfo;
class AwMSGameInfo;
class AwDiffuseObjective;
class AwGameObject_Bomb;
class AwSDGameInfo;
class AwFlagObjective;
class AwDOMGameInfo;
class AwBombObjective;
class AwSBTBombObjective;
class AwGameObject_SBTBomb;
class AwSBTSetObjective;
class AwSBTSetObjective_AF;
class AwSBTDiffuseObjective;
class AwSBTDiffuseObjective_AF;
class AwSBTGameInfo;
class AwSBTSetObjective_RSA;
class AwSBTDiffuseObjective_RSA;
class AwBombObjective_Delivery;
class AwMSPlayerReplicationInfo;
class AwMessage_MSKillMessages;
class AwHUD_Mission;
class AwScoreBoard_Mission;
class AwInfoPod;
class AwTrigger_MSMessageTrigger;
class AwObjectivePointingArrow;
class AwAmmo_Dummy;
class AwObjectiveProgressDisplay;

/*
# ======================================================================================== #
# > Includes
# ======================================================================================== #
*/

#include "Structs.h"
#include "ParamStructs.h"
#include "Classes.h"
