#pragma once
/*
# ======================================================================================== #
# > ArcticCombat SDK
# > Generated By HJSdkGen v1.06b
# ---------------------------------------------------------------------------------------- #
# > Package : IpDrv
# >    File : Structs.h
# ======================================================================================== #
*/

#ifdef _MSC_VER
#pragma pack ( push, 4 )
#endif


/*
# ======================================================================================== #
# > Structs
# ======================================================================================== #
*/

// Struct IpDrv.MasterServerLink.tMasterServerEntry
class DLL_IMPORT FtMasterServerEntry
{
public:
	struct FString                                     Address;                                          		// 0x0000 ( 0x000C[ CPF_NeedCtorLink ]
	int                                                Port;                                             		// 0x000C ( 0x0004

	// Public Imports
	FtMasterServerEntry(struct FtMasterServerEntry const &);
	FtMasterServerEntry(void);
	~FtMasterServerEntry(void);
	struct FtMasterServerEntry &  operator=(struct FtMasterServerEntry const &);
}; // Size: 0x0010

// Struct IpDrv.MasterServerUplink.MD5UpdateData
class DLL_IMPORT FMD5UpdateData
{
public:
	struct FString                                     Guid;                                             		// 0x0000 ( 0x000C[ CPF_NeedCtorLink ]
	struct FString                                     MD5;                                              		// 0x000C ( 0x000C[ CPF_NeedCtorLink ]
	int                                                Revision;                                         		// 0x0018 ( 0x0004

	// Public Imports
	FMD5UpdateData(struct FMD5UpdateData const &);
	FMD5UpdateData(void);
	~FMD5UpdateData(void);
	struct FMD5UpdateData &  operator=(struct FMD5UpdateData const &);
}; // Size: 0x001C

// Struct IpDrv.InternetLink.IpAddr
class DLL_IMPORT FIpAddr
{
public:
	int                                                Addr;                                             		// 0x0000 ( 0x0004
	int                                                Port;                                             		// 0x0004 ( 0x0004

	// Public Imports
	FIpAddr(unsigned short const *,int);
	FIpAddr(struct sockaddr_in);
	FIpAddr(void);
	struct FIpAddr &  operator=(struct FIpAddr const &);
	int  operator==(struct FIpAddr &);
	struct sockaddr_in  GetSockAddr(void);
	class FString  GetString(int);
}; // Size: 0x0008

#ifdef _MSC_VER
#pragma pack ( pop )
#endif

